### ISSUE TITLE
gallery_generator.py running without error but in the feature directory no tensor is created

### ISSUE THREAD

**Issue by divdaisymuffin** [openvinotoolkit/dlstreamer_gst#101]
Hi,

I am working on face recognition pipeline, my aim is to insert face recognition pipeline into Smart city sample. For doing so, I am using face-detection-adas, landmark-regression and face-reidentification-retail model. 
I have created pipeline.json accordingly and given gvaidentify, from Ad-insertion pipeline I get to know that images should be converted to tensor and then given path to gvaidentify. So, I installed gst-video-analytics and then run gallery_generator.py, the pipeline is running but in output I am getting a gallery.json, which is half build and features directory empty.

Command that I run is 
python gst-video-analytics/samples/gst_launch/reidentification/gallery_generator.py -s face_gallery_FP32/ - o face_gallery_FP32/ -d test/Smart-City-Sample/analytics/object/models/face_detection_2020R2/1/FP32/face-detection-adas-0001.xml -i test/Smart-City-Sample/analytics/ob ject/models/landmarks_detection_2020R2/1/FP32/landmarks-regression-retail-0009.xml -l test/Smart-City-Sample/analytics/object/models/reidentification_detection_2020R2/ 1/FP32/face-reidentification-retail-0095.xml --identification_modelproc gst-video-analytics/samples/gst_launch/reidentification/model_proc/face-reidentification-retail -0095.json  --landmarks_regression_modelproc gst-video-analytics/samples/gst_launch/reidentification/model_proc/landmarks-regression-retail-0009.json

Please help me track the issue, I am also attaching some screenshots.
![script_run](https://user-images.githubusercontent.com/68895288/90434876-c4170200-e0eb-11ea-9104-1877f3959592.jpg)
![pipeline](https://user-images.githubusercontent.com/68895288/90434878-c5482f00-e0eb-11ea-8bbd-1d73035d2aa3.jpg)
![images](https://user-images.githubusercontent.com/68895288/90434881-c5e0c580-e0eb-11ea-8a3d-aafc7db6b9bf.JPG)
![directory](https://user-images.githubusercontent.com/68895288/90434882-c5e0c580-e0eb-11ea-9523-5103e55ce16c.JPG)
![gallery](https://user-images.githubusercontent.com/68895288/90434884-c6795c00-e0eb-11ea-80f4-8e5218be51da.JPG)

**Comment by intel-neena** [comment]
@divdaisymuffin Do you still have this issue? Can we close as it has been answered in other issues?

**Comment by divdaisymuffin** [comment]
@intel-neena thanks, no its been resolved, you can close it.

**Comment by intel-neena** [comment]
Great! Thank you for using DL Streamer!!
