### ISSUE TITLE
ModuleNotFoundError: No module named 'skbuild'

### ISSUE THREAD

**Issue by saychuan** [openvinotoolkit/dlstreamer_gst#105]
Not able to perform build by ./docker/build.sh due to versioning issue.

Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.36.11-2) ...
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/22/e7/4b2bdddb99f5f631d8c1de259897c2b7d65dcfcc1e0a6fd17a7f62923500/numpy-1.19.1-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
Collecting opencv-python
  Downloading https://files.pythonhosted.org/packages/77/f5/49f034f8d109efcf9b7e98fbc051878b83b2f02a1c73f92bbd37f317288e/opencv-python-4.4.0.42.tar.gz (88.9MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-99dapzsa/opencv-python/setup.py", line 9, in <module>
        import skbuild
    **_ModuleNotFoundError: No module named 'skbuild'_**

**Comment by tankienleong** [comment]
pip3 install --upgrade pip before install opencv-python

**Comment by abramov-oleg** [comment]
Another option is to downgrade `opencv-python==4.2.0.34`

**Comment by adranit** [comment]
Hi @saychuan,
I would recommend to use docker files from preview/audio-detect branch. This branch is based on 1.1.0 and it includes a couple hot fixes in docker files.

**Comment by intel-neena** [comment]
@saychuan Do you still need any help on this?

**Comment by mliu2020** [comment]
Hi @saychuan,

Did you solve the problem with @adranit's suggestion?

If this was solve, can I close this issue?

Mark

**Comment by saychuan** [comment]
yes, this issue resolved.

**Comment by mliu2020** [comment]
Thanks so much for the quick response.

We just have an update on OpenVINO 2021.1, you are welcome to try it and let us know any issues.

Mark

**Comment by swapnilwagh2204** [comment]
![Screenshot from 2021-01-19 16-30-16](https://user-images.githubusercontent.com/70155167/105025789-ceab3e00-5a73-11eb-963f-d5cf7acde392.png)
![Screenshot from 2021-01-19 16-30-59](https://user-images.githubusercontent.com/70155167/105025795-d10d9800-5a73-11eb-85f1-c5466f498d86.png)
![Screenshot from 2021-01-19 16-31-54](https://user-images.githubusercontent.com/70155167/105025825-db2f9680-5a73-11eb-933f-18bffb978dde.png)

unable to fix this error.....can somebody put light on it.

**Comment by tankienleong** [comment]
@swapnilwagh2204  upgrade the pip3 before install any packages

**Comment by swapnilwagh2204** [comment]
> @swapnilwagh2204 upgrade the pip3 before install any packages

hey @tankienleong ...thanks for the help.
i fixed this issue by using python:3.7-slim instead of python:3.6.1 alpine.

**Comment by BryanBo-Cao** [comment]
> pip3 install --upgrade pip before install opencv-python

Solved my problem! Thanks!

**Comment by mliu2020** [comment]
Thanks everyone for the info. Mark

**Comment by yustiks** [comment]
> pip3 install --upgrade pip before install opencv-python

worked for me as well
