### ISSUE TITLE
How to convert VASurface to System memory

### ISSUE THREAD

**Issue by sayanmutd** [openvinotoolkit/dlstreamer_gst#106]
Hi @umed , 

I wanted to know to know how to convert VASurface to System memory so that i can use tracking i.e gvatrack alongwith decoding and detection on Intel GPU. Please can you give example pipeline which can be taken as reference.

**Comment by sayanmutd** [comment]
@umed , I think vaapipostproc does the trick.

**Comment by adranit** [comment]
Hi @sayanmutd,
Sorry for late response. You are right, vaapipostproc can convert VASurface to System memory.
filesrc location=video.mp4 ! qtdemux ! vaapih264dec ! vaapipostproc ! video/x-raw(memory:VASurface) ! gvadetect pre-process-backend=vaapi model=model.xml ! queue ! gvatrack ! fakesink

**Comment by sayanmutd** [comment]
Hi, @adranit ,cannot take video/x-raw(
The above pipeline you have mentioned cannot directly link queue with gvatrack as because gvatrack cannot take video/x-raw(memory:VASurface) as the input caps. Therefore, we need to apply another vaapipostproc after queue to transfer VASurface to System memory

**Comment by intel-neena** [comment]
@sayanmutd gvatrack supports GPU memory from 2021.1 release. Please try the latest version and feel free to reopen if further help is needed.
