### ISSUE TITLE
How to generate JSON to classify human pose using model (human-pose-estimation-0001)

### ISSUE THREAD

**Issue by shef2608** [openvinotoolkit/dlstreamer_gst#107]
Hi Team,

I generated my own JSON for "human-pose-estimation model" and passed in model-proc but it is not working.
Please suggest a way how to generate it where i can achieve my bussiness logic.
Unable to find documentation how to make it. 

I tried existing model (person/vehicle) and model-proc (JSON) and it is working.

**Comment by dsmertin** [comment]
Hi @shef2608 ,

We do not have post-processing for 'human-pose-estimation' model in boundaries of 'gvaclassify' element.
You can implement it based on [OMZ demo](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/human_pose_estimation_demo).

Thanks,
Dmitry

**Comment by shef2608** [comment]
> Hi @shef2608 ,
> 
> We do not have post-processing for 'human-pose-estimation' model in boundaries of 'gvaclassify' element.
> You can implement it based on [OMZ demo](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/human_pose_estimation_demo).
> 
> Thanks,
> Dmitry

**Comment by shef2608** [comment]
@dsmertin Thanks for he reply,
But I am using gstreamer, and my pipeline is this
gvadetect model={} no-block=true threshold=0.6 device=CPU ! queue ! 

I have to use some models for huma-pose-estimation.

Thanks

**Comment by dsmertin** [comment]
You can use `gvainference` element, which raw data output attach to meta, and `gvapython` element, which can to provide you way to implement post-processing for HPE model.

**Comment by deathboydmi** [comment]
@shef2608 
You can find [gvaskeleton](https://github.com/PaBochka/gst-video-analytics/tree/master/gst/inference_elements/gvaskeleton) and [gvawatermark](https://github.com/PaBochka/gst-video-analytics/tree/master/gst/elements/gvawatermark) they are elemeтts provided by team from UNN university. You can see there sources, which contain [OMZ postprocessing](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/human_pose_estimation_demo).

**Comment by shef2608** [comment]
> @shef2608
> You can find [gvaskeleton](https://github.com/PaBochka/gst-video-analytics/tree/master/gst/inference_elements/gvaskeleton) and [gvawatermark](https://github.com/PaBochka/gst-video-analytics/tree/master/gst/elements/gvawatermark) they are elemeтts provided by team from UNN university. You can see there sources, which contain [OMZ postprocessing](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/human_pose_estimation_demo).

Hi @deathboydmi,
Thanks for the reply.

I have also used gvaskeleton in our pipeline. But it shows me that "no such element found for gvaskeleton"
* I am using the OpenCv/gst-video-analytics.
(https://github.com/opencv/gst-video-analytics)

 Below is my pipeline:
videoconvert ! video/x-raw ! \
gvaskeleton model={} device=CPU ! queue ! \

* So, I have also used the "human-pose-estimation.json" in model-proc with gvainference or with gvaskeleton. But it is not working. 
Below is my pipeline:
videoconvert ! video/x-raw ! \
gvainference model={} model-proc={} device=CPU ! queue ! \

Please suggest a way how I can achieve this. or any way so that I can add an element "gvaskeleton"  in the code (https://github.com/opencv/gst-video-analytics)
![01](https://user-images.githubusercontent.com/37114196/92253177-d0250100-eeec-11ea-8771-51bcb6ed34ed.PNG)


Thanks

**Comment by dsmertin** [comment]
@shef2608  You can look usage `gvainference + gvapython` pipeline sample in our repository: https://github.com/opencv/gst-video-analytics/tree/master/samples/gst_launch/gvapython/face_detection_and_classification

**Comment by wdkwyf** [comment]
Hi,
I commit a PR about human-pose-estimation-001 for your reference. Post-processing codes are simpliy copied from open model zoo repository.
https://github.com/openvinotoolkit/dlstreamer_gst/pull/116

**Comment by shef2608** [comment]
> Hi,
> I commit a PR about human-pose-estimation-001 for your reference. Post-processing codes are simpliy copied from open model zoo repository.
> #116

@wdkwyf , 
Thanks for the reply.
I had found a good reference as you had provided. I am successfully able to give the path to our gvadetect and gvainference.
But when i run the ./human_pose_estimation.sh, 
it immediately gave me the **below pipeline** string but it did not show me any window and **then script stopped**.

filesrc location=https://github.com/intel-iot-devkit/safety-gear-detector-python/raw/master/resources/Safety_Full_Hat_and_Vest.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=dl_streamer/models/intel/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.**xml** ! queue ! gvainference name=gvainference model=dl_streamer/models/intel/human-pose-estimation-0001/FP32/human-pose-estimation-0001.**xml** ! queue ! gvawatermark name=gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false

**It is very important for me to run human-pose model** 

Thanks,

**Comment by mliu2020** [comment]
Hi @shef2608:

I run the string in Ubuntu and I can ge the rendering with the person being recognized by a bound box, is this your issue?

I didn't use script but run on the command line, the only difference is, I have downloaded the file to local:
gst-launch 1.0 filesrc location=~/Downloads/Safety_Full_Hat_and_Vest.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=dl_streamer/models/intel/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.xml ! queue ! gvainference name=gvainference model=dl_streamer/models/intel/human-pose-estimation-0001/FP32/human-pose-estimation-0001.xml ! queue ! gvawatermark name=gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false

I saw your original question was about JSON file, do you want to add JSON file to this pipeline?

Mark

**Comment by shef2608** [comment]
> Hi @shef2608:
> 
> I run the string in Ubuntu and I can ge the rendering with the person being recognized by a bound box, is this your issue?
> 
> I didn't use script but run on the command line, the only difference is, I have downloaded the file to local:
> gst-launch 1.0 filesrc location=~/Downloads/Safety_Full_Hat_and_Vest.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=dl_streamer/models/intel/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.xml ! queue ! gvainference name=gvainference model=dl_streamer/models/intel/human-pose-estimation-0001/FP32/human-pose-estimation-0001.xml ! queue ! gvawatermark name=gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
> 
> I saw your original question was about JSON file, do you want to add JSON file to this pipeline?
> 
> Mark

Hi @mliu2020,
Yes, my question was,
- What will be the approach to make human-pose-estimation-0001 inference work?
- Because this model is not working as expected with gvadetect. They are throwing  the following error if I do not use the JSON file for human-pose-estimation-001 model.
Failed to extract detection results  
Failed to do SSD post-processing  
- Do we need to use gvainference & gvapython for these models? If yes, how can we go about creating the python implementation for these models? Do we have any existing python implementation for these models which we can refer.

- But now I found the JSON file as @wdkwyf mentioned in the above. So,in that document, I found the gstreamer pipeline which is my need and I am successfully able to use that shell file but when i run the **./human_pose_estimation.sh** as mentioned in that document,
it immediately gave me the below **pipeline** string but it did not show me any window and **then script stopped.**

filesrc location=https://github.com/intel-iot-devkit/safety-gear-detector-python/raw/master/resources/Safety_Full_Hat_and_Vest.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=dl_streamer/models/intel/person-vehicle-bike-detection-crossroad-0078/FP32/person-vehicle-bike-detection-crossroad-0078.**xml** ! queue ! gvainference name=gvainference model=dl_streamer/models/intel/human-pose-estimation-0001/FP32/human-pose-estimation-0001.**xml** ! queue ! gvawatermark name=gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false

Thanks

**Comment by wdkwyf** [comment]
Thanks @mliu2020  and @shef2608 for your information. I modify the [pull request](https://github.com/openvinotoolkit/dlstreamer_gst/pull/116) and fix the input issue. Now, run human_pose_estimation.sh can accept the uri and show the window.
![20200904_175738](https://user-images.githubusercontent.com/7670749/93735961-4b86f200-fc11-11ea-9782-f2d10fba278d.jpg)

**Comment by shef2608** [comment]
> Thanks @mliu2020 and @shef2608 for your information. I modify the [pull request](https://github.com/openvinotoolkit/dlstreamer_gst/pull/116) and fix the input issue. Now, run human_pose_estimation.sh can accept the uri and show the window.
> ![20200904_175738](https://user-images.githubusercontent.com/7670749/93735961-4b86f200-fc11-11ea-9782-f2d10fba278d.jpg)

Thanks @wdkwyf, it was really helpful for me, now i am successfully able to use human-pose-estimation-0001 model. But it is taking long time for inferencing a 1 minute of video. Below is the Frames per second per stream.

FpsCounter(1sec): total=0.20 fps, number-streams=1, per-stream=0.20 fps
FpsCounter(1sec): total=0.20 fps, number-streams=1, per-stream=0.20 fps
FpsCounter(1sec): total=0.20 fps, number-streams=1, per-stream=0.20 fps

**Comment by wdkwyf** [comment]
@shef2608 You can try setting the config about inference times per second, which means skip frame, it will help to get the real-time performance.

**Comment by shef2608** [comment]
> @shef2608 You can try setting the config about inference times per second, which means skip frame, it will help to get the real-time performance.

yes i tried this with interval-infereference where I skip the frames, when i pass inference-interval=1 then it is giving me 0.20fps but when i pass inference-interval=2, then it is giving me the Index Error

**Used Inference interval in gvainference:**
gvadetect model={} device=CPU ! queue ! \
gvainference name=gvainference model={} device=CPU inference-interval=2 ! queue ! \
gvafpscounter ! gvawatermark name=gvawatermark ! videoconvert

**IndexError:**
IndexError: list index out of range
FpsCounter(1sec): total=0.40 fps, number-streams=1, per-stream=0.40 fps

**I also used it with the gvadetect, but it is giving me around 0.25 fps with IndexError**
Below is the pipeline:
gvadetect model={} device=CPU inference-interval=2 ! queue ! \
gvainference name=gvainference model={} device=CPU inference-interval=2 ! queue ! \
gvafpscounter ! gvawatermark name=gvawatermark ! videoconvert

**Comment by mliu2020** [comment]
Hi @shef2608,

You may try to put gvatrack immediately after gvadetect. The error may be because gvatrack requires bounding box  as input but gvainference doesn't have bounding box output.

Mark

**Comment by mliu2020** [comment]
@shef2608,

Did you solve the problem with the inference-interval?

From the original topic, I believe this should be closed and the performance with inference-interval should be posted as a different issue.

Let me know your opinion and I will wait for several days to close this one.

Mark

**Comment by mliu2020** [comment]
@shef2608,

Let me close this issue for now.

Feel free to re-open it or post a new question.

Mark Liu
