### ISSUE TITLE
Failed to do SSD post-processing with some Open Model Zoo intel models

### ISSUE THREAD

**Issue by abramov-oleg** [openvinotoolkit/dlstreamer_gst#109]
I'm trying to run minimal inference pipeline and on some models from intel part of Open Model Zoo I get an error:

```
0:00:02.328787412    18 0x7fa378002200 ERROR             GVA_common openvino_image_inference.cpp:364:operator(): Failed in inference request completion callback:

Failed to extract detection results
 Failed to do SSD post-processing
  Output blob dimentions size 1 is not supported (less than 2)
Failed to extract detection results
 Failed to do SSD post-processing
  Output blob dimentions size 1 is not supported (less than 2)
```

Steps to reproduce:

1. Download `face-detection-0105` model from open_model_zoo

        cd open_model_zoo/tools/downloader
        ./downloader.py --name face-detection-0105

1. Start `openvino/ubuntu18_runtime:2020.4` container

        docker run -it --rm -v <model_directory>:/models -v <data_directory>:/data openvino/ubuntu18_runtime:2020.4 /bin/bash

1. Run pipeline with debug info

        GST_DEBUG=GVA_common:4 gst-launch-1.0 \
        uridecodebin uri=flie:///data/testvideo.mp4 \
        ! videoconvert ! video/x-raw,format=BGRx \
        ! gvadetect model=/models/face-detection-0105/FP32/face-detection-0105.xml \
        ! fakesink sync=false

Same thing happens with `face-detection-0106`, for example. At the same time `face-detection-0104` works fine.

**Comment by adranit** [comment]
Hi @abramov-oleg,
I'm not an expert in these models, but I think [105 ](https://docs.openvinotoolkit.org/cn/latest/_models_intel_face_detection_0105_description_face_detection_0105.html) and [106 ](https://docs.openvinotoolkit.org/2020.2/_models_intel_face_detection_0106_description_face_detection_0106.html) are not SSD models unlike [104](https://docs.openvinotoolkit.org/cn/latest/_models_intel_face_detection_0104_description_face_detection_0104.html). Could you double check the models type?

Thanks,
Anton

**Comment by abramov-oleg** [comment]
Yes, indeed, the models page mentions that 105 has `FCOS` head and 106 `ATSS` head, which could explain how SSD output parser fails to get bounding boxes out of model tensor output.

My question I guess is the following: what is the intended way to use these pretrained models? Is it `gvainference` element with custom post-processing, is it some sort of configuration passed to `gvadetect` `post-proc` property, or something else?

**Comment by adranit** [comment]
@abramov-oleg ,
If some models require the post-processing that is not implemented in DL Streamer then several options are possible:
1. using of gvainference + gvapython.
2. using of gvainference + custom application.
3. adding a new post-processor in source code of gvadetect/gvaclassify.

All these options are described [here](https://github.com/opencv/gst-video-analytics/wiki/Custom-Processing).

Thanks,
Anton

**Comment by intel-neena** [comment]
@abramov-oleg Do you still need any help on this?
