### ISSUE TITLE
gallery_generator.py error: Could not determine type of stream

### ISSUE THREAD

**Issue by divdaisymuffin** [openvinotoolkit/dlstreamer_gst#111]
Hi,

I am working on face recognition pipeline, For doing so, I am using face-detection-adas, landmark-regression and face-reidentification-retail model.
I am using gallery_generator.py, to convert images to tensors, the pipeline is runs but stops with error , and feature directory build but contain only 1 tensor.

error: streaming stopped, reason error (-5)                                                                                           ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstTypeFindElement:typefind: Could not determine type of stream.  Additional debug info:                                                                                                               ../plugins/elements/gsttypefindelement.c(1160): gst_type_find_element_loop (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstTypeFindElement:typefind                                                                                                                 ERROR: pipeline doesn't want to preroll.                                                                                             Setting pipeline to NULL ...                                                                                                         Freeing pipeline ...                                                                                                                 Error while running pipeline

I am using GST DEBUG  level = 3 to get detailed error info.
 and command
python3 gst-video-analytics-1.0.0/samples/gst_launch/reidentification/gallery_generator.py -s gallery/ -o g allery/ -d intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml -i intel/dl_streamer/models/int el/face-reidentification-retail-0095/FP32/face-reidentification-retail-0095.xml -l intel/dl_streamer/models/intel/landmarks-regressi on-retail-0009/FP32/landmarks-regression-retail-0009.xml  --identification_modelproc gst-video-analytics-1.0.0/samples/model_proc/fa ce-reidentification-retail-0095.json --landmarks_regression_modelproc gst-video-analytics-1.0.0/samples/model_proc/landmarks-regress ion-retail-0009.json
![prob1](https://user-images.githubusercontent.com/68895288/91971373-b8a41780-ed36-11ea-947d-a8648641752c.JPG)
![prob2](https://user-images.githubusercontent.com/68895288/91971406-c22d7f80-ed36-11ea-8b85-69a4b3bb19ff.JPG)
![prob3](https://user-images.githubusercontent.com/68895288/91971419-c78aca00-ed36-11ea-9268-8e1cfe9a12b5.JPG)

Please help me in this.

**Comment by adranit** [comment]
Hi @divdaisymuffin,
Could you double check if each folder in "gallery\" contains only images? It looks like there is a file exists that can't be handled by decodebin element.

Thanks,
Anton

**Comment by nnshah1** [comment]
@adranit, @divdaisymuffin 

I've started working on a version of the sample that can run in the latest DL Streamer  / VA Serving releases - it will take a day or two to package but will provide more details generally. Thanks for your patience.

**Comment by easychizy** [comment]
Hi @divdaisymuffin,

I believe the issue here was addressed by the following ticket in the video-analytics-serving project:
https://github.com/intel/video-analytics-serving/issues/19

Could you confirm? If this issue can cover your request, we can continue discussion there.

Mark

**Comment by divdaisymuffin** [comment]
Hi @mliu2020 ,
Sorry for delayed response, I was not aware of this message.
Yeah my issue is been resolved at intel/video-analytics-serving#19
You can close this conversation.

Thanks

**Comment by mliu2020** [comment]
Thanks so much for support our product.

Please feel free to re-open if you see the issue re-appear.

Mark
