### ISSUE TITLE
why gavidentify is not present in gva 2020.4 version (latest) while it was there in gva 2020.2, is there other alternate  gva element to gvaidentify available ?

### ISSUE THREAD

**Issue by divdaisymuffin** [openvinotoolkit/dlstreamer_gst#112]
I am working on face reidentification problem and wanted to know why gvaidentify is removed from the latest version of gva? is its depreceated? or is been replaced by some other gva element?

See these links
[https://github.com/opencv/gst-video-analytics/releases](url)
[https://github.com/opencv/gst-video-analytics/releases](url)

**Comment by adranit** [comment]
Hi @divdaisymuffin,
gvaidentify was a sample and it was deprecated and removed from 2020.4 release. There are currently no alternative elements for identification.
We are sorry for the inconvenience.

Anton

**Comment by divdaisymuffin** [comment]
Thanks @adranit for quick response. so, could you suggest me some other way of doing face reidentification via gva? because According to my understanding gvaidentify is neccessary to be defined in pipeline.json for that purpose.

**Comment by nnshah1** [comment]
@divdaisymuffin We are working to provide an alternate sample and will keep you updated.

**Comment by nnshah1** [comment]
Alternate sample using gvapython alone provided here: 

https://github.com/intel/video-analytics-serving/issues/19

**Comment by intel-neena** [comment]
@divdaisymuffin Do you still need any help on this?

**Comment by mliu2020** [comment]
Hi @divdaisymuffin,

If you have no more question on this issue, I will close this in 7 days.

Mark

**Comment by divdaisymuffin** [comment]
Hi @mliu2020 Thank you for the help, my issues are resolved, you can close this.

**Comment by mliu2020** [comment]
@divdaisymuffin,

Thanks for the quick response, let me close this.

Mark
