### ISSUE TITLE
Contents of listen_mqtt.sh

### ISSUE THREAD

**Issue by MauryaShraddha** [openvinotoolkit/dlstreamer_gst#114]
Hello,

There is a `listener.md` file in the metapublish folder, which says: For MQTT, install and launch MQTT broker along with an MQTT client listener subscribed to the topic (that emits to console). Below there is also mention of `listen_mqtt.sh`. I would like to know the contents and purpose of `listen_mqtt.sh`. 

According to the website: https://docs.openvinotoolkit.org/latest/gst_samples_gst_launch_metapublish_listener.html , if I execute `mosquitto_sub -h localhost -t dlstreamer` , I get the details of the bounding boxes. 

How can I write another MQTT client (subscriber) code to receive the messages (the bounding boxes details) from the MQTT broker?

@nnshah1 @intel-neena  @adranit Can you please help?

Thank you
Shraddha

**Comment by cgdougla** [comment]
Hi @MauryaShraddha,

On the page that you linked, the code block under MQTT is the content of listen_mqtt.sh. The mosquitto_sub utility makes it easy to check that your messages are being received by MQTT. If you want to write your own code for a subscriber in an application you can look at sample subscribers for the language and library you need. For example, here is the Paho MQTT example in C for a client subscriber: https://www.eclipse.org/paho/files/mqttdoc/MQTTClient/html/subasync.html.

Does that help?
Thanks,
Cody

**Comment by MauryaShraddha** [comment]
Hello,

Thank you for the reference. I wrote a client and it worked. I am getting the bounding box label information but not able to get the video. Following is the screenshot: 

![image](https://user-images.githubusercontent.com/36510998/92834688-4ec7e580-f3a8-11ea-84e1-ff8a7a02fdb5.png)

How can I get the video?

**Comment by MauryaShraddha** [comment]
Hi @cgdougla ,

Is it possible to send/publish the annotated video through MQTT?

**Comment by cgdougla** [comment]
Using gvametapublish will only provide you with the inference metadata like the bounding boxes and classification information you are seeing.  

If you want to get the video you will need to use another gstreamer element (specifically it will be a sink element) and it depends on your use case. If you are starting your gstreamer pipeline from an application you can use `appsink` and get access to the buffer data. You can see the GStreamer tutorial here for an example https://gstreamer.freedesktop.org/documentation/tutorials/basic/short-cutting-the-pipeline.html?gi-language=c.  

If you are wanting to stream the video after doing inferencing and watermark you can use something like `updsink`. You will need to encode the video and pack it into rtp packets. An example pipeline for streaming is here https://gstreamer.freedesktop.org/documentation/tools/gst-launch.html?gi-language=c#network-streaming. 

I do not know of an element to publish video data to MQTT.

**Comment by MauryaShraddha** [comment]
@cgdougla that helps. 

Thank you
Shraddha
