### ISSUE TITLE
Are post-processing convertors for yolov3_tiny available in gvadetect ?

### ISSUE THREAD

**Issue by Sharan-Sundar** [openvinotoolkit/dlstreamer_gst#121]
Are post-processing convertors for `yolov3_tiny` available in `gvadetect`? I am not getting any `roi` in `frame.regions()` in the callback(`draw_face_attributes.py`). How can I verify if it is something to do with the weights itself or with `gvadetect` post-processing ?

**Comment by adranit** [comment]
Hi @Sharan-Sundar ,
Do you use the model_proc file for yolov3_tiny model? https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/model_proc/yolo-v3-tiny.json

The following pipeline can be used to save roi into report.json file:
filesrc location=... ! decodebin ! videoconvert ! video/x-raw ! gvadetect model=yolo-v3-tiny.xml model-proc=./samples/model_proc/yolo-v3-tiny.json ! queue ! **gvametaconvert** format=json add-tensor-data=true ! **gvametapublish** file-path=report.json method=file file-format=json-lines ! fakesink sync=false

**Comment by Sharan-Sundar** [comment]
Hey @adranit , I tried what you said and **report.json** is empty. However, I am able to run inference using the same model on python(`object_detection_demo_yolov3_async.py`). It is returning no detections only when using `gvadetect`. What might be the issue?

**Comment by adranit** [comment]
Hi @Sharan-Sundar ,
What is the model used? As far as I know OMZ does not contain yolov3_tiny model. 
I think there is a possible mismatch between the model and the model_proc file. The "layer_name" field must point to the first output layer of the model.

**Comment by mliu2020** [comment]
Hi @Sharan-Sundar,

Did you check the file yet?

Yolo models are sensitive to errors in model_proc files. Model_proc file must match the used model. To check the file will clarify the concern.

Let me know if you need help.

Mark

**Comment by Sharan-Sundar** [comment]
Hey @mliu2020 . Yes I did check the model_proc file and there doesn't seem to be any problems. The "layer_name" does match. Since I could not fix this issue, I switched from `yolo` to `ssd`. You may close this if you want.

**Comment by mliu2020** [comment]
Good to know you have a solution and thanks for the comment,

I closed this issue now and feel free to re-open it if you have more question.

Mark
