### ISSUE TITLE
Inference(Detection) in Callback/Gvapython

### ISSUE THREAD

**Issue by Sharan-Sundar** [openvinotoolkit/dlstreamer_gst#126]
I need back-to-back detectors and I am aware that it is a feature that is under development and will be available in the next release. So, I am trying to perform inference(detection) either in the callback or using `Gvapython`.

Since it is a part of the `gstreamer` pipeline, I know that the inference(detection) has to be parallely processed and will stall and delay the pipeline if sequential - Fps dropped to 1 when performing inference in callback.

I am trying out multiprocessing and queue in the `ssd_object_detection.py(gvapython)` but it seems to stop at this and hangs

```
gst-launch-1.0 filesrc location=/home/user/gva/gst-video-analytics/samples/python/OpenVINO/SB2.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvainference model=/home/user/gva/gst-video-analytics/samples/python/OpenVINO/ir_weights/ssd.xml device=CPU inference-interval=4 ! gvapython module=/home/user/gva/gst-video-analytics/samples/gst_launch/gvapython/OpenVINO/postproc_callbacks/ssd_object_detection.py ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'vaapipostproc0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
```
Is performing inference(detection) in callback/gvapython a feasible way ? What are the possible solutions ?

**Comment by nnshah1** [comment]
when you say "back to back" detectors, can you explain more what your use case is? Is it that you need to do secondary detection within a region of interest that has been detected by an initial detector? For that scenario it may be feasible to use an application to crop the regions and then use a second pipeline to run a full frame detection over the cropped regions.

**Comment by Sharan-Sundar** [comment]
Yes the secondary detection has to happen within a region of interest. The use case is the same as [Multilevel or back to back detectors
](https://github.com/openvinotoolkit/dlstreamer_gst/issues/57#issue-598548044) #57  .

And I did ask the same gvadetect->crop->gvadetect question in that issue also for which the answer wasn't positive. I am not familiar enough with gstreamer to modify/create a new plugin which is why I am trying to stick to Python. "_For that scenario it may be feasible to use an application to crop the regions and then use a second pipeline to run a full frame detection over the cropped regions._" - is that possible? Can you pass images in memory asynchronously to a new gstreamer pipeline?

**Comment by nnshah1** [comment]
It is possible, using `appsink` and `appsrc` elements within a python gstreamer application you can take frames from one pipeline, manipulate them, and then push them into a second pipeline.

**Comment by mliu2020** [comment]
Hi @Sharan-Sundar,

Do you still need help on this solution?

Mark

**Comment by Sharan-Sundar** [comment]
Hey @mliu2020 . I have not tried out the `appsink appsrc` elements yet as I am not as familiar with gstreamer. But I guess we can close the issue for now. The solution will be perfect only when you guys have a release with back-to-back `gvadetect` elements - #57 .

**Comment by mliu2020** [comment]
Thanks so much,

Let me close it now and feel free to re-open if you have more thoughts.

Mark
