### ISSUE TITLE
gva mask for certain area

### ISSUE THREAD

**Issue by b04505009** [openvinotoolkit/dlstreamer_gst#127]
Do you provide some functions for elements like gvadetect to only look at certain area? Or some hints for how to implement it?
This can reduce computation so I think is an important function for edge devices. Thanks a lot

**Comment by adranit** [comment]
Hi @b04505009 ,
Sorry for late response.
Currently DL Streamer doesn't provide the ability to set ROI for detection. 
We have [gvametaaggregate ](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/gvametaaggregate )element that can join meta data from different sources.  This element can be used when inference is performed on scaled image, and inference results are attached to original image. This element scales ROIs to the image size, but **it can't handle crop** operation. 

Schematic pipeline with gvametaaggreagate element:
filesrc ! decodebin ! videoconvert ! video/x-raw,format=I420 ! tee name=**t** **t.** ! queue ! gvametaaggregate name=**a** ! gvawatermark ! videoconvert ! fpsdisplaysink **t.** ! queue ! videoscale(300x300) ! gvadetect model=model.xml ! **a.**

**Comment by b04505009** [comment]
Hi @adranit ,
I think adding an argument to gvametaaggregate for user to decide whether to scale on video size mismatch is an easy way to implement this.

**Comment by intel-neena** [comment]
gvadetect now has a property 'inference-region' = 'roi-list' for providing region of interest to run detection. You can use gvapython to attach the roi-list. Please try and re-open the issue if any further help is needed.

**Comment by b04505009** [comment]
Hi, I would like to ask that if I have 2 stages detection, like
gvadetect1 -> gvatrack -> gvadetect2
then how can I know a bbox in gvadetect2 is detected from which bbox in gvadetect1?

**Comment by mliu2020** [comment]
Hi @b04505009,

Since this issue is closed, could you open a new issue?

Thanks

Mark
