### ISSUE TITLE
what is the tracker algorithm used in openvino 2021.1 gvatrack?

### ISSUE THREAD

**Issue by tankienleong** [openvinotoolkit/dlstreamer_gst#133]
what are the algorithms for zero-term and short-term tracker?

**Comment by adranit** [comment]
Hi @tankienleong,
In 2021.1, gvatrack uses ZERO_TERM_COLOR_HISTOGRAM and SHORT_TERM_KCFVAR algos.
Please note that openvino 2021.1 contains the known issue with gvatrack (#132)

**Comment by tankienleong** [comment]
Hi @adranit ,
Thank you.
