### ISSUE TITLE
Failed to construct OpenVINOImageInference ... can't protect

### ISSUE THREAD

**Issue by leo851001** [openvinotoolkit/dlstreamer_gst#135]
My server :
OS : Ubuntu 18.04 LTS
CPU : Intel® Xeon(R) Gold 6248R CPU @ 3.00GHz × 96
RAM : 376GB

I'm using openvino_2020.4.287 to detect the person in the .mp4 file .
model : ssd_mobilenet_v1_coco_2018_01_28 .
First , I use the **model_optimizer** convert the tensorflow model ( .pb ) to OpenVINO IR model ( .xml + .bin ) .
My OpenVINO IR model -> version = 10 , type = FP32 , batch = 16 .
Then I use the DL workbench to convert my model from FP32 -> INT8 .

I have run the pipeline : 
`gst-launch-1.0 -v  filesrc location=/root/videos/output.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/models/16_int8/frozen_inference_graph_16_INT8.xml device=CPU ! queue ! gvafpscounter ! fakesink`
It's successful : `FPSCounter(average): total=534.66 fps, number-streams=1, per-stream=534.66 fps`

Then I started running multiple pipeline same times ( MultiStream ) .
I add five at a time 5 , 10 , 15 .
It's work normal .

But when I add the pipeline to 20 , there was a problem :
`Failed to construct OpenVINOImageInference ... can't protect`
<img width="541" alt="20" src="https://user-images.githubusercontent.com/30343874/96093742-18c5d600-0eff-11eb-8ec2-a22f4c9e3bc9.png">

Then I try to run 19 pipeline , it's work normal : 
<img width="542" alt="19" src="https://user-images.githubusercontent.com/30343874/96093997-65a9ac80-0eff-11eb-8b48-7f393f012f10.png">

The error seems to mean that my CPU cannot be loaded .
But when I'm running 19 pipeline , my cpu usage only 30% .
So , what problem did i get ?

Please excuse my poor English.

Thanks all,
Leo

**Comment by adranit** [comment]
Hi Leo,
I recommend to set "model-instance-id" parameter of gvadetect element. (_Identifier for sharing a loaded model instance between elements of the same type. Elements with the same model-instance-id will share all model and inference engine related properties_). It allows to run multichannel pipelines with reusing the loaded model.
You can use [benchmark](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/benchmark/benchmark.sh) sample as a reference.

Thanks,
Anton

**Comment by mliu2020** [comment]
Hi @leo851001,

Does our suggestion solved your problem yet?

Mark

**Comment by mliu2020** [comment]
Hi @leo851001,

@adranit suggested to use the model-instance-id so the model can be shared among elements. This should result the better performance and higher stream density. Did you try it?

If you are not interested in this issue, I will close it in a couple days.

Mark

**Comment by adranit** [comment]
Performance recommendations for DL Streamer pipelines on Xeon(CLX):
1)	run each video stream in a separate process with as much as possible limited number of threads within one process (ideally 1-3)
2)	explicitly turn off thread pinning in inference engine (CPU_BIND_THREADS=NO) to let operating system to do proper scheduling
3)	to get slightly better and more stable/reproducible performance, in simple benchmarks on two socket Xeon system, bind even/odd processes out of arbitrary number of streams to different NUMA nodes using “numactl” utility
4)	set “cpu-throughput-streams” equal to CPU_THREADS_NUM value
5)	set “nireq" equal to 1.5x-2x of CPU_THREADS_NUM value
6)	depending on NN models complexity, change the balance of threads within one process btw media and inference. 
for lightweight models, set one thread for media operations and one thread for inference (CPU_THROUGHPUT_STREAMS=1; CPU_THREADS_NUM=1; nireq=2). 

filesrc ! qtdemux ! avdec_h264 max-threads=1 ! videoconvert n-threads=1 ! video/x-raw,format=I420 !
gvadetect model=mobilenet-ssd.xml cpu-throughput-streams=1 nireq=2 ie-config=CPU_THREADS_NUM=1,CPU_BIND_THREAD=NO !
gvafpscounter ! fakesink async=false

for heavy models, use one thread for decode and multiple (ex.: 3) threads for inference.

filesrc ! qtdemux ! avdec_h264 max-threads=1 ! videoconvert n-threads=1 ! video/x-raw,format=I420 !
gvadetect  model=face-detection-adas-0001.xml cpu-throughput-streams=3 nireq=5 ie-config=CPU_THREADS_NUM=3,CPU_BIND_THREAD=NO ! 
gvaclassify model=face-reidentification-retail-0095.xml model-proc=face-reidentification-retail-0095.json cpu-throughput-streams=1 nireq=2 ie-config=CPU_THREADS_NUM=1,CPU_BIND_THREAD=NO !
gvafpscounter ! fakesink async=false

**Comment by mliu2020** [comment]
@leo851001,

Please tell us if you are satisfied with @adranit's answers, I will wait for a week to close this if you don't response.

Mark

**Comment by leo851001** [comment]
I’m very sorry. I ignored this part of the test because of an emergency a while ago. I will start the test again. Thank you very much for your answers.

**Comment by mliu2020** [comment]
@leo851001 ,

Do you have any result?

If no more question, could I close it?

Mark

**Comment by leo851001** [comment]
@mliu2020 Sure!! It's work well for me. Thanks!!

**Comment by mliu2020** [comment]
Thanks so much,

Let me close it now and feel free to re-open it or submit a new issue.

Mark
