### ISSUE TITLE
2021.1 classification result (multiclasses) of gvatrack (short-term) is wrong when use gvainference

### ISSUE THREAD

**Issue by tankienleong** [openvinotoolkit/dlstreamer_gst#137]
when I use gvadetect with gvatrack, the classification result draw by gvawatermark is correct.

when I use gvainference & gvapython with gvatrack, the classification result draw by gvawatermark is wrong. Without the gvatrack, the classification result of gvainference & gvapython draw by gvawatermark is correct. The gvapython will get the bounding box coordinates and classification result from the output layer, perform NMS, and use frame.add_region().

**Comment by coller95** [comment]
Change the file gst/elements/gvatrack/vas/tracker.cpp
start from line 83
```
        int label_id = roi.detection().get_int("label_id", std::numeric_limits<int>::max());
        if (labels.find(label_id) == labels.end())
            labels[label_id] = roi.label();

```
to
```
        int label_id = g_quark_from_string (roi.label().c_str());
        labels[label_id] = roi.label();
```

**Comment by tankienleong** [comment]
Hi @coller95 
your solution saved my day
Thank you !!!

**Comment by mliu2020** [comment]
Hi @tankienleong,

@coller95 Thanks for the good solution.

Let me know if you have more questions. Or can you close it?

Mark
