### ISSUE TITLE
gvatrack

### ISSUE THREAD

**Issue by vtimofeev01** [openvinotoolkit/dlstreamer_gst#138]
By running a pipeline with gvatrack can t start
the docker image is rebuild

```
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
ERROR: from element /GstPipeline:pipeline0/GstGvaTrack:gvatrack0: tracker intitialization failed
Additional debug info:
/root/gst-video-analytics/gst/elements/gvatrack/gstgvatrack.c(160): gst_gva_track_set_caps (): /GstPipeline:pipeline0/GstGvaTrack:gvatrack0:

dlopen() failed: libopencv_video.so.4.4: cannot open shared object file: No such file or directory

ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

```

Thank U

**Comment by tankienleong** [comment]
please check libopencv_video.so.4.4 exist or not

**Comment by vtimofeev01** [comment]
not exists in container as i see because there are no locate

**Comment by vtimofeev01** [comment]
not exists in container as i see because there are no locate
but the container is rebuild

**Comment by tankienleong** [comment]
sudo apt install locate
sudo updatedb
locate libopencv_video.so.4.4

**Comment by vtimofeev01** [comment]
the latest in the system is /opt/intel/openvino_2020.3.194/opencv/lib/libopencv_video.so.4.3.0
in container

**Comment by vtimofeev01** [comment]
the latest in the system is /opt/intel/openvino_2020.3.194/opencv/lib/libopencv_video.so.4.3.0
in container i can t find it

**Comment by nnshah1** [comment]
@vtimofeev01 What version of `openvino` are you using to build the container? The latest `DL Streamer` is updated to support `openvino 2021.1`. There are portions of the `gvatrack` algorithms which provided as binary only and are built against a specific version of `openvino` thus they need to match. Can you try updating your build to `2021.1` ?

**Comment by tankienleong** [comment]
@vtimofeev01 If you are using DL streamer release 2021.1.1, you need Openvino 2021.1

**Comment by vtimofeev01** [comment]
The container was rebuild but it doesn’t help

**Comment by nnshah1** [comment]
which container / dockerfile are you using?

Have you tried: https://hub.docker.com/r/openvino/ubuntu18_data_dev 

Please note the special instructions:

**Comment by vtimofeev01** [comment]
I made it via vaserving docker build
