### ISSUE TITLE
opencl dependencies not written on install guide

### ISSUE THREAD

**Issue by b04505009** [openvinotoolkit/dlstreamer_gst#139]
I followed your instructions to compile dl_streamer on host machine (ubuntu 20.04), but I encountered some dependency issues when I use `cmake .. -DENABLE_VAAPI=ON` option. I solve this problem by installing packages `sudo apt-get install ocl-icd-opencl-dev opencl-clhpp-headers`. I think this should add to your install guide.

**Comment by adranit** [comment]
Hi @b04505009 ,
Sorry for late response.
Thank you for report the issue, we'll update the installation guide.
