### ISSUE TITLE
2021.1 gvawatermark not compatible with vaapih264enc

### ISSUE THREAD

**Issue by tankienleong** [openvinotoolkit/dlstreamer_gst#140]
Hi, the rtsp stream output by pipeline below is distorted (please refer to the attached image)

rtspsrc location=rtsp://192.168.1.111/h264 ! rtph264depay ! vaapih264dec ! gvainference model=xxx.xml ! gvapython module=gvapython1.py ! queue ! gvatrack tracking-type=short-term ! gvawatermark ! vaapih264enc ! rtph264pay config-interval=1 name=pay0 pt=96"

![Capture](https://user-images.githubusercontent.com/25731934/96363374-7f006200-1166-11eb-8932-04557908c4b3.JPG)

If I removed the gvawatermark plugin from the pipeline, the rtsp stream is ok.

![Capture](https://user-images.githubusercontent.com/25731934/96363405-c555c100-1166-11eb-9cff-319122ee62ef.JPG)

Openvino 2020.3 doesn't have this problem.

**Comment by tankienleong** [comment]
Problem solved after I changed the pc from intel celeron N3350 to intel i7-7700T. But the intel celeron N3350 pc is installed with ubuntu 18.04.5 kernel 5.4.0-51-generic while the intel i7-7700T pc is installed with ubuntu 18.04.4 kernel 4.15.0-121-generic. So I not sure this is a hardware issue or the ubuntu kernel issue.

**Comment by mliu2020** [comment]
@tankienleong, 

Good to know.

As far as my understand, N3350 and i7-7700T should have the same video function in the GPU core, so it should not be a hardware problem.

Mark

**Comment by tankienleong** [comment]
@mliu2020 I formated and installed ubuntu 18.04.4 kernel 4.15.0-121-generic in intel celeron N3350 but the rtsp stream still distorted.

**Comment by brmarkus** [comment]
Have you tried to generate a gstreamer DOT graph of the pipeline (via the ENV variable "GST_DEBUG_DUMP_DOT_DIR")? Can you check the video parameters, like width, height, cropping and color format (like RGBA, BGRA, NV12, YUVY), please?
Depending on your system installation (and used versions) you might get different behavior with different (default-)parameters used by the plugins and the media-driver (i965 or iHD).

**Comment by mliu2020** [comment]
Hi @tankienleong,

Sorry for the late response, does this issue still exist?

I don't have the device so I can't reproduce it, but if I were you, I will check the video driver first. You can remove the DL Streamer element and only check decoder, for example:
`gst-launch-1.0 rtspsrc location=rtsp://192.168.1.111/h264 ! rtph264depay ! vaapih264dec ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false`

You can also remove the RTSP link and replace with a local file.

Mark

**Comment by tankienleong** [comment]
I formated and installed ubuntu 18.04.4 kernel 5.4.0-54-generic in intel celeron N3350 and the problem solved.
