### ISSUE TITLE
request some sample code of gvapython

### ISSUE THREAD

**Issue by tankienleong** [openvinotoolkit/dlstreamer_gst#141]
Is there any tutorial on how to use the arg, class, function, and kwarg of gvapython in gstreamer pipeline? I would like to pass some input arguments into gvapython for postprocessing.

**Comment by nnshah1** [comment]
@tankienleong  

We have some additional samples / information on how to use arg, class, function and kwarg in our related project va serving:

https://github.com/intel/video-analytics-serving/issues/24 

https://github.com/intel/video-analytics-serving/issues/19#issuecomment-688582265 

`class` and `function` let you select the specific class or function to use within the specified module. If a `class` is specified that class is initialized and the `process_frame` mehtod is called within it.

`arg` is a property that can be supplied multiple times to provide positional arguments to either the `class` initialization method or as additional parameters to the `function`. Its value must be valid JSON (this can be tricky to quote from command line, but if you have specific issues let us know what you are trying to pass and we can potentially provide an example). The format is a JSON `array`.

`kwarg` is a property that can be supplied multiple times to provide keyword arguments. Its value must be valid JSON (same tricks for quoting on command line are required). The format is a JSON `object`.

**Comment by tankienleong** [comment]
Hi @nnshah1 

Thanks for your explanation. I able to pass some input arguments into gvapython for postprocessing now.
