### ISSUE TITLE
gvapython as queue

### ISSUE THREAD

**Issue by vtimofeev01** [openvinotoolkit/dlstreamer_gst#142]
I need to have in my python code f.ex. 20 frames in work. And the changes comes in first comming frame. I want to use standard output methods like kafka etc but i don t know how to add meta to frames that are already out and how to make the system wait of it

**Comment by nnshah1** [comment]
@vtimofeev01 You need to process 20 frames before emitting a result? 

In this case it will probably be simplest to publish directly from gvapython using standard kafka / mqtt library as opposed to using metapublish

**Comment by mliu2020** [comment]
Hi @vtimofeev01 ,

Did you solve the problem with @nnshah1's suggestion?

Mark
