### ISSUE TITLE
reading Timestamp

### ISSUE THREAD

**Issue by vtimofeev01** [openvinotoolkit/dlstreamer_gst#143]
Please tell
how to get a timestamp for a VideoFrame
Thank U

**Comment by adranit** [comment]
Hi @vtimofeev01 ,
Sorry for late response. Timestamp can bee obtained from GstBuffer->pts.
VideoFrame does not have public methods to get the GstBuffer pointer, but you can get it with VideoFrame::video_meta()->buffer.

Thanks,
Anton

**Comment by vtimofeev01** [comment]
If i read a file the pts contains as I right understand and by rtsp-stream what the value i have there
Thank U

**Comment by mliu2020** [comment]
Hi @vtimofeev01,

Did you ask how to read pts from RTSP stream?

As my understanding, if you read meta data of VideoFrame, you should get pts no matter if it is a file or stream.

Mark

**Comment by vtimofeev01** [comment]
Thank U
if from file - starts from 0

**Comment by vtimofeev01** [comment]
If I see pots of videoframe what the value I see: pts from container or from camera stream

**Comment by mliu2020** [comment]
@vtimofeev01,

Sorry for the late response, still not sure if you are asking about the timestamp of file or camera stream,

If it is a file, VideoFrame pts represents the time relative to the viewer. see the following link:
https://gstreamer.freedesktop.org/documentation/gstreamer/gstbuffer.html?gi-language=python#GstBuffer

If it is a camera stream and you want to know absolute time of the frame taken by the camera, see this thread:
https://stackoverflow.com/questions/6149983/h-264-rtsp-absolute-timestamp

Mark

**Comment by mliu2020** [comment]
@vtimofeev01,

Are these answered your question?

Mark

**Comment by mliu2020** [comment]
@vtimofeev01,

Let me close this issue and feel free to reopen it if you still have questions.

Mark
