### ISSUE TITLE
gva gpu benchmark took too long time

### ISSUE THREAD

**Issue by wfchair** [openvinotoolkit/dlstreamer_gst#145]
I run gva on intel NUC,
HW:
  CPU: Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz 
  GPU: Iris Plus Graphics 650
SW: gva with openvino_2020.4.287

cd gst-video-analytics/samples/benchmark
./benchmark.sh video.mp4 GPU GPU
took too long time (1 minute or so) between video/x-raw(memory:VASurface) and gvadetect gstreamer element

can I reduce the time?

**Comment by adranit** [comment]
Hi @wfchair ,
Sorry for late response. 
I'm not sure I understood your question correctly. As far as I know initialization of GPU plugin for IE can take a lot of time. 
Does the issue appear after launch a pipeline only? Do you see the same issues with "./benchmark.sh video.mp4 GPU CPU" or "./benchmark.sh video.mp4 CPU GPU"?
Anton

**Comment by mliu2020** [comment]
Hi @wfchair,

I believe this is expected. Since you specified GPU as the inference engine, IE has to do the real-time compiling and loading of the OpenCL kernel. From my experience, 1 minutes is normal, this should be the fixed overhead.

Mark

**Comment by brmarkus** [comment]
At least you could set the OpenCL cache (via ENV variable) - then the OpenCL kernels are compiled only once and stored as binary blobs. The next time it will just load the pre-compiled kernels and start of application will be much faster (again).

**Comment by wfchair** [comment]
export cl_cache_dir=/home/user/intel/cl_cache

**Comment by wfchair** [comment]
export cl_cache_dir=/home/user/intel/cl_cache
worked like a charm. @brmarkus 

Thanks very much. You can close the issue.
