### ISSUE TITLE
Build error on raspberry pi 4 in copy_blob_to_gststruct.cpp 

### ISSUE THREAD

**Issue by deb-dsc20** [openvinotoolkit/dlstreamer_gst#146]
Hello team,

I am trying to run dlstreamer on raspberry pi 4 + movidius 2. 
Referring [link](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide#install-on-host-machine) for build on raspberry pi. 
Don't have opencl raspberry pi 4.
Also VAAPI or vainfo is not set.
Are these mandatory to build dl streamer on Raspberry pi 4?  
I would like gvadetect, gvaclassify and gvawatermark. On building I am getting following error

In file included from /home/pi/dlstreamer/dlstreamer_gst-master/gst/elements/gvametaconvert/audioconverter/audioconverter.cpp:8:
/home/pi/dlstreamer/dlstreamer_gst-master/gst-libs/gst/videoanalytics/audio/audio_frame.h:109:5: error: ‘GstAudioMeta’ does not name a type; did you mean ‘GstVideoMeta’?
     GstAudioMeta *audio_meta() {
     ^~~~~~~~~~~~
     GstVideoMeta
/home/pi/dlstreamer/dlstreamer_gst-master/gst-libs/gst/videoanalytics/audio/audio_frame.h: In constructor ‘GVA::AudioFrame::AudioFrame(GstBuffer*)’:
/home/pi/dlstreamer/dlstreamer_gst-master/gst-libs/gst/videoanalytics/audio/audio_frame.h:93:9: error: ‘GstAudioMeta’ was not declared in this scope
         GstAudioMeta *meta = audio_meta();
         ^~~~~~~~~~~~
/home/pi/dlstreamer/dlstreamer_gst-master/gst-libs/gst/videoanalytics/audio/audio_frame.h:93:9: note: suggested alternative: ‘GstVideoMeta’
         GstAudioMeta *meta = audio_meta();
         ^~~~~~~~~~~~
         GstVideoMeta
/home/pi/dlstreamer/dlstreamer_gst-master/gst-libs/gst/videoanalytics/audio/audio_frame.h:93:23: error: ‘meta’ was not declared in this scope
         GstAudioMeta *meta = audio_meta();
                       ^~~~
/home/pi/dlstreamer/dlstreamer_gst-master/gst-libs/gst/videoanalytics/audio/audio_frame.h:93:23: note: suggested alternative: ‘gets’
         GstAudioMeta *meta = audio_meta();
                       ^~~~
                       gets
/home/pi/dlstreamer/dlstreamer_gst-master/gst-libs/gst/videoanalytics/audio/audio_frame.h:93:30: error: ‘audio_meta’ was not declared in this scope
         GstAudioMeta *meta = audio_meta();
                              ^~~~~~~~~~
/home/pi/dlstreamer/dlstreamer_gst-master/gst-libs/gst/videoanalytics/audio/audio_frame.h:93:30: note: suggested alternative: ‘audio_info’
         GstAudioMeta *meta = audio_meta();
                              ^~~~~~~~~~
                              audio_info
make[2]: *** [gst/elements/CMakeFiles/elements.dir/build.make:258: gst/elements/CMakeFiles/elements.dir/gvametaconvert/audioconverter/audioconverter.cpp.o] Error 1

[log_fail.txt](https://github.com/openvinotoolkit/dlstreamer_gst/files/5451758/log_fail.txt)
Please suggest the way forward.

**Comment by adranit** [comment]
Hi @deb-dsc20 ,
Audio detection plugin from DL Streamer actually requires GST1.16. If you want to use it you need to update GST to v1.16. Otherwise you can set [ENABLE_AUDIO_INFERENCE_ELEMENTS=OFF](https://gitlab.devtools.intel.com/video-analytics/gst-video-analytics/-/blob/master/CMakeLists.txt#L143) to exclude audio plugin from build.

Thanks,
Anton

**Comment by deb-dsc20** [comment]
Thanks Adranit,
I tried with cmake .. -DENABLE_AUDIO_INFERENCE_ELEMENTS=OFF. 
But after make getting new error:
/home/pi/dlstreamer/dlstreamer_gst-master/gst/inference_elements/base/copy_blob_to_gststruct.cpp: In function ‘void CopyOutputBlobToGstStructure(InferenceBackend::OutputBlob::Ptr, GstStructure*, const char*, const char*, int32_t, int32_t)’:
/home/pi/dlstreamer/dlstreamer_gst-master/gst/inference_elements/base/copy_blob_to_gststruct.cpp:81:73: error: call of overloaded ‘safe_convert<unsigned int>(__gnu_cxx::__alloc_traits<std::allocator<unsigned int>, unsigned int>::value_type&)’ is ambiguous
             g_value_set_uint(&gvalue, safe_convert<unsigned int>(dims[i]));
                                                                         ^
In file included from /home/pi/dlstreamer/dlstreamer_gst-master/gst/inference_elements/base/copy_blob_to_gststruct.cpp:8:
/home/pi/dlstreamer/dlstreamer_gst-master/inference_backend/include/inference_backend/safe_arithmetic.h:141:49: note: candidate: ‘EnableIfUnSignedIntegralType<T> safe_convert(ValueType) [with ReturnType = unsigned int; ValueType = unsigned int; EnableIfUnSignedIntegralType<ValueType>* <anonymous> = 0; EnableIfUnSignedIntegralType<T> = unsigned int]’
 inline EnableIfUnSignedIntegralType<ReturnType> safe_convert(const ValueType value) {
                                                 ^~~~~~~~~~~~
/home/pi/dlstreamer/dlstreamer_gst-master/inference_backend/include/inference_backend/safe_arithmetic.h:159:13: note: candidate: ‘Type safe_convert(Type) [with Type = unsigned int]’
 inline Type safe_convert(const Type value) {
             ^~~~~~~~~~~~
make[2]: *** [gst/inference_elements/CMakeFiles/inference_elements.dir/build.make:63: gst/inference_elements/CMakeFiles/inference_elements.dir/base/copy_blob_to_gststruct.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:330: gst/inference_elements/CMakeFiles/inference_elements.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

The full log file is attached
[log_fail.txt](https://github.com/openvinotoolkit/dlstreamer_gst/files/5472803/log_fail.txt)

**Comment by adranit** [comment]
@deb-dsc20 , what version of gcc is installed on your system?

**Comment by deb-dsc20** [comment]
HEllo adranit,
gcc version is 8.3.0.
=> gcc --version
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mliu2020** [comment]
@deb-dsc20,

It has been a while, do you still have the issue?

Mark

**Comment by mliu2020** [comment]
@deb-dsc20 ,

I will wait for a week and close this issue if you are not response.

Mark

**Comment by deb-dsc20** [comment]
Hello Mark,
I am not using dlstreamer on Raspi anymore. I won't be able to try out new suggestions.
Thanks,
Deb

**Comment by mliu2020** [comment]
Thanks @deb-dsc20 for the quick response,

We are regret that you didn't use our tool, any feedback you want us know?

I am closing it now and feel free to re-open it or submit new issue.

Mark
