### ISSUE TITLE
command path of example is incorrect

### ISSUE THREAD

**Issue by WeiChungChang** [openvinotoolkit/dlstreamer_gst#149]
https://github.com/openvinotoolkit/dlstreamer_gst/wiki/GStreamer%20Video%20Analytics%20Tutorial
The tutorial command is wrong.

`export DETECTION_MODEL_PROC=~/gva/gst-video-analytics/samples/gst-launch/vehicle_pedestrian_tracking/model_proc/person-vehicle-bike-detection-crossroad-0078.json`

should be:

`export DETECTION_MODEL_PROC=~/gva/gst-video-analytics/samples/gst_launch/vehicle_pedestrian_tracking/model_proc/person-vehicle-bike-detection-crossroad-0078.json`

it is; **`gst-launch` should be `gst_launch`;**

Thanks.

**Comment by mliu2020** [comment]
Hi @WeiChungChang,

Thanks so much for the founding, your suggestion is very helpful to us.

I have confirmed this is a typo and we will fix it.

Mark

**Comment by adranit** [comment]
Fixed in 2021.2
https://github.com/openvinotoolkit/dlstreamer_gst/releases/tag/v1.3
