### ISSUE TITLE
WARNING: erroneous pipeline: no element "gvadetect"

### ISSUE THREAD

**Issue by Surajb007** [openvinotoolkit/dlstreamer_gst#151]
I am trying to run the models in docker on Windows 10 OS. I followed all the steps mentioned here https://github.com/openvinotoolkit/dlstreamer_gst/issues/75#issuecomment-649711880. Everything until downloading the models ran successfully. However, I am getting the following error when I am trying to run the pipeline in the last step:

`WARNING: erroneous pipeline: no element "gvadetect"`

Following is the pipeline that I am using and it is similar to the one mentioned in https://github.com/openvinotoolkit/dlstreamer_gst/issues/75#issuecomment-649711880:

`gst-launch-1.0 urisourcebin buffer-size=4096 uri=https://github.com/intel-iot-devkit/sample-videos/raw/master/head-pose-face-detection-female-and-male.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvadetect model=/root/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/age-gender-recognition-retail-0013.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/emotions-recognition-retail-0003.json device=CPU ! queue ! gvaclassify model=/root/intel/dl_streamer/models/intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml model-proc=/opt/intel/openvino/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/landmarks-regression-retail-0009.json device=CPU ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=false`

Any help to resolve this is much appreciated.

**Comment by mliu2020** [comment]
Hi @Surajb007,

This might related to the version of the release since #75 should be obsolete, could you check the following document and see if they help?
Getting Started:
https://gitlab.devtools.intel.com/video-analytics/video-analytics-serving/-/tree/develop
 
Docker file:
https://gitlab.devtools.intel.com/video-analytics/video-analytics-serving/-/blob/develop/docker/Dockerfile
 
Install dependencies:
https://gitlab.devtools.intel.com/video-analytics/video-analytics-serving/-/blob/develop/docker/Dockerfile#L29

Mark Liu

**Comment by Surajb007** [comment]
Hi @mliu2020,

Thanks for the response. Yes, I am using OpenVINO2021.1 and it can be seen in the below image:

![image](https://user-images.githubusercontent.com/11753666/98611205-727fad00-22bf-11eb-8ad7-167356016377.png)

The links that you mentioned in your comment above are not opening for me. Could you please help?

**Comment by mliu2020** [comment]
Thanks @Surajb007,

Are you using the docker image or local installation?

DL Streamer installation directory is at /opt/intel/openvino_2021/data_processing/dl_streamer, as I said, some pre-built docker image might not have DL Streamer installed.

Sorry my mistake for the URL, let me double check and get back.

Mark

**Comment by Surajb007** [comment]
Thanks, @mliu2020, I am using the docker image. I pulled it by using the following line:

`docker pull openvino/ubuntu18_data_dev`

I can see the dl_streamer directory:

![image](https://user-images.githubusercontent.com/11753666/98614176-e0c76e00-22c5-11eb-8275-f51569b6d64c.png)

**Comment by nnshah1** [comment]
@Surajb007 

For OpenVINO 2021.1 docker hub images, you'll need to install GStreamer dependencies in a separate step. 

We illustrate how to build a docker image using OpenVINO 2021.1 as a base image and installing required dependencies in our Video Analytics Serving project:

Getting Started:
https://github.com/intel/video-analytics-serving

Docker file:
https://github.com/intel/video-analytics-serving/blob/master/docker/Dockerfile
 
Install dependencies:
https://github.com/intel/video-analytics-serving/blob/37a10aafa772218bd9ac2d69ebeabc99039a24aa/docker/Dockerfile#L25  

 Let us know if you have any issues installing dependencies.

Neelay

**Comment by Surajb007** [comment]
Thanks @nnshah1, I cloned [video-analytics-serving](https://github.com/intel/video-analytics-serving) on my windows 10 machine and tried running the following command as per the documentation 

`./docker/build.sh`

But I am getting the following error:

![image](https://user-images.githubusercontent.com/11753666/98862975-b7c5eb00-2435-11eb-8ad7-96cd3e5628ad.png)

However, I can see the presence of models.list.yml file in the below screenshot:

![image](https://user-images.githubusercontent.com/11753666/98863102-de842180-2435-11eb-8ecf-b01bad076ae5.png)

Could you please guide me?

**Comment by nnshah1** [comment]
@Surajb007 We have a known issue with spaces in the path - can you try cloning to a path that doesn't have a space in it?

**Comment by Surajb007** [comment]
@nnshah1,

The image is pulled after I cloned into a  directory with no spaces, but still facing this error:

![image](https://user-images.githubusercontent.com/11753666/98869879-6bcc7380-2440-11eb-9fdd-c4718b70429c.png)

**Comment by nnshah1** [comment]
@Surajb007 Can you provide more context from the log before the error,  is this during the docker build? also where are you running the docker build script from? is it in the root of the repository?

**Comment by Surajb007** [comment]
@nnshah1, Yes it is during the docker build step and I am running it from the root of the repo, please see the below screenshot:

![image](https://user-images.githubusercontent.com/11753666/98958329-2b1c3b00-24d0-11eb-8e3e-00afa3e59d5a.png)

**Comment by nnshah1** [comment]
What type of windows environment are you using? Is it WSL 1.0 / WSL 2.0?

My guess is that the volume mount here: 

https://github.com/intel/video-analytics-serving/blob/37a10aafa772218bd9ac2d69ebeabc99039a24aa/docker/build.sh#L230 

Is not correctly formed for your system. (Unfortunately we only test on Linux flavors), Can you add an "echo" here to see the docker command it is running - I suspect again that the arguments to `-v` need to be adjusted for a Windows system.

**Comment by Surajb007** [comment]
@nnshah1, I am using WSL 1.0

Echoing volume_mount is resulting in the following line

![image](https://user-images.githubusercontent.com/11753666/99101989-6b042080-25ab-11eb-8723-6179ce4a3903.png)

So, it cannot be installed correctly on the windows system?

**Comment by mliu2020** [comment]
@Surajb007,

Can you confirm if /d/video-analytics-serving and /d/video-analytics-serving/models_list exits?

I checked quickly my WSL 1.0, a local directory in C drive always shows "/mnt/c/<local directory>". I guess you missed "/mnt" part here.

Mark

**Comment by Surajb007** [comment]
@mliu2020 

I changed it to be inside mnt and still getting the same error.

![image](https://user-images.githubusercontent.com/11753666/99449831-e50b1100-28ed-11eb-879f-50d64a5c7018.png)

Below is the screenshot of models_list directory. Please check

![image](https://user-images.githubusercontent.com/11753666/99449951-11269200-28ee-11eb-9809-fc1abc3028f6.png)

**Comment by pigubaoza** [comment]
i'm also getting similar warnings when running the samples in the docker container such as:
WARNING: erroneous pipeline: no element "gvainference"
WARNING: erroneous pipeline: no element "gvadetect"

There are no instructions on installing DL Streamer into the container, as the install guide simply says that it works.

install guide here:
https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide

This is the non-working container: openvino/ubuntu18_data_dev:latest container (7278372f381c)

I then tried openvino/ubuntu18_data_dev:2020.3.1 and it works. So for all facing the same problem, please take note of the non-working image, and use the working image instead.

**Comment by nnshah1** [comment]
I'd like to seperate into two threads here:

1. support for DL Streamer in OpenVINO docker images

    @pigubaoza 

    In OpenVINO 2021.1, the docker containers no longer have the required dependencies for DL Streamer by default, however, 
    you can install them via script that is within the container. 

    For an example on how to run the install script, please check (examples):

    Docker file:
     https://github.com/intel/video-analytics-serving/blob/master/docker/Dockerfile

    Install dependencies:
    https://github.com/intel/video-analytics-serving/blob/37a10aafa772218bd9ac2d69ebeabc99039a24aa/docker/Dockerfile#L25

    @mliu2020 We should update our documentation  / known issues to reflect this. We are working internally to see how to 
     remove this in future OpenVINO versions, but don't yet have an ETA.

1. support for VA Serving on Windows

    @Surajb007 , If you are interested in Windows support for VA Serving, let us open an issue here: 

    https://github.com/intel/video-analytics-serving/issues

    We have demonstrated this in the past and am happy to help work through to understand the issues but we are not testing / 
     validating on WSL as a primary target. There is no technical reason it should not work but there are quirks that need to be 
     ironed out. 

@mliu2020, @pigubaoza , @Surajb007  I consider the general issue of 1 (how to add support for DL Streamer in OpenVINO docker images) to be closed - please confirm.

On 2  If there is further interest, let us open issue in VA Serving repo for clarity. 

Thanks!

Neelay

**Comment by Surajb007** [comment]
@nnshah1,

Re-opened this issue in the VA repo here https://github.com/intel/video-analytics-serving/issues/44. Feel free to close this. Thanks!

**Comment by mliu2020** [comment]
Thanks @Surajb007,

Let me close it.

Mark

**Comment by pigubaoza** [comment]
thank you. for issue 1, I hope the team can add the install steps into the install guide to help others out https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide

**Comment by mliu2020** [comment]
The solution to @nnshah1 comment #1 is to add the installation of the GST dependencies to OpenVINO dependency installation script and this script is used for docker image creation, this is implemented in OV2021.2.
The script is [here](https://github.com/openvinotoolkit/openvino/blob/2021.2/scripts/install_dependencies/install_openvino_dependencies.sh#L56)

So the direction here is to improve "Out of Box" experience for docker build, so we decide not to add extra section in the installation guide. @Surajb007 Let me know if there are still issues with this solutions.

Mark
