### ISSUE TITLE
how can i decode video with iGPU by "vaapidecode" element

### ISSUE THREAD

**Issue by niuwenju** [openvinotoolkit/dlstreamer_gst#154]
after installing openvinotoolkit=2020.4, i run the demo of decodeing video by "vaapidecode" element but got errors as follows

`gst-launch-1.0 -v filesrc location=/home/dcg/Videos/sample_1080p_h264.mp4!       qtdemux ! vaapidecode ! vaapisink fullscreen=true`

_**WARNING: erroneous pipeline: no element "vaapidecode"**_

so how can i decode video with iGPU by "vaapidecode" element?

**Comment by mliu2020** [comment]
@niuwenju,

"vaapidecode" is not the VAAPI GST element name, in your case, you can use "vaapih264dec". DL Streamer recommends to use VAAPI GST element to access Intel hardware codec, the full list is here:
https://gstreamer.freedesktop.org/documentation/vaapi/index.html?gi-language=c

Mark

**Comment by niuwenju** [comment]
after replace it by vaapih264dec,there is also an error as follows
`gst-launch-1.0 -v filesrc location=/home/dcg/Videos/sample_1080p_h264.mp4!       qtdemux ! vaapih264dec ! vaapisink fullscreen=true`
**WARNING: erroneous pipeline: no element "vaapih264dec"**
so is there anything else should i do after installing openvinotoolkit=2020.4

**Comment by mliu2020** [comment]
@niuwenju,

The latest openVINO version is 2021.1 which should include vaapi element. If you install the previous version, you may have to installed a local GStreamer.

What is the OS and version you are using?

Mark

**Comment by niuwenju** [comment]
OS:ubuntu18.04
openvino==2020.4
i will try to update openvino to 2021.1

**Comment by niuwenju** [comment]
i have successfully installed openvino==2021.1 and installed IGPU driver in [Steps for Intel® Processor Graphics (GPU) ](https://docs.openvinotoolkit.org/2021.1/openvino_docs_install_guides_installing_openvino_linux.html#install-external-dependencies)
but there is also the same error as follows
**WARNING: erroneous pipeline: no element "vaapih264dec"**

**Comment by b04505009** [comment]
@niuwenju Did you run this ?
`source /opt/intel/openvino_2021/bin/setupvars.sh`

**Comment by niuwenju** [comment]
yes.and i can successfully run it in docker

**Comment by b04505009** [comment]
How about `gst-inspect-1.0 /opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstvaapi.so`?

**Comment by mliu2020** [comment]
@b04505009,

Thanks for the help!

Not sure what you are asking, the environment script solved @niuwenju's issue. Here is the output in my local host:
`
gst-inspect-1.0 /opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstvaapi.so
Plugin Details:
  Name                     vaapi
  Description              VA-API based elements
  Filename                 /opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstvaapi.so
  Version                  1.16.2
  License                  LGPL
  Source module            gstreamer-vaapi
  Binary package           gstreamer-vaapi
  Origin URL               http://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer

  vaapijpegdec: VA-API JPEG decoder
  vaapimpeg2dec: VA-API MPEG2 decoder
  vaapih264dec: VA-API H264 decoder
  vaapivc1dec: VA-API VC1 decoder
  vaapivp8dec: VA-API VP8 decoder
  vaapih265dec: VA-API H265 decoder
  vaapipostproc: VA-API video postprocessing
  vaapidecodebin: VA-API Decode Bin
  vaapisink: VA-API sink
  vaapimpeg2enc: VA-API MPEG-2 encoder
  vaapih265enc: VA-API H265 encoder
  vaapijpegenc: VA-API JPEG encoder
  vaapih264enc: VA-API H264 encoder
  vaapih264feienc: VA-API H264 FEI Advanced encoder (Experimental)

  14 features:
  +-- 14 elements
`

**Comment by niuwenju** [comment]
but in my local host it shows

`gst-inspect-1.0 /opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstvaapi.so`

Plugin Details:
  Name                     vaapi
  Description              VA-API based elements
  Filename                 /opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstvaapi.so
  Version                  1.16.2
  License                  LGPL
  Source module            gstreamer-vaapi
  Binary package           gstreamer-vaapi
  Origin URL               http://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer


  0 features:

**Comment by mliu2020** [comment]
@niuwenju,

Can you do following command and see if the output is different?

`/opt/intel/openvino_2021/data_processing/gstreamer/bin/gst-inspect-1.0 /opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstvaapi.so`

Mark

**Comment by niuwenju** [comment]
`dcg@dcg-Vostro-14-5459:/opt/intel/openvino_2021/data_processing/dl_streamer$ /opt/intel/openvino_2021/data_processing/gstreamer/bin/gst-inspect-1.0`

(gst-plugin-scanner:17289): GStreamer-WARNING **: 10:01:07.708: Failed to load plugin '/opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstdirectfb.so': libdirectfb-1.7.so.7: cannot open shared object file: No such file or directory

(gst-plugin-scanner:17289): GStreamer-WARNING **: 10:01:07.728: Failed to load plugin '/opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstopenni2.so': libOpenNI2.so.0: cannot open shared object file: No such file or directory

(gst-plugin-scanner:17289): GStreamer-WARNING **: 10:01:08.104: Failed to load plugin '/opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstneonhttpsrc.so': libneon.so.27: cannot open shared object file: No such file or directory

(gst-plugin-scanner:17289): GStreamer-WARNING **: 10:01:08.294: Failed to load plugin '/opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstladspa.so': liblrdf.so.0: cannot open shared object file: No such file or directory
alsa:  alsamidisrc: AlsaMidi Source
alsa:  alsasink: Audio sink (ALSA)
alsa:  alsasrc: Audio source (ALSA)
audiobuffersplit:  audiobuffersplit: Audio Buffer Split
wavenc:  wavenc: WAV audio muxer
gdkpixbuf:  gdkpixbufsink: GdkPixbuf sink
gdkpixbuf:  gdkpixbufoverlay: GdkPixbuf Overlay
gdkpixbuf:  gdkpixbufdec: GdkPixbuf image decoder
auparse:  auparse: AU audio demuxer
videomixer:  videomixer: Video mixer 2
soup:  souphttpclientsink: HTTP client sink
soup:  souphttpsrc: HTTP client source
libav:  avdeinterlace: libav Deinterlace element
libav:  avmux_yuv4mpegpipe: libav YUV4MPEG pipe muxer (not recommended, use y4menc instead)
libav:  avmux_wtv: libav Windows Television (WTV) muxer
libav:  avmux_webp: libav WebP muxer
libav:  avmux_wav: libav WAV / WAVE (Waveform Audio) muxer (not recommended, use wavenc instead)
libav:  avmux_w64: libav Sony Wave64 muxer
libav:  avmux_voc: libav Creative Voice muxer
libav:  avmux_vc1test: libav VC-1 test bitstream muxer
libav:  avmux_uncodedframecrc: libav uncoded framecrc testing muxer

**Comment by niuwenju** [comment]
and what should i do after installed openvino==2021.1

**Comment by mliu2020** [comment]
@niuwenju,

Did you solve the original issue? You said you can run the pipeline in docker now.

If you have a different question, please create a new issue.

For your last question, please following the following openVINO instructions:
https://docs.openvinotoolkit.org/2020.3/_docs_install_guides_installing_openvino_linux.html#install-openvino

Mark

**Comment by niuwenju** [comment]
not really,i can run the pipeline in docker which means i have a right hardware,but after installing openvino==2021.1 in my local host as shows in [https://docs.openvinotoolkit.org/2020.3/_docs_install_guides_installing_openvino_linux.html#install-openvino](https://docs.openvinotoolkit.org/2020.3/_docs_install_guides_installing_openvino_linux.html#install-openvino),still has the same error
**WARNING: erroneous pipeline: no element "vaapih264dec"**

also

`developer@localhost-14-5459:/opt/intel/openvino_2021/data_processing/dl_streamer$ /opt/intel/openvino_2021/data_processing/gstreamer/bin/gst-inspect-1.0 /opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstvaapi.so`

Plugin Details:
Name vaapi
Description VA-API based elements
Filename /opt/intel/openvino_2021/data_processing/gstreamer/lib/gstreamer-1.0/libgstvaapi.so
Version 1.16.2
License LGPL
Source module gstreamer-vaapi
Binary package gstreamer-vaapi
Origin URL http://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer

0 features:

**Comment by niuwenju** [comment]
and in my way to installing openvino shows in [ https://docs.openvinotoolkit.org/2020.3/_docs_install_guides_installing_openvino_linux.html#install-openvino]( https://docs.openvinotoolkit.org/2020.3/_docs_install_guides_installing_openvino_linux.html#install-openvino), i just follows it from step1 to step4 and step 6

**Comment by mliu2020** [comment]
Could you run other DL Streamer sample?

For example, /opt/intel/openvino_2021/data_processing/dl_streamer/samples/benchmark/

You can use this command "./benchmark.sh <input video> CPU CPU

Mark

**Comment by niuwenju** [comment]
yes,i can run this demo successfully.

**Comment by mliu2020** [comment]
Could you check VAAPI driver by command "vainfo" and the output?

Mark

**Comment by niuwenju** [comment]
`dcg@dcg-Vostro-14-5459:~$ vainfo`

Command 'vainfo' not found, but can be installed with:

sudo apt install vainfo

**Comment by mliu2020** [comment]
Yes, somehow you don't have VAAPI installed.

Could you run "lshw -c CPU" and output?

Mark

**Comment by niuwenju** [comment]
`cg@dcg-Vostro-14-5459:/opt/intel/mediasdk/bin$ lshw -c CPU`
WARNING: you should run this program as super-user.
  *-cpu                     
       product: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
       vendor: Intel Corp.
       physical id: 1
       bus info: cpu@0
       size: 1283MHz
       capacity: 3100MHz
       width: 64 bits
       capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d cpufreq
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.

**Comment by mliu2020** [comment]
You should have the hardware capability, so please install latest Media SDK:

- Go to https://github.com/Intel-Media-SDK/MediaSDK/releases/tag/intel-mediasdk-20.3.0
- Download tar.gz, unzip and run `sudo install_media.sh`
- After complete, run 'vainfo' again.

Mark

**Comment by niuwenju** [comment]
Thanks a lot! it work!

**Comment by mliu2020** [comment]
I think you mean you can run the GST command with vaapih264dec. This is good!

Sorry for taking so long, I was confused if you are running on local machine or docker. 

Do you have more questions?

Mark

**Comment by niuwenju** [comment]
i need run it on both of them,and it works now.
i dont have any questions for now.
Thanks!

**Comment by mliu2020** [comment]
Good! Let me close it.

Feel free to submit new issues.

Mark
