### ISSUE TITLE
README instructions incomplete?

### ISSUE THREAD

**Issue by Surya059** [openvinotoolkit/dlstreamer_gst#159]
Hi, I am using these instructions. 
https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide#install-in-docker-image

Changes I had to make to download_models:
1. I had to download PyYaml before being able to run the **sh download_models.sh**
2. I had to hardcode the OPENVINO downloader script path

Now I am wondering if I missed something that I had to install the PyYaml manually and change the **OPENVINO_DIR** path

**Comment by adranit** [comment]
@Surya059 , thank you for the bug report.

**Comment by adranit** [comment]
fixed in [2021.2 release](https://github.com/openvinotoolkit/dlstreamer_gst/releases/tag/v1.3)
