### ISSUE TITLE
How to compresse JPEG/PNG?

### ISSUE THREAD

**Issue by linrio** [openvinotoolkit/dlstreamer_gst#160]
I want to **lossless compresse JPEG/PNG** image with Intel Neural Compute Stick 2. How to do compression with dlstreamer_gst on NCS2? 
Here I notice that one can compress image with GStreamer: [Lossless compressed JPEG gstreamer element?](https://stackoverflow.com/questions/10033052/lossless-compressed-jpeg-gstreamer-element) and  [How to do image processing using gstreamer like opencv?](https://stackoverflow.com/questions/49366579/how-to-do-image-processing-using-gstreamer-like-opencv).

**Comment by mliu2020** [comment]
hi @linrio,

This is the issue list for DL Streamer: a Gstreamer plugin for OpenVINO inference engine. Your question is about how to use NCS2 to compress JPEG/PNG, so you might go to the following site for the quesiton:
https://community.intel.com/t5/Intel-Compute-Stick/bd-p/compute-stick-cards

Mark

**Comment by linrio** [comment]
hi @mliu2020 , Tks for showing the community site

**Comment by mliu2020** [comment]
@linrio,

No problem, feel free to reopen this if you think this still related to DL Streamer.

Mark Liu

**Comment by linrio** [comment]
HI, @mliu2020 
I followed [OpenVINO Media Processing](https://docs.openvinotoolkit.org/latest/media_processing.html), which is about DL Models on NCS2. I want to do image-processing such as JPEG/PNG compression. Can the dlstreamer do image-processing on NCS2?  
Tks!

**Comment by linrio** [comment]
Hi @mliu2020 ,
I asked the question on [](https://community.intel.com/t5/Intel-Compute-Stick/bd-p/compute-stick-cards):
question: [How to compresse JPEG/PNG on NCS2? ](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/How-to-compresse-JPEG-PNG-on-NCS2/m-p/1231949#M21650) @Iffa_Intel told that I should follow [Getting Started](https://github.com/openvinotoolkit/dlstreamer_gst#getting-started). However, I didn't find an effective solution. Where I should get help? tks!
