### ISSUE TITLE
DL Streamer binaries from OpenVINO package don't work if Libva(VA-API) is not installed 

### ISSUE THREAD

**Issue by adranit** [openvinotoolkit/dlstreamer_gst#164]
DL Streamer installed from OpenVINO(TM) Toolkit's APT and YUM packages does not work if libva (VA-API) is not already installed on the system.  No gva* elements can be loaded by GStreamer until libva (VA-API) is installed, even though it is not going to be used.

Workaround:
Install Libva(VA-API) library from appropriate OpenVINO™ Toolkit package.

**Comment by KarachunIvan** [comment]
For Ubuntu it can be install with this command:
sudo apt-get install libva2
For CentOS:
yum install -y libva

**Comment by adranit** [comment]
resolved in 2021.3
