### ISSUE TITLE
Can not init Myriad device: NC_ERROR

### ISSUE THREAD

**Issue by Warday** [openvinotoolkit/dlstreamer_gst#166]
That error occur when i try to execute my python code. I have installed openvino step by step and add usb rules. I successfully execute demo but when i use 
./demo_security_barrier_camera.sh -d MYRIAD
it make the same error But if i add sudo it get fixed and work successfully. Some fix for python? using cpu works perfect
on raspberry i have the same error (Tasted on Ubuntu 18.4 and raspbian)

**Comment by Warday** [comment]
Fixed using https://github.com/movidius. But when I make my own program it works but it seems it never close the device and if i try to execute other it make the error Can not init Myriad. So how can I terminate the device? if I want to load other network i can do it without plug out and plug in the device?
Thenx

**Comment by mliu2020** [comment]
Hi @Warday,

Sorry for the late response, when you said "..when I make my own program...", is this program a DL Streamer program or an OpenVINO program?

For DL Streamer program, I meant we use GStreamer, an open source media framework to inference the video frames, it can be implemented by command line, C/C++ or Python.

Mark

**Comment by mliu2020** [comment]
@Warday,

Are you still have questions for this issue?

The point to your last question is, "...never close the device..." should apply to OpenVINO programs; for DL Streamer program, this is the consequence of OpenVINO issue. If you can confirm, we will transfer this to OpenVINO, I think this is the better path.

I will wait for your response for  a week and close this if you are not response.

Mark

**Comment by mliu2020** [comment]
@Warday,

My question is trying to help you to address your question, you mentioned using "demo_security_barrier_camera.sh" at the beginning, I wanted to make sure if you were implementing the OpenVINO program before transferring to OpenVINO issue site.

Since I didn't get any feedback from you, I am closing this issue but feel free to re-open it if you still need help.

Mark
