### ISSUE TITLE
How to make model_proc.json

### ISSUE THREAD

**Issue by varunjain3** [openvinotoolkit/dlstreamer_gst#170]
So I trained a custom YoloV3, based of a TF2.0 backend. I was able to successfully convert it into the IE format, I have the xml and bin files, but I'm not really sure how can I make the the model proc file, can you please help? Also is there any formal documentation for model proc?

model.xml - https://drive.google.com/file/d/1CKNQZ5EFpi2uoGEg-3VQZfob4w2vgRhh/view?usp=sharing
model.bin - https://drive.google.com/file/d/1AA8p55GZsVVWKZBR05PN4suSzRh3sJGZ/view?usp=sharing

Github framework used for yolov3 - https://github.com/YunYang1994/TensorFlow2.0-Examples/tree/master/4-Object_Detection/YOLOV3

**Comment by mliu2020** [comment]
@varunjain3,

You can read the section 2 of the [Model preparation page](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Model-preparation), it also have a link to the JSON file examples.

Let me know if you still have question after reading this document.

Mark

**Comment by varunjain3** [comment]
Hi Mark @mliu2020, 

I want to use this model (shared above) in the [smart city sample for Open Visual Cloud](https://github.com/OpenVisualCloud/Smart-City-Sample). As far as I understood, I have to put my model in the [model folder](https://github.com/OpenVisualCloud/Smart-City-Sample/tree/master/analytics/crowd/models) and then give the correct location in the [pipeline](https://github.com/OpenVisualCloud/Smart-City-Sample/blob/d988471d2237c5ce16fa4203154461b996b741f0/analytics/crowd/Xeon/gst/pipeline/2/pipeline.json#L5 ) for the gstreamer.

So in the document you shared above -
> You can read the section 2 of the Model preparation page, it also have a link to the JSON file examples.

It says that, 
> GStreamer inference plugins are capable to optionally perform certain pre- and post-processing operations before/after inference.

Can you confirm that the .json is optional, and I will certainly not require it if i don’t want any pre/post processing.

Also, please explain what these lines mean,
> The post-processing is optional and enabled if either
>GStreamer element automatically detected model output format (currently only for SSD-like object detection models), or

Thanks

**Comment by mliu2020** [comment]
Hi @varunjain3,

Yes, the pre-/post- proc file is optional. 

You can refer to [this example](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/model_proc/yolo-v3-tf.json) for the model you are using. As the explanation to the last paragraph,If output_postproc is not defined, default converter is used. Default converter is “tensor_to_bbox_ssd”.

Mark Liu

**Comment by mliu2020** [comment]
@varunjain3,

Do you have more questions?

Mark

**Comment by varunjain3** [comment]
Thanks @mliu2020 , as of now I have shifted from using a Yolo model to a classification model, I m still working on it. I might need help configuring the model proc later on. But as of now, there are no further questions!

**Comment by mliu2020** [comment]
Thanks so much for using our product,

Let me close this one and feel free to reopen this or request a new issue.

Mark
