### ISSUE TITLE
Output issue with Docker in a VM environment

### ISSUE THREAD

**Issue by mliu2020** [openvinotoolkit/dlstreamer_gst#173]
[This request](https://github.com/openvinotoolkit/dlstreamer_gst/issues/118#issuecomment-751232388) was posted by @varunjain3 at #118

In his environment, he can't get either display output or file output. Since #118 was close, I created this issue to trace the request.

Mark

**Comment by mliu2020** [comment]
Hi @varunjain3,

I can see 2 issues here:

- Rendering: it requires x-server environment, since you mentioned running Docker in a VM environment, I am not sure if the X-Server is available here. You can true to replace xvimagesink with autovideosink, this element doesn't have framerate control but it should be no error.
- For "x264enc", this is the environment issue. Which OpenVINO version are you using? With 2021.1, there was an issue that x264enc is not included in the OpenVINO package, you have to combine with a local GST installation.

Let me know if this solves your problem.

Mark

**Comment by varunjain3** [comment]
Thanks for the reply @mliu2020 
>Rendering: it requires x-server environment, since you mentioned running Docker in a VM environment, I am not sure if the X-Server is available here. You can true to replace xvimagesink with autovideosink, this element doesn't have framerate control but it should be no error.

I was able to solve this problem, I realised that I was incorrectly using docker. 

>For "x264enc", this is the environment issue. Which OpenVINO version are you using? With 2021.1, there was an issue that x264enc is not included in the OpenVINO package, you have to combine with a local GST installation.

I am using the prebuilt docker container that is provided on the [installation guide page](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide#steps-1).

**Comment by mliu2020** [comment]
Good, you have the best path.

If you still want to use the original and add x264enc, you can refer to following page to install the default GStreamer(1.14.5) in Ubuntu 18.04 and add its libraries to the OpenVINO environment: export GST_PLUGIN_PATH="$GST_PLUGIN_PATH:/usr/lib/x86_64-linux-gnu/gstreamer-1.0"

But since GST openVINO has version 1.16.2, there could be side-effect.

Mark
