### ISSUE TITLE
How to normalize input in pre processing

### ISSUE THREAD

**Issue by niuwenju** [openvinotoolkit/dlstreamer_gst#176]
i have normalized frame before input in pre processing by python script,but it dont work.

**Comment by mliu2020** [comment]
Can you have some detailed information?

* What is the application?
* What is the pipeline?
* Are you using gvainference? what is the model?

All inference elements has the pre-proc capability and we have some general document you can check in the following page:
https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Model-preparation

You might check it first.

Mark

**Comment by niuwenju** [comment]
i`m trying to use yolov5 by DL Streamer and the pipeline like

` filesrc location=test_video/sample_1080p_h264.mp4 ! qtdemux ! vaapih264dec !     videoconvert ! capsfilter caps="video/x-raw,format=BGRx" !     gvapython module=~/DLStreamer_yolov5/yolov5_pre.py !     gvainference model=model/yolov5l_v2/FP16/yolov5l_v2.xml device=MYRIAD ! queue !     gvapython module=~/DLStreamer_yolov5/yolov5_post.py !     gvawatermark name=gvawatermark ! videoconvert !     fpsdisplaysink video-sink=xvimagesink sync=false`

**Comment by mliu2020** [comment]
Hi @niuwenju,

Sorry for the late response, I somehow missed your reply.

By checking your pipeline command, I can see one issue: "gvapython" is used for post-processing not for pre-processing as you can see from [this page](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/gvapython):
`...used for metadata conversion, inference post-processing,...`

Can you share the error message you got?

Three inference elements has pre-defined pre-proc algorithm and it should support YoloV3, but I don't know if it support YoloV5. Let me check.

Mark

**Comment by mliu2020** [comment]
Hi @niuwenju,

Did you still have this issue?

The other problem in your pipeline, OpenVINO doesn't support YoloV5 yet. So this pipeline should not work.

Do you still need help? I will wait for a week and if you don't have answer or request, I will close this issue.

Mark Liu

**Comment by mliu2020** [comment]
Hi @niuwenju,

Let me close it for now and feel free to reopen it or submit a new issue.

Mark Liu
