### ISSUE TITLE
How to attach and extract custom metadata generated by custom written plugin?

### ISSUE THREAD

**Issue by devdastl** [openvinotoolkit/dlstreamer_gst#178]
Hello everyone, 

I have written a custom plugin and I want to attach generated metadata to the buffer so that I can access that custom metadata in other plugins like "gvametaconvert" to be able to publish it.

Right now how I am attaching the metadata is by modifying `region_of_interest.h` file in `gst-libs/gst/videoanalytics/` and adding functions similar to what are used to attach object_id generated by tracker plugin. Below are the functions from `region_of_interest.h` which I have taken as reference - 
1. `void set_object_id(int32_t id) {...}`
2. `int32_t object_id() const {...}`

My question is, are there any other better ways to attach and extract custom metadata in the plugin which doesn't requires editing source file.  Also I am trying to pass nested array but only managed to pass one dimensional array.

Please let me know if any other information is required from my side.
Thanks in advance!

**Comment by ymaskina** [comment]
There are two ways to attach custom metadata not editing DL Streamer source code (you should implement it in your element's code):
1) using DL Streamer C++ API:
You should create `VideoFrame` from buffer, then get `std::vector<RegionOfInterest>` from `VideoFrame` with `video_frame.regions()`. `RegionOfInterest` class has method `add_tensor()`. This method adds empty `GstStructure` with name to meta and returns created `tensor`. With returned `tensor `you can use methods like` set_name()`, `set_int()` etc. 
2) If functionality of API is not enough for your goal there is another way:
You should use `gst_buffer_iterate_meta_filtered()`  function to get `GstVideoRegionOfInterestMeta` from buffer, create your `GstStructure `with needed fields and name and add it to meta with `gst_video_region_of_interest_meta_add_param()`

[Here](https://openvinotoolkit.github.io/dlstreamer_gst/) you can find more detailed description and samples of code.

`gvametaconvert `will try to publish custom tensor (see [convert_tensor.cpp](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/gst/elements/gvametaconvert/convert_tensor.cpp)). 
I don't know what meta you want to attach, most likely you should modify `gvametaconvert` to publish your results or write your own element for it.

I'm not sure about question about arrays. It makes sense to read Gstreamer documentation about this. Also you can share  more details: where exactly did you try to pass nested array, how?

**Comment by devdastl** [comment]
Thanks a lot @ymaskina  for your replay,

Also thanks for sharing documentation, after going through that documentation I figured out that I want to attach custom metadata at **frame level** (or for each **VideoFrame** objects) and not for each **ROI objects**. 

Based on above correction and two methods of attaching metadata that you have mentioned I have following query- 

1. Can I create empty tensor at frame level (which I think I could because there are functions to add tensor and get tensor in VideoFrame class) similar to what you have mentioned for each ROI object in first approach. 

2. Since my custom plugin is generating groups of integer per buffer/frame, I want to attach those integer values as nested array or preferably as nested vectors to each frame. But I didn't find any such methods to attach nested array or even 1D array in Tensor class description. 

3.  If there are no methods to attach array or nested array then can I create a child class of Tensor class so that I can add those methods(`taking std::vector<guint> dims const(){..}` in `gst-libs/../../tensor.h` as reference) . Also I tried  to figure out how I can attach nested array  through Gstreamer documentation but no luck. Only if I could convert or save nested array as `GValueArray` then I can pass that `GValueArray` into `gst_structure_set_array()` function to attach it.

4. Can I use second approach mentioned by you to attach metadata at frame level. If yes then I think this approach could be a preferred way of attaching custom metadata as array if not as nested array. 


I really want to attach a nested array as custom metadata but if it is not possible then I have to figure out some way to convert nested array into 1D array and then again back to nested array.

Let me know if any of my query is not clear or requires more information.

**Comment by ymaskina** [comment]
1. That's correct, `VideoFrame` can have own tensors like `RegionOfInterest`.
2. There is no method that allow you set an array in `tensor`
3-4. You can use method `add_tensor()` of `VideoFrame `class. This method creates  `GstGVATensorMeta`, adds it to buffer and returns created tensor. Using `gst_structure()` method of Tensor class you can get access to `GstStructure `of `GstGVATensorMeta `and set there what ever you want.
[Here](https://github.com/openvinotoolkit/dlstreamer_gst/blob/a644d52ab9af0932673fd77b028a05e246c339a1/gst/inference_elements/base/copy_blob_to_gststruct.cpp#L14) is sample of adding array 
If you know dimensions of your array it will be easy to parse it into 1d array and vise versa, this is the first thing that comes to mind.

**Comment by devdastl** [comment]
Thanks a lot @ymaskina,

That's solved my problem. Now I am able to attach my array into the buffer using `GstGVATensorMeta` and I am also able to convert my 1D array into nested array after retrieving it from another plugin(like gvawatermark).

I have one last question - 
If I want to overlay my custom metadata on the output video as well as if I want to publish my custom metadata then for that I have to edit both **gvawatermark** and **gvametaconvert** plugin. But I don't want to edit any **GVA plugins** for extracting that custom metadata and process it. Is there any way in which I can avoid doing any changes in **GVA plugins** and still able to process custom metadata.

Thanks for the help!

**Comment by ymaskina** [comment]
I don't know a lot of details about your metadata, so I can't say for sure
Most likely you will have to modify existing elements or write your own.
Also you can modify the buffer in your element`s `transform_ip()` function to overlay results on the output video (the same for publishing)

**Comment by mliu2020** [comment]
@devdastl,

As my understanding, if you want to customer your overlay without touching GVA plugins, you can implement a python script called by gvapython. If you do this after you attached the meta data, you can access both VideoFrame and metadata in the python script to create the overlay.

For publishing metadata, you can use gvametapublish; but if want your own publish method, you can use he same process as the overlay creation I mentioned above.

Let me know if this solved your problem.

Mark

**Comment by devdastl** [comment]
Hello @mliu2020,

Sorry for the delayed replay...
Thanks for suggesting idea of using gvapython plugin, I think it can help me with my issue. 
Will it be possible for you to share any example utilizing gvapython plugin, I tried searching for the examples but didn't find any.

Thanks

**Comment by ymaskina** [comment]
[Here](https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples/gst_launch/gvapython/face_detection_and_classification) you can find examples of python callbacks for gvapython and README file

**Comment by mliu2020** [comment]
Hi @devdastl,

Let me know if @ymaskina's example works for you or you need more help.

Mark

**Comment by devdastl** [comment]
Hello @mliu2020,

Sorry for the delayed response. 

Yes, GVA python plugin solved my issue but I had to modify gvawatermark as it was little tough to use GVA Python to overlay data. 

Thanks a lot for the help..

**Comment by mliu2020** [comment]
Thanks @devdastl,

Glad you solve the problem and thanks for feedback.

I really appreciate your feedback, this will help us to improve. So before I close the issue, could you specify your pain point?

Mark Liu

**Comment by mliu2020** [comment]
@devdastl,

Thanks for the great feedback, we will discuss your feedback for improvement.

Let me close it for now and feel free to put the comment.

Mark

**Comment by Rasmita-Ardu** [comment]
@devdastl 
![image](https://user-images.githubusercontent.com/34830728/136163581-9ad7a65c-ef66-4bba-a769-3a75330c3a89.png)
I want to use the videoframe constructor in my C++ application. But whenever, I try building it, I get so many errors. 
Not sure why is it happening ? 
Can you guide me ??

**Comment by sbmalik** [comment]
Hey @devdastl I wanted to get and save the VideoFrame from the buffer, I created a custom **GstBaseTransform** element and using following code for doing the task in  `_transform_ip`  function. But it skips the frames and also reduces around 10 FPS. Can you please guide on this?

```
static GstFlowReturn
gst_m_hello_world_t_transform_ip(GstBaseTransform *trans, GstBuffer *buf)
  {
  
  GstMHelloWorldT *mhelloworldt = GST_M_HELLO_WORLD_T(trans);
  GST_DEBUG_OBJECT(mhelloworldt, "transform_ip");

  // GET CAPS from element
  GstCaps *caps = gst_pad_get_current_caps(GST_BASE_TRANSFORM_SINK_PAD(mhelloworldt));

  GVA::VideoFrame video_frame(buf, caps);
  guint width = video_frame.video_info()->width;
  guint height = video_frame.video_info()->height;

  std::time_t t = std::time(0);
  std::string filename = "saved_frames/frame__" + std::to_string(t) + std::string(".jpg");

  GstMapInfo map;
    if (!gst_buffer_map(buf, &map, GST_MAP_READ))
        return GST_FLOW_OK;

  cv::Mat mat(height, width, CV_8UC4, map.data);
  cv::imwrite(filename, mat);
  
  return GST_FLOW_OK;
  
  }
```

Launch command for this is following, where **mhelloworldt** is my element

```
gst-launch-1.0 filesrc location=video.mp4 ! decodebin ! videoconvert ! capsfilter caps="video/x-raw,format=BGRx" ! queue ! mhelloworldt ! queue ! gvadetect model-instance-id=yolov5 model=yolov5.xml labels-file=yolov5.txt model-proc=yolov5.json device="CPU" batch-size=1  ! gvatrack tracking-type=zero-term ! queue ! identity name=identity_0 ! gvafpscounter ! fakesink sync=false
```
