### ISSUE TITLE
How to use x264enc element?

### ISSUE THREAD

**Issue by thinkinds** [openvinotoolkit/dlstreamer_gst#179]
I am trying to output my inference result through a RTSP server.  So my pipeline is something like:  file-source -> h264-parser -> decoder ->   gvadetect -> gvainference -> gvawatermark ->  encoder -> rtppay -> udpsink, where encoder is x264enc. When I executed my pipeline inside the openvino/ubuntu18_data_dev docker container, I got following error:
```
Traceback (most recent call last):
  File "rtsp_test.py", line 141, in <module>
    pipeline = Gst.parse_launch(gst_launch_string)
GLib.Error: gst_parse_error: no element "x264enc" (1)
```
I used gst-inspect-1.0 to check :
`gst-inspect-1.0 x264enc`
result is: 
`No such element or plugin 'x264enc'`

Then, I used apt-get to install gstreamer1.0-plugins-ugly:amd64, which is supposed to comprise the x264enc. However, after installation, gst-inspect-1.0 still cannot find x264enc.

How can I get it work? Thanks in advance.

**Comment by brmarkus** [comment]
Can it be assumed that the installation of `gstreamer1.0-plugins-ugly:amd64` went fine and you can find the installed files inside of your Docker container?
Then it looks like it's needed to extend the gstreamer plugin search-path - as the DL-Streamer plugins are deployed somewhere else than the binaries installed via `apt-get`.

**Comment by thinkinds** [comment]
> Can it be assumed that the installation of `gstreamer1.0-plugins-ugly:amd64` went fine and you can find the installed files inside of your Docker container?
> Then it looks like it's needed to extend the gstreamer plugin search-path - as the DL-Streamer plugins are deployed somewhere else than the binaries installed via `apt-get`.
> (see e.g. the issue #173)
Thanks for your quick reply. 
1. How could I make sure the installation went fine?
```
# dpkg -l | grep x264
ii  libx264-152:amd64                    2:0.152.2854+gite9a5903-2           amd64        x264 video coding library
ii  libx264-dev:amd64                    2:0.152.2854+gite9a5903-2           amd64        development files for libx264
ii  x264                                 2:0.152.2854+gite9a5903-2           amd64        video encoder for the H.264/MPEG-4 AVC standard
```
```
dpkg -l | grep gst 
ii  gstreamer1.0-alsa:amd64              1.14.5-0ubuntu1~18.04.1             amd64        GStreamer plugin for ALSA
ii  gstreamer1.0-plugins-bad:amd64       1.14.5-0ubuntu1~18.04.1             amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-base:amd64      1.14.5-0ubuntu1~18.04.1             amd64        GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-good:amd64      1.14.5-0ubuntu1~18.04.1             amd64        GStreamer plugins from the "good" set
ii  gstreamer1.0-plugins-ugly:amd64      1.14.5-0ubuntu1~18.04.1             amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.0-rtsp:amd64              1.14.5-0ubuntu1~18.04.1             amd64        RTSP plugin for GStreamer
ii  gstreamer1.0-vaapi:amd64             1.14.5-0ubuntu1~ubuntu18.04.1       amd64        VA-API plugins for GStreamer
ii  libgstreamer-gl1.0-0:amd64           1.14.5-0ubuntu1~18.04.1             amd64        GStreamer GL libraries
ii  libgstreamer-plugins-bad1.0-0:amd64  1.14.5-0ubuntu1~18.04.1             amd64        GStreamer libraries from the "bad" set
ii  libgstreamer-plugins-base1.0-0:amd64 1.14.5-0ubuntu1~18.04.1             amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-good1.0-0:amd64 1.14.5-0ubuntu1~18.04.1             amd64        GStreamer development files for libraries from the "good" set
ii  libgstreamer1.0-0:amd64              1.14.5-0ubuntu1~18.04.1             amd64        Core GStreamer libraries and elements
ii  libgstrtspserver-1.0-0               1.14.5-0ubuntu1~18.04.1             amd64        GStreamer RTSP Server (shared library)
```
Is the output above right?

2. path has been added, as below:
```
echo $GST_PLUGIN_PATH                     
/opt/intel/openvino/data_processing/dl_streamer/lib:/opt/intel/openvino/data_processing/gstreamer/lib/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer1.0

```
But gst-inspect-1.0 still cannot find x264enc...  What should I do?

**Comment by thinkinds** [comment]
I checked the dockerfile of openvino/ubuntu18_data_dev:latest, where gstreamer1.0-plugins-ugly is includedin apt-get install command:

`# GStreamer core
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install --no-install-recommends -q -y \
        libglib2.0-dev \
        libgmp-dev \
        libgsl-dev \
        gobject-introspection \
        libcap-dev \
        libcap2-bin \
        gettext \
        libssl-dev \
        ffmpeg \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-libav \
        gstreamer1.0-plugins-ugly \
        gstreamer1.0-alsa \
        gstreamer1.0-pulseaudio \
        libgstreamer1.0-0 \
        libgstreamer1.0-dev \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer-plugins-bad1.0-dev \
        libgirepository1.0-dev && \`
Why I cannot find x264enc that is a part of ugly plugins?

**Comment by mliu2020** [comment]
Hi @thinkinds,

It seems only installed gstreamer1.0-plugins-ugly might be the problem.

I am not sure in the docker environment, but I refer to the following URL to install the Gstreamer and this seems work for me:
http://lifestyletransfer.com/how-to-install-gstreamer-on-ubuntu/

Since you are using docker, you can also only try to install GStreamer and see if you can get x264enc and then install OpenVINO.

In both paths either install GST or OpenVINO first, also pay attention to remove the local cache before "gst-inspect-1.0":
`rm -rf ~/.cache/gstreamer-1.0`

Mark Liu

**Comment by thinkinds** [comment]
> Hi @thinkinds,
> 
> It seems only installed gstreamer1.0-plugins-ugly might be the problem.
> 
> I am not sure in the docker environment, but I refer to the following URL to install the Gstreamer and this seems work for me:
> http://lifestyletransfer.com/how-to-install-gstreamer-on-ubuntu/
> 
> Since you are using docker, you can also only try to install GStreamer and see if you can get x264enc and then install OpenVINO.
> 
> In both paths either install GST or OpenVINO first, also pay attention to remove the local cache before "gst-inspect-1.0":
> `rm -rf ~/.cache/gstreamer-1.0`
> 
> Mark Liu

Thanks for your help, I got it work at last.
