### ISSUE TITLE
Release Build with Debug Information

### ISSUE THREAD

**Issue by vt911001** [openvinotoolkit/dlstreamer_gst#180]
Hi,

Is it possible to build dlstreamer in release mode but with debug information?

Thanks,
Vincent

**Comment by mliu2020** [comment]
@vt911001,

Sure let me check and allow me to ask around, and I assume, you already read the following document and can't find the solution:
https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide

Mark

**Comment by mliu2020** [comment]
Hi @vt911001,

I checked with dev team and we don't setup any special flags, could you check the general cmake flags and see if this help?

https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html

Mark Liu

**Comment by vt911001** [comment]
Hi Mark,

Sure, let me check that out.

Vincent
