### ISSUE TITLE
Saving video clips based on inference output

### ISSUE THREAD

**Issue by Surya059** [openvinotoolkit/dlstreamer_gst#181]
Hi, We have a scenario where we need to save a 5 second video clip only at selected times when an anomaly occurs ( Eg: cat enters the scene at night) . Is it possible to trigger a video saving from an element in the application?

**Comment by nnshah1** [comment]
@Surya059 It is definitely possible to trigger video saving using GStreamer elements and an application that would send action signals / change element properties. To develop an example would take a little work. 

Another approach could be to save segments in 5 sec chunks and then at a regular cadence delete any uninteresting clips. Essentially pre save the clips and the inference results and then remove any clips that don't have the anomaly you are looking for.

We have a basic sample demonstrating how to save and replay inference results on top of stored segments:

https://github.com/intel/video-analytics-serving/tree/master/samples/record_playback 

That could be modified to clear out segments / move segments where detection results are seen.

**Comment by mliu2020** [comment]
@Surya059,

Did our solution work for you? Let me know if you need more help.

Mark

**Comment by Surya059** [comment]
Yes, It works. but there is more resource usage when we are saving the videos in sliding window fashion continuously. Is there a better way only to encode and save video once there is trigger from code?

**Comment by mliu2020** [comment]
@Surya059,

Agree with you. There is other factor--timing, there should be some delay when you find the scenario and decide to record.

I did some research, the function should called "video loop recording", like [this one](https://github.com/maxneaga/open_dash_cam_android). Under this design, you will always record one file and overwrite it when the time is up(5 seconds in your case), Once you find the scenario, the recorded file will be kept.

Mark Liu
