### ISSUE TITLE
gvawatermark failed to map GstBuffer to system memory when using VAAPI

### ISSUE THREAD

**Issue by tunght** [openvinotoolkit/dlstreamer_gst#182]
Hi, 

The release version 2021.1 said it currently supports GPU memory surface in gvawatermark however I still get errors when using gvawatermark.
The error is 
ERROR: from element /GstPipeline:pipeline0/GstGvaWatermark:gvawatermark0: watermark has failed to draw label
Additional debug info:
/home/vedge/dl-streamer/gst/elements/gvawatermark/watermark.cpp(292): draw (): /GstPipeline:pipeline0/GstGvaWatermark:gvawatermark0:
Failed to map GstBuffer to specific memory type
	Failed to map GstBuffer to system memory

In the pipeline im using videoconvert ! video/x-raw\(memory:VASurface\)

Could you please help?
Thanks

**Comment by mliu2020** [comment]
Hi @tunght,

From the error message, it seems you are using the system memory which you can check following code:
https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/gst/common/gva_buffer_map.cpp#L104

As you can see VASurface should have different error message. So I think there might be some problem with negotiation.

GStreamer negotiation process is tricky, it would be better to post your full pipeline.

The other choose is to simplify the pipeline to a simplest form where the error happens.

Mark Liu

**Comment by tunght** [comment]
Hi @mliu2020 

Thank you for your response.
This is the pipeline im using 
gst-launch-1.0 rtspsrc location=rtsp://10.1.1.30/axis-media/media.amp ! rtph264depay ! h264parse ! queue ! decodebin ! videoconvert n-threads=4 ! video/x-raw\(memory:VASurface\) ! gvadetect model=/home/vedge/models/face-detection-0204/FP32/face-detection-0204.xml device=MULTI:CPU,GPU pre-process-backend=vaapi ! queue ! gvawatermark ! videoconvert ! autovideosink

**Comment by tunght** [comment]
I looked at the code for in gvawatermark. It uses system memory specifically. This is the line causes the issue

https://github.com/openvinotoolkit/dlstreamer_gst/blob/a644d52ab9af0932673fd77b028a05e246c339a1/gst/elements/gvawatermark/watermark.cpp#L280

**Comment by mliu2020** [comment]
Thanks,

Let me try your pipeline to see if I can reproduce.

Yes, the line I post before is the location in gva_buffer_map() where the error message "Failed to map GstBuffer to system memory" was printed.

Mark Liu

**Comment by ymaskina** [comment]
This issue can be related to vaapi elements, not gvawatermark.
 You can try to replace `decodebin ! videoconvert n-threads=4 ! video/x-raw(memory:VASurface) ` to `vaapih264dec` in your pipeline

**Comment by mliu2020** [comment]
Thanks @tunght,

If you want to post this issue to Gstreamer-VAAPI, please go to https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues 

I am not sure which GST version you are using, but 1.18 or later would have a lot of bug fixing and new features.

Mark

**Comment by tunght** [comment]
Thank you very much @mliu2020 . I'm using 1.16.2. I would love to use newest version of gstreamer, i'm just not sure whether dlstreamer support latest version of gstreamer?

**Comment by mliu2020** [comment]
You are right, afaik DL Streamer uses 1.16.2. Please file a ticket there and see if they could figure it out.

Mark

**Comment by b04505009** [comment]
Is there any update on this issue?
In my experiment this may related to vaapipostproc

This will pass:
```
gst-launch-1.0 filesrc location=../test_videos/video.mp4 ! qtdemux ! h264parse ! \
vaapih264dec ! "video/x-raw(memory:VASurface),format=NV12" ! \
gvadetect model=ssd_pd_300x300.xml model_proc=ssd_pd_300x300.json  pre-process-backend=vaapi ! \
gvawatermark ! vaapisink
```

While this will got error:
```
gst-launch-1.0 filesrc location=../test_videos/video.mp4 ! qtdemux ! h264parse ! \
vaapih264dec ! vaapipostproc ! "video/x-raw(memory:VASurface),format=NV12" ! \
gvadetect model=ssd_pd_300x300.xml model_proc=ssd_pd_300x300.json  pre-process-backend=vaapi ! \
gvawatermark ! vaapisink
```

Error message:
```
Got context from element 'vaapisink0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstGvaWatermark:gvawatermark0: watermark has failed to draw label
Additional debug info:
/home/gvsai/dlstreamer_gst/gst/elements/gvawatermark/watermark.cpp(292): draw (): /GstPipeline:pipeline0/GstGvaWatermark:gvawatermark0:
Failed to map GstBuffer to specific memory type
	Failed to map GstBuffer to system memory

ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by ymaskina** [comment]
@b04505009 vaapipostproc element can lead to this error when used in passthrough mode (gst-vaapi-1.16.2 version).  Vaapipostproc is also implicitly called by decodebin element, so there was the same problem with the pipeline from original issue.
As workaround you can set some property to vaapipostproc, e.g `vaapipostproc ! "video/x-raw(memory:VASurface),format=NV12,brightness=0.0001"`  or simply remove vaapipostproc from the pipeline, since passthrough mode means that vaapipostproc does nothing.
