### ISSUE TITLE
Error opening file /samples/bottle_detection.mp4: No such file or directory

### ISSUE THREAD

**Issue by amajai** [openvinotoolkit/dlstreamer_gst#184]
I am trying to POST the sample video from local file to the object detection endpoint but I get this error. 
```bash
{"levelname": "ERROR", "asctime": "2021-02-12 11:31:56,109", "message": "Error on Pipeline 1: gst-resource-error-quark: Resource not found. (3): ../gst/gio/gstgiosrc.c(324): gst_gio_src_get_stream (): /GstPipeline:pipeline7/GstURISourceBin:source/GstGioSrc:source:\nCould not open location file:///samples/bottle_detection.mp4 for reading: Error opening file /bottle_detection.mp4: No such file or directory", "module": "gstreamer_pipeline"}
```

This json request that I have sent.
```bash
{
  "source": {
    "uri": "file://samples/bottle_detection.mp4",
    "type": "uri"
  },
  "destination": {
    "type": "file",
    "path": "/tmp/test.json",
    "format": "json-lines"
  }
}
```
Is there a way to resolve it?

**Comment by nnshah1** [comment]
@amajai This looks like you are using:

https://github.com/intel/video-analytics-serving 

If this is the case - you will need to place the file in a location accessible from the container.

Simplest approach is to use, the  `/tmp/samples`.

In that case you can move `bottle_detection.mp4` to `/tmp/samples` and then update your request to use:

`file:///tmp/samples/bottle_detection.mp4`

It also maybe a type in the uri, `file:///samples/bottle_detection.mp4` - to my knowledge we only support absolute paths in the `file://` scheme.

Do you mind if we move this issue to https://github.com/intel/video-analytics-serving? 

In case you have additional questions we will be better able to direct them to the right team.

**Comment by amajai** [comment]
Thanks for the response, will try it out now. Sorry for posting the issue in the wrong repo. I will move it now

**Comment by nnshah1** [comment]
@amajai - No apologies necessary - the two projects are highly related so its is perfectly understandable - I just want to make sure you get answers more quickly. It's really just to speed up the routing of your question. Thanks for understanding.
