### ISSUE TITLE
Issue when using Facenet model for face recognition

### ISSUE THREAD

**Issue by sanshr** [openvinotoolkit/dlstreamer_gst#187]
I want to build pipeline for face detection and recognition. I have successfully converted the publicly available pre-trained  facenet model to IR (.xml and .bin) and using it to extract face embedding (feature vector). Also, I am using Intel's model "face-detection-retail-0004" IR model to detect faces on frames. Basically, I want the pipeline to do something like the following:

detect face(s) on the frame ==> pass the detected face to facenet model to obtain face embedding ==> pass the embedding feature vector to SVM classifier to recognize the person in the frame

I already have trained SVM classsifer and have the .pkl model file.

My pipeline is set up something like the following:

```
PIPELINE="gst-launch-1.0 \
$SOURCE_ELEMENT ! decodebin ! \
gvadetect model=face-detection-retail-0004.xml device=cpu ! queue ! \
gvainference model=facenet.xml device=cpu! queue ! \
gvapython module=$PYTHON_SCRIPT1 ! \
gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false"
```

In `$PYTHON_SCRIPT1`, I am doing post-processing by retrieving raw tensor data which is the face embedding and doing the classification using the classifier `.pkl` model. Something like this:

```
with open("classifier.pkl", 'rb') as infile:
    (model, class_names) = pickle.load(infile)

def process_frame(frame: VideoFrame, threshold: float = DETECT_THRESHOLD) -> bool:
    for roi in frame.regions():
        for tensor in roi.tensors():
            if tensor.layer_name() == 'embeddings':
                predictions = model.predict_proba([tensor.data()])
                best_class_indices = np.argmax(predictions, axis=1)
                tensor.set_label(class_names[best_class_indices[0]])

    return True
```

The predictions made by the above implementation are wrong. It is able to retrieve facial embeddings but I don't think they are correct. My guess is the input to `gvainferece` facenet model is not right. We might not be passing the input in proper format for the model to process which is the detected face images in rgb format in fixed dimension 160x160. If this is the case how do I do it exactly? I did try messing around with `model_proc` to `gvainference` to pre-process model input but no luck.

Is there something that I am doing wrong? Would this be recommended way to solve face detection and recognition problem with dlstreamer gst pipeline?

**Comment by nnshah1** [comment]
I think I see the issue, can you try using `gvaclassify` instead of `gvainference`. `gvaclassify` will work on the detected ROIs by default, `gvainference` will work accross the original image by default.

For a working example using the model from open model zoo (using simple distance calculation instead of SVM):

https://github.com/intel/video-analytics-serving/issues/19#issuecomment-688582265 

  https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/face-recognition-resnet100-arcface/face-recognition-resnet100-arcface.md

**Comment by sanshr** [comment]
@nnshah1 : Unfortunately, I did try using `gvaclassify` but still the same issue. I did try `gvainference` and added `"inference-region"= 1` to target only ROI found by `gvadetect` but couldn't get it working properly.  Facenet embeddings are obtained  in proper format  as I could see it by printing `tensor.data()` but the inference is wrong. The SVM model is correct and so is facenet model as it works perfectly fine in a separate python program without pipeline implementation.  I believe the appropriate input is not being passed to `gvainference` facenet model after `gvadetect` and it just calculates the wrong face embeddings. Should I do model input processing for gvainference facenet model as it accepts input image of fixed dimension 160x160 in rgb? If so, what would be input prepossessing in json file?

Is there anyway I can see what is being passed as region of interest by `gvadetect`?  like get the buffer blob or image for region of interest?

I went through the example of face recognition in video analytic serving you supplied and tried to follow it. But, I couldn't make it work.

**Comment by nnshah1** [comment]
@sanshr Thanks for the update - what issue did you have with the face recognition video analytics serving sample? Can you provide more details? That should work with no changes.

The color space for the facenet model might need to be specified as I believe the default will be BGR, try a model-proc file like the following:
```
{
  "json_schema_version": "2.0.0",
  "input_preproc": [
    {
      "format": "image",
      "layer_name": "0",
      "params": {
        "color_space": "RGB"
      }
    }
  ]
}
```

**Comment by sanshr** [comment]
@nnshah1 Thank you for your prompt response. The issue I faced  with the example you sent was converting "face-recognition-resnet100-arcface" mxnet model to IR using openvino model optimizer. It complained that I needed to supply input shape of the model and I did. Then, again, when using it - the pipeline didn't work. It just freezes after first few frames. Not sure if model-proc version json 1.0.0 had anything to do with it.

I tried the model-proc on  facenet model but still it gives me incorrect inference result while still  producing 512 feature vector embeddings in `tensor.data()`

**Comment by nnshah1** [comment]
Thanks, I will take a look at the va serving sample - I should be able to get that to work - might need some updates for the latest version of the model.

For the facenet model - is it possible to share model IR along with some expected input / output pairs? 

I would start by removing the detection phase and sending in a pre-cropped image, use full frame inference / classification - and ensure that is giving the results you expect compared to a known input /output pair

**Comment by sanshr** [comment]
@nnshah1 I did try removing the detect and directly supplying cropped image to `gvainferece` but still the results the same.

IR Facenet model converted using model optimizer supplied with OpenVino: [https://drive.google.com/file/d/1H3Ty8ZEo5_4XNoMUkU7P4FqznhEeXXyL/view?usp=sharing](url)

Original Facenet TF model  in frozen graph .pb format: [https://drive.google.com/file/d/1EXPBSXwTaqrSC0OhUdXNmKSh9qJUQ55-/view](url)

Trained SVM classifier with two classes Joe BIden and Barack Obama in .pkl format: [https://drive.google.com/file/d/1pcUHtiq6fpvItB-eFYsrJxZTyC6aFcYD/view?usp=sharing](url)

Expected flow that I was planning is something like the following:

Input image or frame: 
/home/san/Desktop/datasets/custom/Joe_Biden/Joe_Biden_0005.jpg

face detection  (done via gvadetect)
/home/san/Desktop/datasets/custom_160/Joe_Biden/Joe_Biden_0005.png

input to `gvainference` facenet model is the detected face with dimension 160x160 in RGB that outputs face feature embedding in [1, 512]  dimension.

Using `gvapython` to do post-processing to detect the face based on the embedding and classifier with something like 

```
with open("classifier.pkl", 'rb') as infile:
    (model, class_names) = pickle.load(infile)

def process_frame(frame: VideoFrame, threshold: float = DETECT_THRESHOLD) -> bool:
    for roi in frame.regions():
        for tensor in roi.tensors():
            if tensor.layer_name() == 'embeddings':
                predictions = model.predict_proba([tensor.data()])
                best_class_indices = np.argmax(predictions, axis=1)
                tensor.set_label(class_names[best_class_indices[0]])

    return True
```

**Comment by sanshr** [comment]
@nnshah1 Closing the issue as I just decided with the solution you provided (which uses ArcFace model) and everything is working as expected. Thanks for the help!

**Comment by nnshah1** [comment]
@sanshr Sorry that the facenet model didn't work out - but glad you are unblocked. Please let us know if you need anything else / have issues moving forward.

**Comment by sanshr** [comment]
@nnshah1 : I need to store detected face in disk in .png or .jpg format. Basically, storing detected face. My approach  I applied something like the following:

```
frame_w = frame.video_meta().width
frame_h = frame.video_meta().height
with frame.data() as frame_img:
    frame_img = frame_img.reshape( (frame_h, frame_w, 1)) 
    // croping the image to ROI like this
    // cv::Rect myROI(10, 10, 100, 100);
    // cv::Mat frame_img = frame_img(myROI);
    cv.imwrite("test.png", frame_img)
```

Not sure if this works as I tried just saving the frame as image, I got distorted image in black and white like this:
![Uploading Screenshot from 2021-02-22 17-36-14.png…]()


Height and width are correct. However, it's in black and white.

Examining frame info,
`frame.video_info().finfo.format` is `GST_VIDEO_FORMAT_I420`
`frame.video_info().finfo.pixel_stride` is `[1, 1, 1, 0]`

How would I save region of interest detected photo in `process_frame` function without using jpegenc (video convert) in pipeline?

**Comment by nnshah1** [comment]
The `frame.data()` will return a numpy array with the correct shape for the video format (I420), so you should not have to reshape it. Reshaping it will infact cause the artifacts you are seeing. Try removing the reshape and doing the png save -

**Comment by sanshr** [comment]
@nnshah1 Thank you again for your prompt response. I did try it without reshaping it like this:

```
with frame.data() as frame_img:
                cv.imwrite("/home/san/Desktop/sdw.png", frame_img)
```
Same distorted image got saved. Not sure why though. As, my pipeline is working with all correct inference output.

**Comment by nnshah1** [comment]
What happens when you convert to bgr fcolor space first - and then same the bgr image as png?

```
# Convert YUV420 to BGR (for testing), applies BT.601 "Limited Range" conversion.
    bgr = cv2.cvtColor(yuv, cv2.COLOR_YUV2BGR_I420)
```

**Comment by sanshr** [comment]
It appears to have the same distorted with a color tint on it. 
Result: https://ibb.co/McY39BS

**Comment by nnshah1** [comment]
Can you share the latest pipeline you have? if I get time I can try a few things towards the end of the week

**Comment by sanshr** [comment]
@nnshah1 Hi again! Thank you for the response. I did manage to solve the issue. It was related with the pipeline set up and I have fixed it. I know this is irrelevant to the issue but can you suggest me how I can change  planar 4:2:0 YUV (I420) to RGB? The frame data retrieved with `frame.data()` as numpy 8bit array is in YUV 420 format and saving the array with `cv.imwrite ` causes it to be stored in 8bit grayscale image. Can you advise on how I can save it as rgb image and not grayscale without use of other additional  elements in pipeline such as `videoconvert`? My pipeline is optimized and introduction of other elements especially video convert will likely cause performance issues. Thanks again!

**Comment by sanshr** [comment]
@nnshah1 solved the issue with `COLOR_YUV420p2RGB` instead of `COLOR_YUV2BGR_I420`. Thanks anyway!

**Comment by nnshah1** [comment]
That's great! Glad it glad it got solved. Do you mind adding here your final pipeline - it may help others in the future and we can look to add something similar into our internal testing -
