### ISSUE TITLE
Docker image env variables issue?

### ISSUE THREAD

**Issue by CACUser** [openvinotoolkit/dlstreamer_gst#188]
Hi - I am trying to use this image - https://hub.docker.com/r/openvino/ubuntu18_data_dev as my base image. It does not seem work along with Kafka. I create an image, run the container as a pod in a kubernetes cluster.  If I run gst-launch-1.0 through a python sub process from a python file directly in the container, it works. But if I run it along with kakfa, there seems to be an issue. It cannot find gst-launch-1.0. All the env variables seem to be set. What am I missing? Are the env variables set only when the image is executed?

**Comment by alekseyfa** [comment]
Hi @CACUser,
Could you please share more details about your problem? It would be nice if you provide the error log, Dockerfile, gst pipeline you are using, and how do you run Kafka/docker containers. We will try to reproduce this issue.

**Comment by CACUser** [comment]
Hi @alekseyfa, - I now think this has nothing to do with kafka, but with env variables.
The beginning of my dockerfile looks like this:

FROM openvino/ubuntu18_data_dev

I then run /opt/intel/openvino_2021/bin/setupvars.sh 

While building the docker image I get the following message:
[setupvars.sh] OpenVINO environment initialized

At the end of my dockerFIle I run this:
CMD ["/bin/bash", "-c", "/home/main.py"]

In main.py - I call ( I am using a short gstreamer pipeline for testing.)
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
cmd looks like this: ['gst-launch-1.0', 'filesrc', 'location=/root/videos/crowd_run_m6_5k_265.mp4', '!', 'qtdemux', '!', 'avdec_h265', '!', 'gvafpscounter', '!', 'fakesink', 'async=false']

When the container starts running and the above runs: I get
Error: Failed to execute gstreamer pipeline: [Errno 2] No such file or directory: 'gst-launch-1.0': 'gst-launch-1.0'
((), {})

Then I exec -it into the pod/container. As soon as I exec into the container I see the following output:
[setupvars.sh] OpenVINO environment initialized
I then run the same piece of code as in main.py. This time the gstreamer pipeline runs..
['gst-launch-1.0', 'filesrc', 'location=/root/videos/crowd_run_m6_5k_265.mp4', '!', 'qtdemux', '!', 'avdec_h265', '!', 'gvafpscounter', '!', 'fakesink', 'async=false']
Setting pipeline to PAUSED ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
Redistribute latency...
FpsCounter(1sec): total=432.84 fps, number-streams=1, per-stream=432.84 fps


I tried accessing the env variables like GST_PLUGIN_PATH, OpenCV_DIR etc from the main.py I call in CMD in my dockerfile. These are not found.

But after I exec -it into the container these same env variables are found.

So - most probably problem could be with how I am launching main.py in my container.

Any help would be appreciated.

I also tried  using option#4 - from here - https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide. The docker image does not build - many of the images it uses cannot be pulled down 
Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  Temporary failure resolving 'archive.ubuntu.com'

Thanks!

**Comment by CACUser** [comment]
Update- Fixed by creating a shell script as below:

#!/bin/bash

source /opt/intel/openvino_2021/bin/setupvars.sh
python3 /home/main.py

And running it as ENTRYPOINT in docker:
ENTRYPOINT ["/home/set_env_and_start.sh"]

wonder why the setupvars.sh run during docker build - does not stick or why python cannot see it.
