### ISSUE TITLE
rtpjitterbuffer invoking OOMKiller

### ISSUE THREAD

**Issue by jainricha** [openvinotoolkit/dlstreamer_gst#190]
Hi,

My application gets killed without giving any errors when I see a lot of rtpjitterbuffer in GST_DEBUG logs.

What could be the best way to avoid this happening? How can I control rtpjitterbuffer resource consumption?

Below is my pipeline:
`gst-launch-1.0 decodebin name=depay0 ! videorate ! videoconvert ! video/x-raw,format=BGR ! gvainference model-instance-id={}_fdet model={} no-block=true inference-interval=4 device={} ! queue leaky=downstream ! gvafpscounter ! fakesink
`
Any help will be appreciated.

Thanks

**Comment by mliu2020** [comment]
Hi @jainricha,

Can you share some of the error message?

The other tip is to isolate the error, you can remove all the DL Streamer element and see if the error still generates.

I am trying to reproduce your issue but I am not sure what's the input.

I will also check with dev team and see what they could say.

Mark

**Comment by mliu2020** [comment]
Hi @jainricha,

Do my suggestion helps?

I suggest you try to use GST_DEBUG=3 so you might get error messages.

I have questions from Dev team:
- Do you restart the pipeline in the same process?
- What's the OpenVINO package version?
- Can you share your Model name?
- Your pipeline was abstracted and I can't tell. What input were you using in the pipeline?

Mark Liu

**Comment by mliu2020** [comment]
Hi @jainricha 
Do you have answers to our question or further results?
Mark

**Comment by mliu2020** [comment]
@jainricha 

Let me close this issue for now and feel free to reopen it if you still have the same issue.

Mark
