### ISSUE TITLE
mobilenet-ssd: how to make gvadetect ignore object classes?

### ISSUE THREAD

**Issue by wfchair** [openvinotoolkit/dlstreamer_gst#192]
I'm using mobilenet-ssd to detect object:
gvadetect model=mobilenet-ssd.xml model_proc=mobilenet-ssd.json

It's object classes include cat, dog, horse, person etc, but I'm only interested in dog detection.
how to make gvadetect ignore other classes?

**Comment by mliu2020** [comment]
Hi @wfchair,

You may add a probe function at the source pad of gvadetect to remove the roi which is not dog.

The other feature you can use if you use gvaclassify or gvainference as the follow up element, set inference-region=1 which only infer with ROI list.

Hope this helps.

Mark

**Comment by wfchair** [comment]
Thanks for your reply. Can you recommend a sample? With a sample, it will be more helpful.

**Comment by wfchair** [comment]
https://github.com/wfchair/dlsample/blob/main/filterpub.py

**Comment by wfchair** [comment]
I wrote a sample, although it's for gvametapublish instead of gvadetect.
https://github.com/wfchair/dlsample/blob/main/filterpub.py

You can close this issue.

**Comment by mliu2020** [comment]
@wfchair thanks,

Let me close it.

Mark Liu

**Comment by deep28vish** [comment]
how to implement the same in a GST pipeline:

`gst-launch-1.0 filesrc location=10min_test_helmet.mp4 ! decodebin ! gvadetect model=models_intel/person-vehicle-bike-detection-crossroad-0078/FP16/person-vehicle-bike-detection-crossroad-0078.xml model-proc=model_proc/person-vehicle-bike-detection-crossroad-0078.json ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=autovideosink sync=false`

I just want to detect the 'person' class and don't want BBoxs for the rest of 2 classes.

`gst-launch-1.0 filesrc location=10min_test_helmet.mp4 ! decodebin ! gvadetect model=models_intel/person-vehicle-bike-detection-crossroad-0078/FP16/person-vehicle-bike-detection-crossroad-0078.xml model-proc=model_proc/person-vehicle-bike-detection-crossroad-0078.json object-class=person ! queue ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=autovideosink sync=false`

this pipeline is with using object-class=person.. which doesnt preroll.

Can you please suggest a change in the pipeline.

**Comment by mliu2020** [comment]
@deep28vish,

Sorry for the late response.

Since this issue was closed, it will be easier to be ignored. Could you post a new one?

Mark
