### ISSUE TITLE
gvadetect with Core Pinning

### ISSUE THREAD

**Issue by jainricha** [openvinotoolkit/dlstreamer_gst#194]
Hi,

I am trying to run my pipeline with a gvadetect using device=CPU. My application container the pipeline runs on specific CPU cores using taskset. But in this scenario pipeline gets stuck on detection and nothing happens from there onwards. On trying to end my python application, it shows up like a zombie process while some threads are still stuck:

`root       212     0  0 10:54 ?        00:00:00 [python3.6] <defunct>`

what is wrong while running gvadetect with taskset/core pinning? Please suggest.

**Comment by mliu2020** [comment]
@jainricha,

I want to understand your scenario so:

- Are you using "taskset" in the python callback function in the pipeline?
- Can you post your pipeline? You can remove the model name etc. if you don't want to expose the detail of your product.
- What is "taskset"?

Mark Liu

**Comment by jainricha** [comment]
> @jainricha,
> 
> I want to understand your scenario so:
> 
> * Are you using "taskset" in the python callback function in the pipeline?
> * Can you post your pipeline? You can remove the model name etc. if you don't want to expose the detail of your product.
> * What is "taskset"?
> 
> Mark Liu

Hi @mliu2020 

Yes, I am using taskset for core pinning. The python process launching my pipeline, is invoked from a shell script which I ran using taskset. I verified using taskset -pc <pid> command that the python process is designated to run on specific cores.

Here is my pipeline for your reference (the source of video is a remote machine , sending stream via rtspclientsink:

`decodebin name=depay0 !  videoconvert ! capsfilter caps=\"video/x-raw,format=BGRx\" !  gvadetect model-instance-id={}_tdet model={} model-proc={} no-block=true inference-interval=2 threshold=0.6 device=CPU !    queue flush-on-eos=true !  gvametaconvert format=json add-empty-results=true !  gvametapublish method=mqtt address={}:1884 topic=traffic_stats/{}/{}/traffic !     fakesink`

The taskset I use is : 0xf800f800 

The command I use to run my application shell script is: 
`taskset 0xf800f800 ./myapp.sh &
`

Additionally I have also tried disabled all openvino internal threading with below parameteres of gvadetect config, but it did not seems to help too:

`gvadetect ie-config=CPU_BIND_THREAD=NO,CPU_THREADS_NUM=1,CPU_THROUGHPUT_STREAMS=0 model-instance-id={}_tdet model={} model-proc={} no-block=true inference-interval=2 threshold=0.6 device={} `

 If I remove detection from my pipeline it works fine, but only when gvadetect is present, the pipeline won't run.

Any clue what is causing the pipeline to stuck?

**Comment by adranit** [comment]
Hi @jainricha !
I am most likely wrong, but could you try two options just in case:
1) don't use model-instance-id property of gvadetect
2) set async=false for fakesink element

**Comment by jainricha** [comment]
> Hi @jainricha !
> I am most likely wrong, but could you try two options just in case:
> 
> 1. don't use model-instance-id property of gvadetect
> 2. set async=false for fakesink element

Sure, I will give this a try. I think I already tried async=false, but I will give it another shot. One question though:

Any specific reason that you think, removing model-instance-id can help here?

Thanks.

**Comment by mliu2020** [comment]
@jainricha,

Can you try to remove model-instance-id and see if this resolve the problem?

It seems like the 'taskset' is the only one that is unique in this problem, since you were trying remove threading, does it related with threading? Specifically, does "taskset" will turn off any thread in the application?

Mark Liu

**Comment by jainricha** [comment]
> @jainricha,
> 
> Can you try to remove model-instance-id and see if this resolve the problem?
> 
> It seems like the 'taskset' is the only one that is unique in this problem, since you were trying remove threading, does it related with threading? Specifically, does "taskset" will turn off any thread in the application?
> 
> Mark Liu

I  tried removing internal threading thinking it might have some impact on CPU Core utilization. But the gvadetect issue still persists. I can run the pipeline with model-instance-id if running via device=HDDL. 

I shall try removing model-instance-id for the CPU one and let you know if that helps.

One question:
Does gvadetect spawn any threads which might be getting executed on non-designated cores? Or running with taskset, spawn all threads on only allocated cores?

Thanks.

Thanks.

**Comment by mliu2020** [comment]
@jainricha,

I still don't know what "taskset" is, but I believe this is the direction you decided.

Yes, gvadetect uses asynchonized API of inference engine, this is to utilize the CPU for better throughput. So IE should spawn threads. This is [the actual code](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/gst/inference_elements/base/inference_impl.cpp#L456) for gvadetect to submit the inference request.

If you want to check sync vs. async API of inference engine, you can refer to following simple example:
- This is [the IE sample uses sync API](https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/samples/hello_classification).
- This is [the IE sample uses async API](https://github.com/openvinotoolkit/openvino/tree/master/inference-engine/samples/classification_sample_async).

You can use this samples to check if "taskset" works or not.

Mark

**Comment by mliu2020** [comment]
Hi @jainricha,

Did I answered your following question?

> Does gvadetect spawn any threads which might be getting executed on non-designated cores? Or running with taskset, spawn all threads on only allocated cores?

Basically it is not gvadetect but the inference engine spawn the threads, so if you can duplicate the issue with the sample in my post, it should confirm it.

I read a little bit about taskset and understood a little bit. But I still don't know how this feature affects the existing threads, I believe this is out of the DL Streamer scope.

Let me know if you need further help.

Mark Liu

**Comment by mliu2020** [comment]
Hi @jainricha ,

If you don't have further question, I would conclude this is not DL Streamer issue.

If you don't have further questions, I will close this issue.

Mark

**Comment by mliu2020** [comment]
Thanks @jainricha,

Let me close this issue for now. Feel free to open a new issue.

Mark Liu
