### ISSUE TITLE
Unable to run test-record.c with pipeline I am using in my python application

### ISSUE THREAD

**Issue by goelkirti** [openvinotoolkit/dlstreamer_gst#196]
Hi Team, 

I am referring to the repo https://github.com/GStreamer/gst-rtsp-server/tree/master/examples

I am getting this error on server
1) gcc -o test-launch test-record.c `pkg-config --cflags --libs gstreamer-rtsp-server-1.0`
2)./test-launch -p 7081 filesrc location=Relaxing_highway_traffic_777.mp4 ! decodebin ! x264enc ! fakesink

### After running client, error it shows on server side: 
<b>(test-launch:37329): GLib-GObject-WARNING **: 12:41:21.811: invalid cast from 'GstFileSrc' to 'GstBin'

(test-launch:37329): GStreamer-CRITICAL **: 12:41:21.811: gst_bin_get_by_name: assertion 'GST_IS_BIN (bin)' failed</b>

_### On Client Side: error shows after running the command_

gst-launch-1.0 filesrc location=Relaxing_highway_traffic_777.mp4 ! decodebin ! x264enc ! rtspclientsink location=rtsp://127.0.0.1:7081/test

<b>ERROR: from element /GstPipeline:pipeline0/GstRTSPClientSink:rtspclientsink0: Could not read from resource.
Additional debug info:
../gst/rtsp-sink/gstrtspclientsink.c(3092): gst_rtsp_client_sink_send (): /GstPipeline:pipeline0/GstRTSPClientSink:rtspclientsink0:
Got error response: 415 (Unsupported Media Type).</b>

**Comment by mliu2020** [comment]
@goelkirti,

From your pipeline command, there is no GST element from DL Streamer product. DL Streamer is an GStreamer plugin for Intel OpenVINO inference, targeting on video analytics application framework.

Are your testing or application using our product?

Mark

**Comment by goelkirti** [comment]
@mliu2020 

We are using openvino 2020.2 and original pipeline uses gvadetect

Thanks

**Comment by mliu2020** [comment]
Thanks for using our product,

If this is the problem of gvadetect, I can help you but I can't find it or other DL Streamer elements. The scenario you described seems to be the client problem when you are using RTSP server, this is out of our scope.

From your log, it seems the negotiation problem, I suggest you check the input file by switch to different codec, you can also check if the serversink supports the codec you input.

Sorry I never use this RTSP server sample, you might check if there is other RTSP server examples, like RTSP camera simulator.

Mark

**Comment by mliu2020** [comment]
Hi @goelkirti,

It has been a while and I didn't get your response. As I said, the issue you got seems only related to the GStreamer several script, this is out of our scope.

From your previous comment, you are using DLStreamer as the client of the server. So if you have any question related to DL Streamer elements the pipeline on the client side, feel free to open a new request.

Mark Liu
