### ISSUE TITLE
Size of buffer's data not equal to requested size

### ISSUE THREAD

**Issue by sanzexstha** [openvinotoolkit/dlstreamer_gst#197]
Hello Team,

I am trying to save frame images as: 

``` 
def process_frame(frame: VideoFrame):
    with frame.data() as image:
        rgb = cv2.cvtColor(image, cv2.COLOR_YUV420p2RGB)
        cv2.imwrite(img_path, rgb)
 ```
            
It works well when I supply 360p and 1080p resolution video in the pipeline sample: 

`gst-launch-1.0 filesrc location=sample.mp4 ! decodebin ! gvadetect ! gvapython ! fakesink sync=false`

But saves distorted image when other resolution videos are supplied.

It gives warning that size of buffer's data is greater than the requested size.

How can I fix it? Am I doing it wrong way?

**Comment by sanzexstha** [comment]
Hi @mliu2020,

When I supply 640x360 resolution video in following pipeline: 
```
gst-launch-1.0 filesrc location=sample.mp4 ! decodebin ! \
gvadetect model=/home/sanzex/intel/dl_streamer/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml device=$DEVICE ! queue ! \
gvapython module=$PYTHON_SCRIPT1 ! \
fakesink sync=false"!
```
Image saved (numpy array to image without color conversion), resolution: 640x540=(640x(360x1.5))=requested size=345600 = size of buffer's data
![sar2](https://user-images.githubusercontent.com/41791327/111726820-c152da00-8891-11eb-831e-32268941319e.jpg)

With Color Conversion, resolution: 640x360
![sar3](https://user-images.githubusercontent.com/41791327/111726851-d0398c80-8891-11eb-8d94-71d0af550496.jpg)

854x480 resoulution video, 
image saved resoultion: 854x480,  requested size = 854x480x1.5=614880, but size of buffer'data = 616320
![sar2](https://user-images.githubusercontent.com/41791327/111729188-9fa82180-8896-11eb-9caa-9f832143fd5d.jpg)
![sar3](https://user-images.githubusercontent.com/41791327/111729199-a6369900-8896-11eb-9ee2-bac3657b7978.jpg)

When supplied 1280x720 resolution video, 
image(without color conversion) saved resolution: 1280x720
requested size=1280x720x1.5=1382400, buffer's data size = 1596672
![sar2](https://user-images.githubusercontent.com/41791327/111727001-1b539f80-8892-11eb-9cf1-cf2cfb979521.jpg)
with color conversion
![sar3](https://user-images.githubusercontent.com/41791327/111727056-40481280-8892-11eb-9835-25a2db039188.jpg)

**Comment by mliu2020** [comment]
@sanzexstha,

Could you try to add following elements between decodebin and gvadetect and see if it solves your problem?
videoconvert ! capsfilter caps=\"video/x-raw,format=I420\" !

Mark Liu

**Comment by ymaskina** [comment]
Hi @sanzexstha,

It looks like that `cv::imwrite()` has no info about frame strides.
In some cases decoder can add strides to frame for optimization purposes (this is the expected behavior), so the buffer size increases. As far as I know this behavior is more typical for YUV formats, so you can try to insert in your pipeline `videoconvert ! video/x-raw,format=BGRx` after `decodebin`.
Another way is to construct `cv::Mat` from `frame.data()` using information from `frame.video_info()` (image width, height, channels, strides, etc.) and then dump it with `cv::imwrite()`. I think if cv::Mat contains information about strides, dumped image will be correct.

**Comment by sanzexstha** [comment]
Hi @ymaskina @mliu2020,

I tried adding videconvert with format BGRx instead of I420, frame images were saved without distortion in all standard resolution. I also tried with NV12 format, it worked in all except 854x480.

Thank you so much for your help @mliu2020, @ymaskina
