### ISSUE TITLE
DLStreamer on Windows

### ISSUE THREAD

**Issue by vt911001** [openvinotoolkit/dlstreamer_gst#198]
Hi,

I have looked at the latest OpenVINO 2021.3 Release Notes and found out that there is a **_preview/support-for-windows_** branch but I cant seems to find it.
Is the branch still active?

Vincent

**Comment by adranit** [comment]
Hi Vincent,
Sorry for delay in publishing the preview branch. Now it is available.
https://github.com/openvinotoolkit/dlstreamer_gst/tree/preview/support-for-windows

**Comment by vt911001** [comment]
Hi Anton,

Thanks a lot for your help.

Vincent
