### ISSUE TITLE
preview-windows-support

### ISSUE THREAD

**Issue by shardul-sathe** [openvinotoolkit/dlstreamer_gst#203]
I am getting an error in the Option1 - Step1 on Windows10 system:
git clone -b preview/windows-support https://github.com/openvinotoolkit/dlstreamer_gst.git %USERPROFILE%\intel\dlstreamer_gst
Cloning into <name_of_dir>...
**fatal: Remote branch preview/windows-support not found in upstream origin**

(git version 2.31.1.windows.1)

systeminfo:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363

I would like to install DL Streamer on windows (native).  How to resolve this issue?

**Comment by adranit** [comment]
Hi @shardul-sathe ,
There is an error in the instruction - wrong branch name is used in the command line.

git clone -b **preview/support-for-windows** https://github.com/openvinotoolkit/dlstreamer_gst.git %USERPROFILE%\intel\dlstreamer_gst

Thank you for reporting the issue, we'll update the instruction.

**Comment by adranit** [comment]
fixed
