### ISSUE TITLE
How to overwrite gvatrack object ids?

### ISSUE THREAD

**Issue by AhmedHisham1** [openvinotoolkit/dlstreamer_gst#205]
Hello,
I want to overwrite the given ids of each detection. I tried the following code inside a python probe callback function, but later probes have a fluctuating value for the changed id which do not even match the id given by neither the tracker nor myself.

```python
def foo(frame):
    for roi in frame.regions():
        if roi.label() == "person":
            param = roi.meta()._params
            while param:
                t = Tensor(param.contents.data)
                if t.name() == 'object_id':
                    if self.new_ids:
                        t['id'] = int(the new id)

                param = param.contents.next
```
I figured this might work after I saw #69 answers.

What is the correct way to do this in python?

**Comment by mliu2020** [comment]
Hi @AhmedHisham1,

Could you check [this document](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Object-tracking) about "object_id" and see if it is helpful? I think this might mean we have implemented the feature mentioned in #69 

I read through your code and I think there might be 2 errors:
1. t['id'] should be t['object_id']
2. After "if self.new_ids:" should you break out the loop?

Mark

**Comment by AhmedHisham1** [comment]
The document describes how to read the object_id given by gvatrack by "roi.object_id()" but does not say how to overwrite this value. 
1. if you check the fields of the t tensor by print(t.fields()) before doing anything, it return ['id'] so I think this is the correct key rather than "object_id', right? I tried t['object_id'] = some number, but it doesn't affect the object id by any means. At least t['id'] causes this fluctuation in object_id value in later prob callbacks, but t['object_id'] does nothing.
2. I added a break after it but the issue is still there.

**Comment by AhmedHisham1** [comment]
If you can provide a Python example on how to correctly overwrite this value, that would be great.

**Comment by mliu2020** [comment]
Hi @AhmedHisham1,

We tried this issue with the following pipeline but can't reproduce:
`gst-launch-1.0 filesrc location=head-pose-face-detection-female-and-male.mp4 ! decodebin ! gvadetect model=face-detection-adas-0001.xml device=CPU ! queue ! gvatrack tracking-type=zero-term ! queue ! gvapython module=ssd_object_detection.py ! gvawatermark ! videoconvert ! fpsdisplaysink video-sink=ximagesink sync=false`

In the Python callback (ssd_object_detection.py):
```
def process_frame(frame: VideoFrame, threshold: float = DETECT_THRESHOLD) -> bool:
    for roi in frame.regions():
        param = roi.meta()._params
        while param:
            t = Tensor(param.contents.data)
            if t.name() == 'object_id':
                t['id'] = 4
            param = param.contents.next
    return True
```


As a result I see bounding boxes with overwritten id equals 4.

Can you provide us with the pipeline you run?
Could you also make sure something after gvapython didn't modify object id? You might try to remove some element as a check.

Mark

**Comment by AhmedHisham1** [comment]
Thanks for replying, it works now. This was a logic error on my end. I will close this issue now. However, I recommend adding a direct method for changing/overwriting the object id in future releases. Thanks.
