### ISSUE TITLE
Failed to construct OpenVINOImageInference: Config for layer precision does not contain precision info for layer: head_pose_angles

### ISSUE THREAD

**Issue by sonln5** [openvinotoolkit/dlstreamer_gst#212]
I'm trying to build an python gstreamer application as the bellow c++ example:
https://docs.openvinotoolkit.org/latest/omz_demos_gaze_estimation_demo_cpp.html
This example use: face-detection-retail-0004 or face-detection-adas-0001 , head-pose-estimation-adas-0001, facial-landmarks-35-adas-0002 , open-closed-eye-0001 and gaze-estimation-adas-0002.
- Firstly, I was converted the open-closed-eye-0001 from .ONNX to openvino format
- Then I create a gstreamer pipeline like: 
**filesrc** location={file_location} ! **decodebin** ! queue ! **videoconvert** ! video/x-raw,format=BGRx ! **gvadetect** model=face-detection-adas-0001/FP32/**face-detection-adas-0001.xml** model-proc=models/face-detection-adas-0001/PROC/face-detection-adas-0001.json device=CPU ! **gvatrack** ! queue ! **gvaclassify** reclassify-interval=5 model=models/head-pose-estimation-adas-0001/FP32/**head-pose-estimation-adas-0001.xml** device=CPU batch-size=1 pre-process-backend=opencv object-class=face ! queue ! **gvaclassify** reclassify-interval=5 model=models/facial-landmarks-35-adas-0002/FP32/**facial-landmarks-35-adas-0002.xml**  device=CPU batch-size=1 pre-process-backend=opencv object-class=face ! queue ! **gvaclassify** reclassify-interval=5 model=models/open-closed-eye-0001/FP32/**open-closed-eye-0001.xml** device=CPU batch-size=1 pre-process-backend=opencv object-class=face ! queue ! **gvaclassify** reclassify-interval=5 model=models/gaze-estimation-adas-0002/FP32/**gaze-estimation-adas-0002.xml** device=CPU batch-size=1 pre-process-backend=opencv object-class=face ! queue ! **videoconvert** name=videoconvert ! **autovideosink** name=autovideosink
- When starting the pipeline, I got an error: 
**ERROR:Pipeline has error gst-library-error-quark: base_inference plugin intitialization failed (3)
Debug detail: /app/dl-streamer/gst/inference_elements/base/inference_singleton.cpp(136): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaClassify:gvaclassify3:
Failed to construct OpenVINOImageInference
	Config for layer precision does not contain precision info for layer: head_pose_angles**

Thanks anh Best Regards,
Ngoc Son, Luong (Eric)

**Comment by mliu2020** [comment]
Hi @sonln5,

This seems like an initialization error when DL Streamer [made requests](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/gst/inference_elements/base/inference_singleton.cpp#L136) to Inference Engine which might require some addition information or missing some layer support. To understand which model cause the problem, could you remove model "gaze-estimation-adas-0002" or "open-closed-eye-0001" or both to see if the error still exists? The other models are the same as our sample, so they should be OK

Do you check our [face_draw_attribute sample](https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples/python/draw_face_attributes)? This sample uses 3 models which are the same as yours. You can also extend it with two models in your prototype and see if it generates an error.

Mark

**Comment by sonln5** [comment]
Hi @mliu2020 
I've already tried with the face_draw_attribute sample and it was OK. I also run [](url)

> Hi @sonln5,
> 
> This seems like an initialization error when DL Streamer [made requests](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/gst/inference_elements/base/inference_singleton.cpp#L136) to Inference Engine which might require some addition information or missing some layer support. To understand which model cause the problem, could you remove model "gaze-estimation-adas-0002" or "open-closed-eye-0001" or both to see if the error still exists? The other models are the same as our sample, so they should be OK
> 
> Do you check our [face_draw_attribute sample](https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples/python/draw_face_attributes)? This sample uses 3 models which are the same as yours. You can also extend it with two models in your prototype and see if it generates an error.
> 
> Mark

**Comment by sonln5** [comment]
> Hi @sonln5,
> 
> This seems like an initialization error when DL Streamer [made requests](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/gst/inference_elements/base/inference_singleton.cpp#L136) to Inference Engine which might require some addition information or missing some layer support. To understand which model cause the problem, could you remove model "gaze-estimation-adas-0002" or "open-closed-eye-0001" or both to see if the error still exists? The other models are the same as our sample, so they should be OK
> 
> Do you check our [face_draw_attribute sample](https://github.com/openvinotoolkit/dlstreamer_gst/tree/master/samples/python/draw_face_attributes)? This sample uses 3 models which are the same as yours. You can also extend it with two models in your prototype and see if it generates an error.
> 
> Mark

Hi @mliu2020 
Thanks for your answer.
I've already tried with the face_draw_attribute sample and it was OK. I also run the [cpp example](https://docs.openvinotoolkit.org/latest/omz_demos_gaze_estimation_demo_cpp.html) successfully. But when I put the gaze_estimation_0002 model to my gstreamer pipeline. it still got the error as before. I'm debugging on the dlstreamer source code to figure out when we got **'Config for layer precision does not contain precision info...'** error.
Thanks and Best Regards

**Comment by mliu2020** [comment]
@sonln5,

This is more an OpenVINO question than a DL Streamer question.

I am not an inference engine expert but I guess, your model has a layer precision, it is missing the precision info like FP32, etc. So it seems your model have some issue.

A quick check is to run the same application in OpenVINO demos.

Mark

**Comment by sonln5** [comment]
Dear @mliu2020 
I've already run the [OpenVINO example](https://docs.openvinotoolkit.org/latest/omz_demos_gaze_estimation_demo_cpp.html) successfilly.

**Comment by mliu2020** [comment]
@sonln5 ,

Sorry for the late response, I have checked with dev team.

Here is the analysis from dev team: 
The Gaze Estimation demo is more complicated than our current design. Because it requires to calculate eye regions and pass separately left and right eye images according to gaze-estimation-adas-0002 model inputs. We don’t support such use case right now, so this pipeline won’t work.

The other requirement is, gaze-estimation-adas-0002 model has three inputs, we don’t know which one is for what data so application needs to provide ‘model-proc’ file with description of these input layouts (format, precision, etc.) as expected. But since current function doesn't support such many inputs, the pipeline still doesn't work even if model-proc file is provided.

Mark Liu

**Comment by mliu2020** [comment]
Hi @sonln5,

Do you have any feedback to our answers? Let me know if you want this to be a feature request.

Or if you don't have further questions, I will close it.

Mark

**Comment by mliu2020** [comment]
Hi @sonln5 ,

Let me close this for now and feel free to open new issue.

Mark
