### ISSUE TITLE
Error audio sample app - Got EOS from element "pipeline0"

### ISSUE THREAD

**Issue by antoniomtz** [openvinotoolkit/dlstreamer_gst#214]
Hello,

I was able to build and run the DL streamer audio sample app and I'm getting this message and no output is generated.
I tried this on locahost with openVINO 2021.3, and also on openvino/ubuntu18_data_runtime:latest and  openvino/ubuntu20_data_runtime:latest docker containers.

Any ideas?

Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
**Got EOS from element "pipeline0".**
Execution ended after 0:00:00.052957385
Setting pipeline to PAUSED ...
Setting pipeline to READY ...

Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by mliu2020** [comment]
Hi @antoniomtz,

What was the input file? Can you share your full pipeline command?

The other useful tool for investigation is to set GST_DEBUG=3 at least to see the error messages:
https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c

Mark

**Comment by antoniomtz** [comment]
Hello @mliu2020 ,

I'm running the sample audio file from openVINO which includes an audio file.
This is the command:
```
gst-launch-1.0 filesrc location=how_are_you_doing.wav ! decodebin ! audioresample ! audioconvert ! audio/x-raw, channels=1,format=S16LE,rate=16000 ! audiomixer output-buffer-duration=100000000 ! gvaaudiodetect model=/home/antonio/intel/dl_streamer/models/audio_models/aclnet/FP32/aclnet.xml model-proc=./model_proc/aclnet.json sliding-window=0.2 ! gvametaconvert ! gvametapublish file-format=json-lines ! fakesink
```

**Comment by adranit** [comment]
Hi @antoniomtz ,
Could you verify that model_proc file for aclnet contains the following fix? https://github.com/openvinotoolkit/dlstreamer_gst/commit/4a8b37a81b4f8362899d3521bcabe5ecaec97014#diff-690de75ea210e7d36ad143ef356375f3931f2653dc520112d57b8cdc49baea7e

**Comment by mliu2020** [comment]
@antoniomtz,

Can you confirm on @adranit's suggested patch?

You might either try the same script on the latest 2021.4 release and see if this was fixed.

Mark

**Comment by mliu2020** [comment]
Hi @antoniomtz,

If you are no long looking into this issue, would you mind if I close this issue?

Mark

**Comment by antoniomtz** [comment]
@mliu2020 @adranit it worked. However, the output from the sample audio app is not accurate. The sample audio app from openVINO uses an audio file with the speech "How are you doing".

> gst-launch-1.0 filesrc location=how_are_you_doing.wav ! decodebin ! audioresample ! audioconvert ! audio/x-raw, channels=1,format=S16LE,rate=16000 ! audiomixer output-buffer-duration=100000000 ! gvaaudiodetect model=/home/antonio/intel/dl_streamer/models/audio_models/aclnet/FP32/aclnet.xml model-proc=./model_proc/aclnet.json sliding-window=0.2 ! gvametaconvert ! gvametapublish file-format=json-lines ! fakesink
> Setting pipeline to PAUSED ...
> Pipeline is PREROLLING ...
> Pipeline is PREROLLED ...
> Setting pipeline to PLAYING ...
> New clock: GstSystemClock
> {"channels":1,"events":[{"detection":{"confidence":0.7,"label":"Can opening","label_id":35,"segment":{"end_timestamp":1000000000,"start_timestamp":0}},"end_timestamp":1000000000,"event_type":"Can opening","start_timestamp":0}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":0.67,"label":"Cow","label_id":4,"segment":{"end_timestamp":1200000000,"start_timestamp":200000000}},"end_timestamp":1200000000,"event_type":"Cow","start_timestamp":200000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":0.99,"label":"Speech","label_id":53,"segment":{"end_timestamp":1400000000,"start_timestamp":400000000}},"end_timestamp":1400000000,"event_type":"Speech","start_timestamp":400000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":1.0,"label":"Speech","label_id":53,"segment":{"end_timestamp":1600000000,"start_timestamp":600000000}},"end_timestamp":1600000000,"event_type":"Speech","start_timestamp":600000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":1.0,"label":"Speech","label_id":53,"segment":{"end_timestamp":1800000000,"start_timestamp":800000000}},"end_timestamp":1800000000,"event_type":"Speech","start_timestamp":800000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":1.0,"label":"Speech","label_id":53,"segment":{"end_timestamp":2000000000,"start_timestamp":1000000000}},"end_timestamp":2000000000,"event_type":"Speech","start_timestamp":1000000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":1.0,"label":"Speech","label_id":53,"segment":{"end_timestamp":2200000000,"start_timestamp":1200000000}},"end_timestamp":2200000000,"event_type":"Speech","start_timestamp":1200000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":1.0,"label":"Speech","label_id":53,"segment":{"end_timestamp":2400000000,"start_timestamp":1400000000}},"end_timestamp":2400000000,"event_type":"Speech","start_timestamp":1400000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":1.0,"label":"Speech","label_id":53,"segment":{"end_timestamp":2600000000,"start_timestamp":1600000000}},"end_timestamp":2600000000,"event_type":"Speech","start_timestamp":1600000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":1.0,"label":"Speech","label_id":53,"segment":{"end_timestamp":2800000000,"start_timestamp":1800000000}},"end_timestamp":2800000000,"event_type":"Speech","start_timestamp":1800000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":1.0,"label":"Speech","label_id":53,"segment":{"end_timestamp":3000000000,"start_timestamp":2000000000}},"end_timestamp":3000000000,"event_type":"Speech","start_timestamp":2000000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":0.99,"label":"Speech","label_id":53,"segment":{"end_timestamp":3200000000,"start_timestamp":2200000000}},"end_timestamp":3200000000,"event_type":"Speech","start_timestamp":2200000000}],"rate":16000}
> {"channels":1,"events":[{"detection":{"confidence":0.99,"label":"Speech","label_id":53,"segment":{"end_timestamp":3400000000,"start_timestamp":2400000000}},"end_timestamp":3400000000,"event_type":"Speech","start_timestamp":2400000000}],"rate":16000}
> Got EOS from element "pipeline0".
> Execution ended after 0:00:00.138420280
 
Can you guide me how to translate this json message into the actual speech? 

> {"channels":1,"events":[{"detection":{"confidence":0.99,"label":"Speech","label_id":53,"segment":{"end_timestamp":1400000000,"start_timestamp":400000000}},"end_timestamp":1400000000,"event_type":"Speech","start_timestamp":400000000}],"rate":16000}

**Comment by mliu2020** [comment]
@antoniomtz,

The output should be expected. You misunderstood the purpose of the model, it is used to detect the kind of the sound, not to generate the transcript of the speech.

Mark Liu

**Comment by antoniomtz** [comment]
That's what I assumed afterwards. 
However, the sample hello wav file confused me a little bit. I was expecting to see "How are you doing" as the output.

Other than that, the ticket can be closed now. Thank you.

**Comment by mliu2020** [comment]
Yes, I agree.

I have the same experience, we should either supply a new sound track or describe it explicitly. 

Mark
