### ISSUE TITLE
How to change bbox line color?

### ISSUE THREAD

**Issue by wfchair** [openvinotoolkit/dlstreamer_gst#218]
When use gva pipeline ssd detection:
gvadetect model=./face-detection-adas-0001/FP16-INT8/face-detection-adas-0001.xml
the output bounding box was rendered with fixed color.

Can I change the bbox line color with other different color, e.g., by changing model-proc output_postproc?

**Comment by mliu2020** [comment]
Hi @wfchair,

If you check the sample code, the rendering code is at the frame call back function. For example, in ~/sample/python/draw_face_attribute, the pipeline was setup at the draw_face_attribute.py function where you can find the render operation there.

You might change the color of bbox or text in [the frame call back function](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/python/draw_face_attributes/draw_face_attributes.py#L38) which was attached to the gvawatermark src pad.

Let me know if this helps.

Mark

**Comment by mliu2020** [comment]
Hi @wfchair,

Did my answer solve your problem?

Mark

**Comment by wfchair** [comment]
Thanks for your hint.
