### ISSUE TITLE
filesink issue in ubuntu18_data_dev container for 2021.4

### ISSUE THREAD

**Issue by ojjsaw** [openvinotoolkit/dlstreamer_gst#221]
Using DLStreamer to save output of the pipelines, there seems to be no x264enc (CPU/SW) or vaapi264enc in the ubuntu18_data_dev. I am hoping to run any DLStreamer samples that can export to video file using any possible encoding. As per the documentation hoping to leverage ubuntu18_data_dev as a base image to run dlstreamer samples.

For older 2020 versions this used to work, but the 2021 images don't seem to have this capability anymore.

![vaapi264enc-error](https://user-images.githubusercontent.com/2703543/126888854-24277b36-eb7a-498b-af7c-9e69cbdafd6c.PNG)
![x264enc](https://user-images.githubusercontent.com/2703543/126888855-e43b5072-878d-4811-800f-86fff1465951.PNG)

**Comment by mliu2020** [comment]
Hi @ojjsaw,

Could you do a quick check with "gst-inspect-1.0 vaapi"? "x264enc" is included in the standard GST distribution but not in OV releases. "vaapih264enc" isn't included by default but it can be installed by running "<install_dir>/install_dependencies/install_openvino_dependencies.sh", if it is not included in the docker image, you can find it [here](https://github.com/openvinotoolkit/openvino/tree/master/scripts/install_dependencies).

Mark Liu

**Comment by adranit** [comment]
Hi @ojjsaw ,
x264enc element has got license limitations so it is not included. 
vaapih264e should be included.
Could you provide output of the following command?  _gst-inspect-1.0 vaapi_
What command do you use to run the docker image?

**Comment by ojjsaw** [comment]
@adranit  see attached. What would you suggest then as recommended encoder to demonstrate file outputs utilizing dlstreamer that don't have licensing issues in containers?
@mliu2020  Hi Mark, this is Ojas here..  as per docs openvino 2021 and above data_dev don't require that script, i still ran it from the container and gst-inspect still failed to find vaapi264enc.
![image](https://user-images.githubusercontent.com/2703543/127249003-ffcca931-e1f2-4d56-b529-02a102450f3e.png)

**Comment by mliu2020** [comment]
Hi @ojjsaw,

What is your host device? I have a concern if you have GPU on it, you can check it by "vainfo".

I had a direct local host installation, the GST_PLUGIN_PATH is <openvino_dir>/data_processing/dl_stramer/lib and <openvino_dir>/data_processing/gstreamer/lib/gstreamer-1.0/

Let me check ubuntu18_data_dev on my side.

Mark

**Comment by mliu2020** [comment]
Hi @ojjsaw,

I checked docker image ubuntu18_data_dev, I can get 16 elements without issue. And I can run a pipeline with a filesink to write.

So I think you might have an environment issue, the docker image requires the video driver to be installed on host device.

Mark

**Comment by brmarkus** [comment]
Can you provide the output of `lspci | grep VGA`, please? This should indicate whether you have a GPU and which variant you have; maybe you don't have an Intel GPU (embedded or discrete), maybe you have a very old GPU model.

I can see something exactly the same on an Intel CPU Desktop computer, which doesn't have an Intel GPU (but from another silicon manufacturer): 0 features and no vaapi encoding plugins. But the plugin is installed (you can see the "Filename" pointing to the SharedObject file).

Inside the container, can you first delete the gstreamer registry cache via `rm -rf ~/.cache/gstreamer-1.0/` and then run `gst-inspect-1.0 | grep vaapi`, please? You might see error messages, you might even see gstreamer to blacklist certain plugins due to problems probing them.

**Comment by ilya-naumov** [comment]
Hi @ojjsaw,
Are you running the image on Linux host? What command do you use to run the docker image?
Maybe you need to add the `--device /dev/dri:/dev/dri` parameter to `docker run`:
```
docker run -it -u 0 --device /dev/dri:/dev/dri openvino/ubuntu18_data_dev:2021.4
```

**Comment by ojjsaw** [comment]
@ilya-naumov @brmarkus @mliu2020 yup.. my iGPU driver is not installed properly on my ubuntu20 rocketlake - failing to mount thus failing to expose the VAAPI in the container. You can close this issue as it's on my side. 

**Secondary question:** I learned from above due to x264 license limitations, the plugin is removed, what alternate SW encoding is recommended for saving video files with dlstreamer in data_dev container? For now - resorted to using avenc_mpeg4 (which is pre-installed in the container)

**Comment by mliu2020** [comment]
Hi @ojjsaw,

I hope avenc_mpeg4 could work; I used x264enc before by installing a standard 16.2 distribution and add it to GST_PLUGIN_PATH. This could be useful for Xeon platform, but I didn't try OV2021.4 yet since it has GST 1.18.x now.

Mark

**Comment by mliu2020** [comment]
Hi @ojjsaw,

Did you solved this problem with out answers?

If no more questions, could I close this?

Mark

**Comment by mliu2020** [comment]
Hi @ojjsaw,

Let me close it for now and feel free to post new issues.

Mark Liu
