### ISSUE TITLE
Question: is it possible to combine multiple gvadetect and gvaclassify into one pipeline?

### ISSUE THREAD

**Issue by antoniomtz** [openvinotoolkit/dlstreamer_gst#226]
Hello,

I'm trying to create a pipeline where I do people detection -> Face detection -> Age/gender recognition as follows:
```
gst-launch-1.0 filesrc location=./videos/face-demographics-walking-and-pause.mp4 \
! decodebin ! gvadetect model=./person-detection-0200/person-detection-0200.xml \ 
! gvadetect model=./face-detection/face-detection-retail-0004.xml \
! gvaclassify model=./age/age-gender-recognition-retail-0013.xml model-proc=/opt/intel/openvino_2021/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/age-gender-recognition-retail-0013.json \
! gvametaconvert json-indent=4 \
! gvametapublish method=file file-path=./tmp/face.json \
! gvawatermark ! xvimagesink
```
However, the age-gender recognition takes both (people detection and age/gender recognition) as input.
Is it possible to tell **gvaclassify** to only use the input from face detection? or should I be creating two different pipelines for that purpose?

Thanks

**Comment by adranit** [comment]
Hi @antoniomtz ,
You can use object-class property of gvaclassify element(please refer to the [sample](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/gst_launch/vehicle_pedestrian_tracking/vehicle_pedestrian_tracking.sh#L78)).


gst-launch-1.0 filesrc location=./videos/face-demographics-walking-and-pause.mp4 \
! decodebin ! gvadetect model=./person-detection-0200/person-detection-0200.xml \ 
! gvadetect model=./face-detection/face-detection-retail-0004.xml **model-proc=face-detection-retail-0004.json** \
! gvaclassify model=./age/age-gender-recognition-retail-0013.xml model-proc=/opt/intel/openvino_2021/data_processing/dl_streamer/samples/gst_launch/face_detection_and_classification/model_proc/age-gender-recognition-retail-0013.json **object-class=face** \
! gvametaconvert json-indent=4 \
! gvametapublish method=file file-path=./tmp/face.json \
! gvawatermark ! xvimagesink

Model-proc file for the face detection model: https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/model_proc/intel/object_detection/face-detection-retail-0004.json

**Comment by antoniomtz** [comment]
@adranit Excellent, it worked!

**Comment by antoniomtz** [comment]
Closing this issue.
