### ISSUE TITLE
Error Building 1.5.1 with Opensource OpenVINO

### ISSUE THREAD

**Issue by dpatel257** [openvinotoolkit/dlstreamer_gst#227]
### System information (version)
OpenVINO=> 2021.4
Operating System / Platform => U 18.04

### Detailed description
Getting error while building dlstreamer_gst (1.5.1) with Open Source OpenVINO 2021.4(https://github.com/openvinotoolkit/openvino)
Installation cannot find ngraph:
```
--   Found gstreamer-1.0, version 1.19.1
CMake Error at /usr/local/openvino/inference-engine/share/InferenceEngineConfig.cmake:36 (message):
  File or directory /usr/local/openvino/inference-engine/../ngraph/cmake
  referenced by variable _ngraph_dir does not exist !
Call Stack (most recent call first):
  /usr/local/openvino/inference-engine/share/InferenceEngineConfig.cmake:124 (set_and_check)
  CMakeLists.txt:48 (find_package)
  gst/preview_elements/common/CMakeLists.txt:13 (find_IE_package)
```
Is dlstreamer_gst tested with opensource OpenVINO ?

### Steps to reproduce
Install Dldt 2021.4 (https://github.com/openvinotoolkit/openvino)
Install gst-video-analytics 1.5.1

**Comment by mliu2020** [comment]
@dpatel257,

Did you try @adranit 's suggestions and got succeed?

Mark Liu

**Comment by dpatel257** [comment]
Hello @mliu2020  Yes, thanks for checking

**Comment by mliu2020** [comment]
Thanks for the quick response,

This is good confirmation and let me close this issue.

Feel free to post if you have new issues.

Mark Liu
