### ISSUE TITLE
Build issue on RaspberryPI

### ISSUE THREAD

**Issue by nikparmar** [openvinotoolkit/dlstreamer_gst#235]
Hi Team,

I am trying to build on Raspberry PI 4 following the steps mentioned [here](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Install-Guide#install-on-host-machine). I am attaching the logs for both `cmake ..` & `make -j8` .
[cmake_output.txt](https://github.com/openvinotoolkit/dlstreamer_gst/files/7246369/cmake_output.txt)
[make_output.txt](https://github.com/openvinotoolkit/dlstreamer_gst/files/7246371/make_output.txt)

Also, I upgraded the Gstreamer to version 1.18.4

**Comment by nikparmar** [comment]
> @nikparmar Which version of OpenVINO package did you use? Is it data_dev or runtime?

Hey there is only 1 version available for Raspberry PI -> https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.4.1/l_openvino_toolkit_runtime_raspbian_p_2021.4.689.tgz

**Comment by ymaskina** [comment]
@nikparmar Can you please share cmake/make_output.txt with  -DENABLE_ITT=OFF option?

**Comment by adranit** [comment]
@nikparmar , it looks like the issue is not actual.
