### ISSUE TITLE
Does dl streamer support yolov4-tiny model?

### ISSUE THREAD

**Issue by IvanZhangDoIt** [openvinotoolkit/dlstreamer_gst#237]
we trained a yolov4-tiny model and used model_proc of yolo-v3-tiny-tf.json from https://github.com/openvinotoolkit/dlstreamer_gst/wiki/Supported-Models. But the location bbox width is pretty wider. 
Does dl streamer support yolov4-tiny, how can we write the model_proc file?

**Comment by dsmertin** [comment]
Hi @IvanZhangDoIt !

We created tutorial about how to create model-proc file. And there we show how to define yolo-v4-tiny post-processing.
https://github.com/openvinotoolkit/dlstreamer_gst/wiki/How-to-create-model-proc-file#output_postproc-

If you are saying your bboxes are looking weird, then I propose take attention on this:
> Let's moving on. Model's output description says that it is necessary to apply the sigmoid functions to the output values. Also we replaced the sigmoid call with softmax to distribute the confidence values of the classes. This can be configured with "output_sigmoid_activation": true and "do_cls_softmax": true fields.

Please tell me if it is helpful.

Regards,
Dmitry

**Comment by jperezmedina** [comment]
Hello, I have the same issue. I tested with the yolo-v4-tiny-tf.json file example at https://github.com/openvinotoolkit/dlstreamer_gst/wiki/How-to-create-model-proc-file#output_postproc- but I dont obtain any detection. Thanks in advance for any suggestion. Best regards!

**Comment by adranit** [comment]
@IvanZhangDoIt , did you manage to write model_proc file for used model?

**Comment by IvanZhangDoIt** [comment]
@adranit , thanks, now it works well.
