### ISSUE TITLE
probe_callback can modify the frame_buffer or not?

### ISSUE THREAD

**Issue by wdkwyf** [openvinotoolkit/dlstreamer_gst#244]
Hi, I want to add the custom pre-process before gvainference element with the pad probe method.
From these docs, we know something like add_region function to modify the metadata of tensor, which is useful for post-processing.

However, as for pre-processing, I wonder whether the modification of buffer will also take effect when I modify the frame caps.
If so, could you please provide some sample code?

For example: buffer is type of Gst.Buffer
```
with util.GST_PAD_PROBE_INFO_BUFFER(info) as buffer:
  caps = pad.get_current_caps()
  # modify the buffer here
return Gst.PadProbeReturn.OK
```

**Comment by wdkwyf** [comment]
Notice the [gstreamer document](https://gstreamer.freedesktop.org/documentation/application-development/advanced/pipeline-manipulation.html?gi-language=c#data-probes) said it's possible to modift gstbuffer in the probe callback. Not sure whether the python bindings in dl streamer can support it.
![image](https://user-images.githubusercontent.com/7670749/140475123-e7e343ae-1f78-418a-85d8-b65ecc535611.png)

**Comment by nnshah1** [comment]
@wdkwyf It is definitely possible to modify the buffer contents (you need to map the buffer). You can see this here:

https://github.com/openvinotoolkit/dlstreamer_gst/blob/747878fe2de3380fab7f4a5a4932623aaf1622a8/samples/python/draw_face_attributes/draw_face_attributes.py#L38 

However what is trickier would be to change the caps of the frame (i.e. change the size, change the color space) - that requires triggering a re-negotiation of the caps of downstream elements. I know in general that its possible but don't have an example ready and would bear further investigation.

**Comment by wdkwyf** [comment]
> @wdkwyf It is definitely possible to modify the buffer contents (you need to map the buffer). You can see this here:
> 
> https://github.com/openvinotoolkit/dlstreamer_gst/blob/747878fe2de3380fab7f4a5a4932623aaf1622a8/samples/python/draw_face_attributes/draw_face_attributes.py#L38
> 
> However what is trickier would be to change the caps of the frame (i.e. change the size, change the color space) - that requires triggering a re-negotiation of the caps of downstream elements. I know in general that its possible but don't have an example ready and would bear further investigation.

@nnshah1 Thanks for your confirmation. In fact, we need to do padding operation, with the right padding is 20pix, left, bottom and top padding is 0.
Because the model-proc only supprot the symmetric padding, so I thought I need to modify something in dl streamer.
However, I found we can use the videobox plugin to do the similar task. 
![image](https://user-images.githubusercontent.com/7670749/140702001-739040ba-3f8a-442c-abce-8fc3a3379765.png)
