### ISSUE TITLE
How to convert the custom build model to IR format?

### ISSUE THREAD

**Issue by divdaisymuffin** [openvinotoolkit/dlstreamer_gst#247]
Hi,

I have build a yolov3 model and while training I have added few custom layers and changing of backbone, in another approach I have made my own custom build network.
In such customization cases, how I can convert my model to IR format?

**Comment by biyuehuang** [comment]
Hello, you can follow this guide to convert yolov3:
https://docs.openvino.ai/latest/omz_models_model_yolo_v3_tf.html

**Comment by adranit** [comment]
@divdaisymuffin , is this issue still actual?

**Comment by divdaisymuffin** [comment]
@adranit no it's been resolved we can close this.
