### ISSUE TITLE
Data modified with gvapython not persists

### ISSUE THREAD

**Issue by MGReyes** [openvinotoolkit/dlstreamer_gst#250]
Hello! I am trying to run the face recognition sample of the python folder with a gst-launch command. 
The steps of this process are:

1. detect faces (every N frames)
2. rescale rois of faces (for example to 1.15 is the default value in the example)
3. track objects
4. get landmarks
5. get faces features
6. compare faces features and do the reidentification
7. show the results (for example drawing rois and labels)

The second step of that pipeline is re-scale the rois of the face detector obtained with the `gvadetector`.  This post processing function is not implemented, so, I created a new module to use it with the `gvapython`. In that module I was able to modify the rois and using the `gvawatermark` I saw that the results were fine. But that works only when in step 1, the `gvadetect` has the property of `inference-interval=1`. With other values, for example `inference-interval=5`, the `gvawatermark` draw the scaled roi only when the `gvadetect` is applied, in other steps, the roi that track and draw is the one that correspond to the original detection and not to the re-scaled detection.

A sketch of the gvapython module used:
```py
class DetectionConverter:
    def process_frame(self, frame: VideoFrame):
        for roi in frame.regions():
            for tensor in roi.tensors():
                if not tensor.is_detection():
                   continue

                bbox = roi.normalized_rect()

                # rescale the bbox
                w_scaled = bbox.w * 1.15
                h_scaled = bbox.h * 1.15
                x0 = bbox.x + ((bbox.w - w_scaled) / 2)
                y0 = bbox.y + ((bbox.h - h_scaled) / 2)
                x1 = x0 + w_scaled
                y1 = y0 + h_scaled

                x0, x1 = np.clip([x0, x1], 0, 1.0)
                y0, y1 = np.clip([y0, y1], 0, 1.0)

                tensor['x_min'] = float(x0)
                tensor['y_min'] = float(y0)
                tensor['x_max'] = float(x1)
                tensor['y_max'] = float(y1)
        return True
```

When is not running the detection, the `frame.regions` are empty. So, I guess that the `gvatrack` is taking that data from other source (and the `gvadetect` is also writing there), but from the python wrapper I am not able to write it.

**Comment by adranit** [comment]
Hi @MGReyes ,
As far as I remember, gvatrack uses absolute coordinates of boxes for tracking, and ignores normalized coordinates. Try to scale and set  absolute coordinates too (x,y,w,h).

**Comment by MGReyes** [comment]
I tried it but the tensor have the data normalized. I print the data before. And if I set in pixels, the visualization fails showing a black screen. An example of a tensor before convert it:
```
-- tensor data: {'converter': 'tensor_to_bbox_ssd', 'confidence_threshold': 0.5, 'layer_name': 'detection_out', 'model_name': 'mobilenet_ssd_672x384', 'label_id': 1, 'confidence': 0.9999741315841675, 'x_min': 0.3334711194038391, 'x_max': 0.47851312160491943, 'y_min': 0.18580801784992218, 'y_max': 0.5296036750078201}
```

**Comment by adranit** [comment]
Little trick - absolute coordinates attached to "roi", not to "tensor"

**Comment by MGReyes** [comment]
Ok, I tried. Modifying the roi with absolute coordinates **and** the tensor with relative coordinates works fine. If I only modify one of them, it is not consistent.

**Comment by adranit** [comment]
It seems that the issue was resolved with w/a. @MGReyes feel free to reopen it if you have any concerns or questions
