### ISSUE TITLE
Dependent libraries of pkg-config 

### ISSUE THREAD

**Issue by hayashi57** [openvinotoolkit/dlstreamer_gst#251]
Option 1: Compile DL Streamer from sources on host system
Step 2: Install dependencies
Option 2 Downloading binaries
In the above guide, the links for [pkg-config_0.26-1_win32.zip](https://download.gnome.org/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip) are duplicated.
One is [gettext-runtime_0.18.1.1-2_win32.zip](https://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip), isn't it?

**Comment by adranit** [comment]
@hayashi57 , thanks for reporting the documentation issue.  You are right - the correct link is https://download.gnome.org/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip.

**Comment by adranit** [comment]
fixed
