### ISSUE TITLE
Video display gets stuck/frozen - with no errors in logs/terminal

### ISSUE THREAD

**Issue by Sharan-Sundar** [openvinotoolkit/dlstreamer_gst#256]
Hello,
I am currently performing license plate detection using a custom trained ssd-mobilenet model.
I am mostly using `OpenVINO - 2020.4.287` -  `Ubuntu 18.04.5` on a `Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz` . 

This is my pipeline -
`gst-launch-1.0 urisourcebin buffer-size=4096 uri=rtsp://182.63.8.7:5544/stream ! decodebin ! videoconvert n-threads=4 ! capsfilter caps="video/x-raw,format=BGRx" ! gvadetect model-instance-id=inf0 model=/home/user/model/objectdetection-FP32.xml device=CPU batch-size=1 threshold=0.4 inference-interval=1 nireq=1 ! queue ! gvatrack tracking-type=short-term ! queue ! gvawatermark name=gvawatermark ! videoconvert n-threads=4 ! fpsdisplaysink video-sink=xvimagesink sync=false`

This is a real-time streaming feed from an IP Camera and these are the stream parameters - 

![Video_Parameters](https://user-images.githubusercontent.com/43034406/147044959-4e2b2e71-4b1c-49e1-9a13-9ea2e8a4cfd0.png)

The problem is that display goes on properly and randomly freezes like this

![Frozen](https://user-images.githubusercontent.com/43034406/147043971-240424de-9eba-47a0-9708-c96ca618d91d.png)

And this is the output on the terminal

```
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://182.63.8.7:5544/stream
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
Progress: (request) Sent PLAY request
Got context from element 'vaapipostproc0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx0";
Redistribute latency...
```
I am aware the I can increase the `inference-interval` parameter but I think a single stream of 25 FPS at 1920 x 1080 should be alright for a processor like Xeon and so the problem seems to be somewhere else only.
I did go through #193  and #115 but it didn't seem to help.  The outputs made no difference till gst-debug-level 3. ll try running with higher gst-debug levels and get back to you.
Looking forward to your help.

Thanks,
Sharan

**Comment by brmarkus** [comment]
Have you tried to simplify the pipeline, e.g. to just decode and render the stream? Is that working stable?
As the XEON isn't a SOC with embedded GPU - do you have an external GPU?

If you see the pipeline stable with decoding and rendering only - can you incrementally add detection only, then add tracking, then add watermarking, please? To try narrowing-down what is causing the instability?

**Comment by Sharan-Sundar** [comment]
Yes @brmarkus , I tried what you suggested. A simple pipeline to just decode and render the stream also ends up frozen. I am not sure about the embedded GPU - might be a reason.

So that means it is not a problem with dlstreamer as a simple gstreamer pipeline without dlstreamer elements also freezes. Hence, I will close the issue for now. I will get back if I have any updates.
