### ISSUE TITLE
How do I inject label_id with gvapython?

### ISSUE THREAD

**Issue by JoeAYeung** [openvinotoolkit/dlstreamer_gst#258]
I use gvainference to inference with my yolov5 model, followed by gvapython to post-process the detection.
In my gvapython script, I use frame.add_region() to create ROI with detection label.
With this, gvawatermark draws all my bounding boxes in red.

<img width="1091" alt="Screen Shot 2021-12-31 at 4 43 26 PM" src="https://user-images.githubusercontent.com/96928924/147841783-1b4fee25-fc9f-495e-a393-1334cf309e63.png">

How can I also include the label_id in the ROI tensor, so GVA knows they are of different detection class such that gvawatermark uses different color for different object?

More to it, when I include gvatrack in my pipeline (after my gvapython), my detections are thought to be of different classes. I start having different color bounding boxes for the same detection class.

<img width="1087" alt="Screen Shot 2021-12-31 at 4 44 24 PM" src="https://user-images.githubusercontent.com/96928924/147841795-c3db87ae-e99f-45af-b205-8b00395f1ed2.png">

**Comment by nnshah1** [comment]
To set the label_id for a region you can retrieve the detection tensor from the region and set the label id, for example:

```python
region.detection()["label_id"] = 3
```

The tracking rectangles however are colored based on the object id and not the class id -

**Comment by JoeAYeung** [comment]
Got it! Unfortunately, I was under the impression that the colored rectangles are based on class id because with tracking, my object changed class id with the same object id...
