### ISSUE TITLE
Security barrier

### ISSUE THREAD

**Issue by mtashireva** [openvinotoolkit/dlstreamer_gst#38]
Security barrier shell sample uses model that is trained to recognize Chinese license plates, so recognition results of other country car license plates are not valid.

**Comment by mtashireva** [comment]
WORKAROUND: Use a video with Chinese cars and license ids to evaluate recognition quality. The sample is provided to get familiar with construction of security barrier pipelines and not evaluating recognition accuracy.

**Comment by intel-neena** [comment]
This issue is created as an FYI. It is not an issue to be fixed for DL Streamer.
