### ISSUE TITLE
SW decoder in GStreamer 1.14 doesn't support I420 format

### ISSUE THREAD

**Issue by mtashireva** [openvinotoolkit/dlstreamer_gst#42]
SW decoder in GStreamer 1.14   produces corrupted frames in I420 format.

**Comment by mtashireva** [comment]
WORKAROUND:
Option1. Use GStreamer 1.16
Option2. Add convert element into pipeline

**Comment by adranit** [comment]
Since [2021.2 release](https://github.com/openvinotoolkit/dlstreamer_gst/releases/tag/v1.3) GStreamer1.16 is required for DL Streamer.
