### ISSUE TITLE
Face alignment is missed when IE selected as the pre_proc

### ISSUE THREAD

**Issue by mtashireva** [openvinotoolkit/dlstreamer_gst#43]
Face alignment is additional pre-proc element of GvaClassify in face recognition use case. When IE is selected as the pre-proc - face alignment is skipped.

**Comment by mtashireva** [comment]
WORKAROUND:
Don't use "ie" pre-processor (pre-proc=ie) for GvaClassify in face recognition use case.

**Comment by MGReyes** [comment]
why are not going to fix it? It also would be great if print some message to know if this is preprocess function is running fine.
Also add the documentation to the wiki of how to set up in the model_proc file.
