### ISSUE TITLE
How does the gvawatermark connect to the rtmpsink

### ISSUE THREAD

**Issue by 1000sprites** [openvinotoolkit/dlstreamer_gst#56]
**一.Expectation**
gst elements gvawatermark connect to the rtmpsink by direct or indirect means

**二.Environment**
1.Ubuntu 18.04
2.gst-video-analytics:latest

**三.Process**
1.default gst-video-analytics:latest does not include rtmpsink, need to install:
```
apt-get install gstreamer1.0-plugins-bad –y
```
2.rtspsrc as the input, rtmpsink as the output
```
gst-launch-1.0 rtspsrc location="rtsp://192.168.0.10:554/user=admin&password=&channel=1&stream=0.sdp?" protocols=tcp ! rtph264depay ! h264parse ! queue ! flvmux ! rtmpsink location="rtmp://192.168.0.128:1935/stream/hello"
```
**notes: the above pipeline can work**
3.modify the file "/root/gst-video-analytics/samples/shell/face_detection_and_classification.sh"
```
gst-launch-1.0 --gst-plugin-path ${GST_PLUGIN_PATH} \
$SOURCE_ELEMENT ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! \
gvadetect model=$DETECT_MODEL_PATH device=$DEVICE pre-proc=$PRE_PROC ! queue ! \
gvawatermark ! videoconvert ! x264enc ! h264parse ! flvmux \
! rtmpsink location="rtmp://192.168.0.128:1935/stream/hello"
```
run ./face_detection_and_classification.sh /dev/video0: 
```
root@ubuntu:~/gst-video-analytics/samples/shell# ./face_detection_and_classification.sh /dev/video0
[setup_env.sh] GStreamer-plugins environment initialized
[setlocale.sh] C locale is set
Running sample with the following parameters:
GST_PLUGIN_PATH=/root/gst-video-analytics/scripts/../build/intel64/Release/lib:/usr/lib/gst-video-analytics/:/root/gst-video-analytics/
LD_LIBRARY_PATH=/opt/intel/dldt/inference-engine/external/hddl/lib
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
```
There was no error, but VLC cannot get RTMP by URL rtmp://192.168.0.128:1935/stream/hello

So how does the gvawatermark connect to the rtmpsink, that I can get the RTMP flow.

**Comment by umed** [comment]
@1000sprites, you cannot just install `gstreamer1.0-plugins-bad` from ppa. There is version mismatch. `gst-plugins-bad` from ppa have version 1.14.5, but our image builds gstreamer and its plugins on version 1.16.0. That is first problem.

However, gstreamer should be ABI compatible with previous version. If we will assume that it might work we can export environment variable `GST_DEBUG=3` then run pipeline again. It will show errors

**Comment by 1000sprites** [comment]
@umed thanks. Since I am still in the trial and error stage, not thinking about compatibility or other issues. I'm new for gstreamer, can only study a few examples. Examples related to the gvawatermark:
```
gvawatermark ! videoconvert ! fpsdisplaysink video-sink=xvimagesink sync=false
gvawatermark ! videoconvert ! vaapih264enc ! filesink location=out.h264
```
I haven't been able to find some examples with gvawatermark and rtmpsink.

**Comment by mliu2020** [comment]
Hi @1000sprites ,

It has been a while for this issue, do you still need help?

If this issue was solved, can I close it?

Mark

**Comment by mliu2020** [comment]
Hi @1000sprites,

Let me close this issue for now, feel free to open a new ticket for more questions.

Mark
