### ISSUE TITLE
Multilevel or back to back detectors

### ISSUE THREAD

**Issue by vtpl1** [openvinotoolkit/dlstreamer_gst#57]
Hi,
Is there any option to have back to back detectors in the single pipeline?
detection->classification in the roi is there.
But is there any option for 
detection->detection in given roi?

**Comment by mikhail-nikolskiy** [comment]
Hi,

Not supported directly by gvadetect at the moment.

But you can do that with little C++/Python programming: build gvadetect->gvaclassify pipeline and set C++/Python callback at gvaclassify source pad to convert tensor data created by gvaclassify into bounding boxes.

Is it for use case similar to detect vehicle -> detect license place for each vehicle?

**Comment by vtpl1** [comment]
Hi, @mikhail-nikolskiy , thank you for your response. Yes the application is similar to detect vehicle -> detect license plate.
How to write back the meta data generated by the python code?

I was trying to modify the existing code and put detection within detected region of first level. There I am getting buffer is not writable. Any clue?

**Comment by wang7393** [comment]
@vtpl1 same problem,have you solve it ?

**Comment by easychizy** [comment]
Hi @vtpl1 ,
Sorry for the late response, I assume you are changing the follow code based on @mikhail-nikolskiy advice, this is my understanding:
You should remove the label setting logic from [age_gender_classification.py](https://github.com/opencv/gst-video-analytics/blob/master/samples/gst_launch/gvapython/face_detection_and_classification/postproc_callbacks/age_gender_classification.py) loop and replace it with the logic like [ssd_object_detection.py](https://github.com/opencv/gst-video-analytics/blob/master/samples/python/draw_face_attributes/postproc_callbacks/ssd_object_detection.py) and finally call frame.add_region()
but initially you can add some random values, so you can make a quick try by call add_region() only.
Are you doing this or something differently?
Mark Liu

**Comment by wang7393** [comment]
@easychizy I write a new plugin: I want to use "frame.pop_region()" to delete regions  and use "frame.add_region" to add regions. and then errors occur: 

(gst-launch-1.0:33): GStreamer-CRITICAL **: 01:01:59.980: gst_buffer_remove_meta: assertion 'gst_buffer_is_writable (buffer)' failed
terminate called after throwing an instance of 'std::runtime_error'
  what():  GVA::VideoFrame: Underlying GstVideoRegionOfInterestMeta for RegionOfInterest at index 0 doesn't belong to this VideoFrame

(gst-launch-1.0:1854): GStreamer-CRITICAL **: 01:49:04.477: gst_buffer_add_meta: assertion 'gst_buffer_is_writable (buffer)' failed


but I find that it also can add and pop regions in gvatrack plugin/vas/tracker.cpp,why?

**Comment by mikhail-nikolskiy** [comment]
The gvadetect element guarantees writable buffer on source pad, as gvadetect calls gst_buffer_make_writable before pushing to next element. Unfortunaly this is not the case for gvaclassify, it doesn't call gst_buffer_make_writable.

Two options to solve "writable buffer" problem
1. Create and register simple GStreamer element which calls gst_buffer_make_writable before add_region. This helps as element can output new buffer, callback can't.
2. Attach bounding box information as custom fields "x","y","w","h" into existent meta, like this code
    GVA::VideoFrame video_frame(buffer, caps);
    // Iterate detected objects and all attributes (tensors)
    for (GVA::RegionOfInterest &roi : video_frame.regions()) {
        for (auto tensor : roi.tensors()) {
            vector<float> data = tensor.data<float>();
            double x, y, w, h;
            
            .. calculate x, y, w, h from tensor data            
            
            tensor.set_double("x", x);
            tensor.set_double("y", y);
            tensor.set_double("w", w);
            tensor.set_double("h", h);

**Comment by wang7393** [comment]
@mikhail-nikolskiy I create and register a GStreamer element reference on the gvatrack to implement my own tracking function，and also I have done this:
buffer= gst_buffer_make_writable(buffer);
 GVA::VideoFrame frame(buffer, track_video_info.get());
 for (auto &roi : frame.regions()) 
{
     frame.pop_region();
 }

but it also occur the same error,why?

**Comment by wang7393** [comment]
@easychizy  sorry ,I did not do that.

**Comment by Sharan-Sundar** [comment]
Does gvadetect -> gstreamercrop element - > gvadetect work? Is that a possible solution?

**Comment by mliu2020** [comment]
Hi @Sharan-Sundar,

This pipeline should not work for now. We are going to add a feature to support “detect vehicle -> detect license place for each vehicle” use case.

If you has a different use case, I would suggest you to post a new issue.

Mark

**Comment by Sharan-Sundar** [comment]
Hi @mliu2020 . Yes I also have the same use case(“detect vehicle -> detect license place for each vehicle”) and it's great that you are adding a new feature. Can you tell me approximately when it will come out? Just so that I can plan a temporary fix as of now.

**Comment by adranit** [comment]
Since [2021.2 release](https://github.com/openvinotoolkit/dlstreamer_gst/releases/tag/v1.3) all the inference elements have "inference-region" property that allows to use cascades of gvadetect elements in a pipeline.

https://github.com/openvinotoolkit/dlstreamer_gst/wiki/gvadetect
```
  inference-region    : Identifier responsible for the region on which inference will be performed
                        flags: readable, writable
                        Enum "InferenceRegionType" Default: 0, "full-frame"
                           (0): full-frame       - Perform inference for full frame
                           (1): roi-list         - Perform inference for roi list
```
Usage example:
`... ! gvadetect inference-region=full-frame ! gvadetect inference-region=roi-list ! ...`

**Comment by intel-neena** [comment]
@vtpl1 @wang7393 @Sharan-Sundar I am closing this issue as the feature is added in 2021.2 release. Please see adranit's comment above and feel free to create a new issue if any further help is needed.
