### ISSUE TITLE
mqtt reconnection

### ISSUE THREAD

**Issue by xwu2git** [openvinotoolkit/dlstreamer_gst#62]
gvametapublisher needs to handle mqtt connection status more robustly and try to reconnect:
(1) If by the time gst is started, the mqtt broker is not yet available.
(2) The mqtt broker is disconnected and migrated to a different worker in the Kubernete cluster.

**Comment by intel-neena** [comment]
This issue was fixed in 2021.1 release. Can you please try the latest version? Please feel free to reopen if the issue still persists.
