### ISSUE TITLE
gvatrack removes vectors except detection

### ISSUE THREAD

**Issue by vtimofeev01** [openvinotoolkit/dlstreamer_gst#78]
gvatrack removes vectors except detection! what to do?

**Comment by adranit** [comment]
Hi @vtimofeev01,
This is a known issue in the current version of the tracker. We are working on it and going to resolve the issue by 2021.1 release. Sorry for any inconvenience.

**Comment by adranit** [comment]
The issue was resolved in 2021.1 release.
