### ISSUE TITLE
WARNING: erroneous pipeline: no element "gvaaudiodetect"

### ISSUE THREAD

**Issue by sanjeevx007** [openvinotoolkit/dlstreamer_gst#89]
I checked out the branch "preview/audio-detect" to use the Audio Event Detection feature.

After installing GVA using Docker env, i proceeded to run the "download_audio_models.sh" script in the path "~/gst-video-analytics/samples/gst_launch/audio_detect" and then ran the "audio_event_detection.sh" script. The following shows the output of the above:

root@<user>:~/gst-video-analytics/samples/gst_launch/audio_detect# ./audio_event_detection.sh 
gst-launch-1.0 filesrc location=how_are_you_doing.wav ! decodebin ! audioresample ! audioconvert ! audio/x-raw, channels=1,format=S16LE,rate=16000 ! audiomixer output-buffer-duration=100000000 ! gvaaudiodetect model=models/aclnet_des_53_fp32.xml model-proc=./model_proc/aclnet_des_53_fp32.json sliding-window=0.2 ! gvametaconvert ! gvametapublish file-format=json-lines ! fakesink
**WARNING: erroneous pipeline: no element "gvaaudiodetect"**

Any idea what's causing this? I can run the other sample applications fine: face_detection_and_classification & vehicle_pedestrian_tracking (bounding boxes appear for tracking/detection/classification)

**Comment by nnshah1** [comment]
@sanjeevx007 Can you describe the steps you used to create the Docker env with GVA? It looks like the gvaudiodetect element is either not built or not found at runtime. Can you also post the value of GST_PLUGIN_PATH?

**Comment by sanjeevx007** [comment]
Hi @nnshah1 I used the docker build steps using the latest package I downloaded from the OpenVINO website:

1. cd ~/gva/gst-video-analytics/docker
2. ./build_docker_image.sh package
3. xhost local:root
4. cd ~/gva/gst-video-analytics/docker  # essential
5. export DATA_PATH=~/gva/data  # essential
6. sudo ./run_docker_container.sh --video-examples-path=$DATA_PATH/video --intel-models-path=$DATA_PATH/models/intel --models-path=$DATA_PATH/models/common --image-name=gst-video-analytics:latest

I noticed that there was no "openvino" folder in /opt/intel (only a "dldt" folder) therefore I installed it manually once inside the docker env.

GST_PLUGIN_PATH: /opt/intel/openvino_2020.4.287/data_processing/dl_streamer/lib:/opt/intel/openvino_2020.4.287/data_processing/gstreamer/lib/gstreamer-1.0

I think this missing openvino folder and me having to manually install it might be the cause of the problem (does not point to the right audio elements)

**Comment by intel-neena** [comment]
@sanjeevx007 Do you still need any help on this?

**Comment by sanjeevx007** [comment]
Nope got it figured out. Will proceed to close this issue.

**Comment by intel-neena** [comment]
Thank you for using DL Streamer!!
