### ISSUE TITLE
New post-processing convertor for gvadetect

### ISSUE THREAD

**Issue by mcleonard** [openvinotoolkit/dlstreamer_gst#90]
I'm using `gvadetect` for a project, but the available post-processing convertors don't handle the output of my detection model. I wrote a new convertor that I'd like to contribute.

This converter handles models with a single output tensor of shape P x (N + 4) where N is the number of classes and P is the number of proposals. For each proposal, the first N values are the class scores. The last 4 values are for the bounding box with format [x_min, y_min, x_max, y_max].

From the class scores it finds the class with the highest score to get the label id and confidence. NMS is performed before adding the ROIs, similar to the YOLO convertors.

I have the convertor implemented already.

**Comment by mcleonard** [comment]
I'm training a model from here: https://github.com/qfgaohao/pytorch-ssd, mobilenetv2-ssd-lite

The model returns two tensors, one with class scores and one with bounding boxes. I concatenate the tensors into one tensor.

Then I convert PyTorch -> ONNX -> OpenVINO.

**Comment by intel-neena** [comment]
@mcleonard Are there other examples of models that use this output type (P x (N+4))? In terms of adding converters to the main repo, we want to make sure to focus on post-processors that have wide applicability. If this is not widely applicable it would still be great to include a link to demonstrate how to customize DL Streamer for custom models. Thank you for your contribution.

**Comment by mcleonard** [comment]
I don't know if there are other models that work like this. The PyTorch model I used returns two output tensors: the classification scores and the bounding box regression. The existing post-processors only work with one output that is formatted like `[class_id, confidence, bbox1, bbox2, bbox3, bbox4]`.

I tried to convert the two tensors into this format. But I was getting an error with the TopK operation somewhere when  converting PyTorch -> ONNX -> OpenVINO. I wound up concatenating the two tensors into one tensor and finding the max score & class id in the post-processor. Which is how I ended up with this (P x (N+4)) format.

**Comment by Sharan-Sundar** [comment]
Are post-processing convertors for yolov3_tiny available in gvadetect? I am not getting any roi in frame.regions() in the callback(draw_face_attributes.py). How can I verify if it is something to do with the weights itself or gvadetect post-processing ?

**Comment by intel-neena** [comment]
@Sharan-Sundar yolov3_tiny post-processing is supported in gvadetect from Release 2020.4. You need to use the model-proc [yolo-v3-tiny.json](https://github.com/openvinotoolkit/dlstreamer_gst/blob/master/samples/model_proc/yolo-v3-tiny.json). Please open a new issue if you are still facing a problem.

**Comment by intel-neena** [comment]
@mcleonard since this output format is not generic, please use C++/ Python callback or gvapython to implement postprocessing.
