### ISSUE TITLE
Can't use onnx model directly

### ISSUE THREAD

**Issue by chungyehwangai** [openvinotoolkit/dlstreamer_gst#97]
Below command failed to load ONNX model. gva modules expect DL model is IR files/compiled model.

gst-launch-1.0 filesrc location=video.mp4 ! decodebin ! videoconvert ! video/x-raw,format=BGRx ! gvaclassify model=openvino_models/public/resnet-50-pytorch/resnet-v1-50.onnx ! videoconvert ! fpsdisplaysink video-sink=fakesink sync=true

Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0: base_inference plugin intitialization failed
Additional debug info:
/root/gst-video-analytics/gst/inference_elements/base/inference_singleton.cpp(136): acquire_inference_instance (): /GstPipeline:pipeline0/GstGvaClassify:gvaclassify0:

Failed to construct OpenVINOImageInference
 Failed to import pre-compiled model
  [NOT_IMPLEMENTED]

ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...

if change "inference_backend/image_inference/openvino/model_loader.cpp" as below, it can use onnx model.

bool ModelLoader::is_ir_model(const std::string &model_path) {
    bool is_ir = false;
    if (model_path.find(".xml") != std::string::npos) {
        const std::string model_bin = fileNameNoExt(model_path) + ".bin";
        is_ir = Utils::fileExists(model_path) && Utils::fileExists(model_bin);
    }
    return true; //is_ir;
}

**Comment by intel-neena** [comment]
GVA elements do not directly support ONNX yet. Thank you for your suggested code changes. There might be additional post-processing changes required in gvadetect and gvaclassify. We have captured this feature request and it will be part of our planning for the upcoming releases. Thanks for using DL Streamer!

**Comment by adranit** [comment]
Since 2021.2 release DL Streamer can directly use four ONNX models ([wiki](https://github.com/openvinotoolkit/dlstreamer_gst/wiki/supported-models#object-detection-and-recognition-models-onnx-model-zoo)): YoloV2, YoloV2Tiny, MobileNet and FER+ Emotion Recognition.

Note that other ONNX models also can be loaded but they may require additional pre- and post- processing.
