### ISSUE TITLE
gvametpublish mqtt fail

### ISSUE THREAD

**Issue by zizo1111** [openvinotoolkit/dlstreamer_gst#99]
Hello, 
I am  trying to do the inference on multiple rtsp streams, then send the results using gavmetapublish through mqtt. The pipelines start with nor problem, but after sometime they disconnect due to this error. I tried reinstalling the plugins and paho mqtt in hope to find a solution but was not successful.

Teminal error:
`ERROR: from element /GstPipeline:pipeline0/GstGvaMetaPublish:gvametapublish0: Failed to write message
Additional debug info:
/root/gst-video-analytics/gst/elements/gvametapublish/gstgvametapublish.c(425): gst_gva_meta_publish_transform_ip (): /GstPipeline:pipeline0/GstGvaMetaPublish:gvametapublish0:
Failed to write message for method MQTT publish. Connection to the broker may have been lost
Execution ended after 0:01:08.685707431
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
`
Pipeline example 
`gst-launch-1.0  --gst-plugin-path ${GST_PLUGIN_PATH} \
				rtspsrc location=rtsp://127.0.0.1:8554/cam01 \
				drop-on-latency=true  \
				do-retransmission=false \
				protocols=GST_RTSP_LOWER_TRANS_UDP \
				udp-reconnect=true \
				! decodebin ! video/x-raw ! videoconvert  \
				! gvadetect model-instance-id=inf0 model=${model_path} device=CPU model_proc=${proc_path} threshold=0.7 batch-size=1 no-block=true ! queue \
				! gvatrack tracking-type=short-term   \
				! gvametaconvert format=json  \
				! gvametapublish  method=mqtt address=127.0.0.1:1883 mqtt-client-id=clientIdValue topic="MQTTDetections01" timeout=10000 \
				! queue ! fakesink &
`
Ubuntu 18
openvino_2020.4.287

Thanks in advance

**Comment by easychizy** [comment]
hi @zizo1111,

From the error message, it seems the connection was lost. Did you try to confirm the connection to port "1883"?

Mark

**Comment by cgdougla** [comment]
Hi @zizo1111,

What looks like the problem to me is that you say there are multiple of this pipeline running. If you use the same mqtt-client-id for a second pipeline, it will stop the first one (by MQTT standards) since the server will assume that it is the same client trying to reconnect after some failure. Long story short, change the "clientIdValue" for each pipeline or don't specify one at all and the gvametapublish element will generate one for you.

**Comment by intel-neena** [comment]
@zizo1111 Can we close this issue if you do not require any further help?

**Comment by zizo1111** [comment]
Thanks, problem solved!
